-- PostgreSQL semantic baseline paired with SQLite schema version 23.
-- Generated once from the reviewed static contract; never translated at runtime.

CREATE TABLE agent_access_tokens (
  id text NOT NULL,
  agent_profile_id text NOT NULL,
  token_hash text NOT NULL,
  scopes_json jsonb NOT NULL DEFAULT '[]'::jsonb,
  default_notebook_id text NOT NULL,
  expires_at timestamp with time zone,
  revoked_at timestamp with time zone,
  last_used_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL,
  CONSTRAINT pk_agent_access_tokens PRIMARY KEY (id),
  CONSTRAINT uq_agent_access_tokens_token_hash UNIQUE (token_hash)
);

CREATE TABLE agent_profiles (
  id text NOT NULL,
  owner_id text NOT NULL,
  name text NOT NULL,
  description text NOT NULL DEFAULT '',
  status text NOT NULL DEFAULT 'active',
  created_at timestamp with time zone NOT NULL,
  updated_at timestamp with time zone NOT NULL,
  CONSTRAINT pk_agent_profiles PRIMARY KEY (id),
  CONSTRAINT ck_agent_profiles_status CHECK (status IN ('active', 'revoked'))
);

CREATE TABLE agent_token_notebooks (
  token_id text NOT NULL,
  notebook_id text NOT NULL,
  CONSTRAINT pk_agent_token_notebooks PRIMARY KEY (token_id, notebook_id)
);

CREATE TABLE answers (
  id text NOT NULL,
  notebook_id text NOT NULL,
  question text NOT NULL DEFAULT '',
  payload jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamp with time zone NOT NULL,
  conversation_id text,
  ordinal bigint GENERATED BY DEFAULT AS IDENTITY,
  CONSTRAINT pk_answers PRIMARY KEY (id),
  CONSTRAINT uq_answers_ordinal UNIQUE (ordinal)
);

CREATE TABLE ask_jobs (
  id text NOT NULL,
  notebook_id text NOT NULL,
  conversation_id text NOT NULL DEFAULT '',
  created_by text NOT NULL DEFAULT '',
  mode text NOT NULL DEFAULT '',
  question text NOT NULL DEFAULT '',
  status text NOT NULL DEFAULT 'running',
  trace_json jsonb NOT NULL DEFAULT '[]'::jsonb,
  answer_id text NOT NULL DEFAULT '',
  error text NOT NULL DEFAULT '',
  created_at timestamp with time zone,
  updated_at timestamp with time zone,
  CONSTRAINT pk_ask_jobs PRIMARY KEY (id)
);

CREATE TABLE ask_trace_steps (
  job_id text NOT NULL,
  seq bigint NOT NULL,
  step_json jsonb NOT NULL,
  created_at timestamp with time zone,
  CONSTRAINT pk_ask_trace_steps PRIMARY KEY (job_id, seq)
);

CREATE TABLE auth_sessions (
  token text NOT NULL,
  user_id text NOT NULL,
  created_at timestamp with time zone NOT NULL,
  expires_at timestamp with time zone NOT NULL,
  last_seen_at timestamp with time zone NOT NULL,
  CONSTRAINT pk_auth_sessions PRIMARY KEY (token)
);

CREATE TABLE canonical_relations (
  notebook_id text NOT NULL,
  canonical_src text NOT NULL,
  edge_type text NOT NULL,
  canonical_tgt text NOT NULL,
  support_count bigint NOT NULL DEFAULT 1,
  source_count bigint NOT NULL DEFAULT 1,
  sample_relation_ids jsonb NOT NULL DEFAULT '[]'::jsonb,
  updated_at timestamp with time zone NOT NULL,
  CONSTRAINT pk_canonical_relations PRIMARY KEY (notebook_id, canonical_src, edge_type, canonical_tgt)
);

CREATE TABLE chunk_embeddings (
  chunk_id text NOT NULL,
  notebook_id text NOT NULL,
  vector bytea NOT NULL,
  created_at timestamp with time zone NOT NULL,
  CONSTRAINT pk_chunk_embeddings PRIMARY KEY (chunk_id)
);

CREATE TABLE chunks (
  id text NOT NULL,
  notebook_id text NOT NULL,
  source_id text NOT NULL,
  text text NOT NULL,
  section_path text NOT NULL DEFAULT '',
  element_ids jsonb NOT NULL DEFAULT '[]'::jsonb,
  created_at timestamp with time zone NOT NULL,
  ordinal bigint GENERATED BY DEFAULT AS IDENTITY,
  CONSTRAINT pk_chunks PRIMARY KEY (id),
  CONSTRAINT uq_chunks_ordinal UNIQUE (ordinal)
);

CREATE TABLE communities (
  id text NOT NULL,
  notebook_id text NOT NULL,
  level bigint NOT NULL DEFAULT 0,
  member_ids jsonb NOT NULL,
  size bigint NOT NULL,
  title text NOT NULL DEFAULT '',
  summary text NOT NULL DEFAULT '',
  findings jsonb NOT NULL DEFAULT '[]'::jsonb,
  created_at timestamp with time zone NOT NULL,
  CONSTRAINT pk_communities PRIMARY KEY (id)
);

CREATE TABLE community_members (
  canonical_id text NOT NULL,
  notebook_id text NOT NULL,
  level bigint NOT NULL DEFAULT 0,
  community_id text NOT NULL,
  canonical_name text NOT NULL DEFAULT '',
  centrality double precision NOT NULL DEFAULT 0
);

CREATE TABLE concept_clusters (
  id text NOT NULL,
  notebook_id text NOT NULL,
  canonical_id text NOT NULL,
  member_object_id text NOT NULL,
  canonical_name text NOT NULL,
  object_type text NOT NULL DEFAULT 'concept',
  canonical_description text NOT NULL DEFAULT '',
  canonical_desc_sig text NOT NULL DEFAULT '',
  created_at timestamp with time zone NOT NULL,
  CONSTRAINT pk_concept_clusters PRIMARY KEY (id)
);

CREATE TABLE concept_comentions (
  notebook_id text NOT NULL,
  canonical_a text NOT NULL,
  canonical_b text NOT NULL,
  bridge_claims bigint NOT NULL DEFAULT 1,
  CONSTRAINT pk_concept_comentions PRIMARY KEY (notebook_id, canonical_a, canonical_b)
);

CREATE TABLE concept_merge_candidates (
  id text NOT NULL,
  notebook_id text NOT NULL,
  canonical_a text NOT NULL,
  canonical_b text NOT NULL,
  score double precision NOT NULL,
  status text NOT NULL DEFAULT 'pending',
  created_at timestamp with time zone NOT NULL,
  updated_at timestamp with time zone NOT NULL,
  confidence double precision NOT NULL DEFAULT 0,
  rationale text NOT NULL DEFAULT '',
  reviewed_by text NOT NULL DEFAULT '',
  seed_a text NOT NULL DEFAULT '',
  seed_b text NOT NULL DEFAULT '',
  CONSTRAINT pk_concept_merge_candidates PRIMARY KEY (id)
);

CREATE TABLE concept_whitelist (
  term text NOT NULL,
  note text NOT NULL DEFAULT '',
  created_at timestamp with time zone NOT NULL,
  CONSTRAINT pk_concept_whitelist PRIMARY KEY (term)
);

CREATE TABLE conversations (
  id text NOT NULL,
  notebook_id text NOT NULL,
  title text DEFAULT '',
  created_by text DEFAULT '',
  created_at timestamp with time zone NOT NULL,
  updated_at timestamp with time zone NOT NULL,
  CONSTRAINT pk_conversations PRIMARY KEY (id)
);

CREATE TABLE element_embeddings (
  element_id text NOT NULL,
  source_id text NOT NULL,
  notebook_id text NOT NULL,
  vector bytea NOT NULL,
  created_at timestamp with time zone NOT NULL,
  CONSTRAINT pk_element_embeddings PRIMARY KEY (element_id)
);

CREATE TABLE extraction_runs (
  id text NOT NULL,
  notebook_id text NOT NULL,
  source_id text,
  run_type text NOT NULL,
  status text NOT NULL,
  error_message text NOT NULL DEFAULT '',
  created_at timestamp with time zone NOT NULL,
  updated_at timestamp with time zone NOT NULL,
  ordinal bigint GENERATED BY DEFAULT AS IDENTITY,
  CONSTRAINT pk_extraction_runs PRIMARY KEY (id),
  CONSTRAINT uq_extraction_runs_ordinal UNIQUE (ordinal)
);

CREATE TABLE feedback (
  id text NOT NULL,
  answer_id text NOT NULL,
  notebook_id text NOT NULL,
  rating text NOT NULL,
  comment text NOT NULL DEFAULT '',
  created_at timestamp with time zone NOT NULL,
  CONSTRAINT pk_feedback PRIMARY KEY (id)
);

CREATE TABLE kg_build_jobs (
  id text NOT NULL,
  notebook_id text NOT NULL,
  created_by text NOT NULL DEFAULT '',
  mode text NOT NULL,
  status text NOT NULL DEFAULT 'running',
  stage text NOT NULL DEFAULT 'probing',
  total_sources bigint NOT NULL DEFAULT 0,
  completed_sources bigint NOT NULL DEFAULT 0,
  failed_sources bigint NOT NULL DEFAULT 0,
  error_code text NOT NULL DEFAULT '',
  error_message text NOT NULL DEFAULT '',
  created_at timestamp with time zone NOT NULL,
  updated_at timestamp with time zone NOT NULL,
  finished_at timestamp with time zone,
  ordinal bigint GENERATED BY DEFAULT AS IDENTITY,
  CONSTRAINT pk_kg_build_jobs PRIMARY KEY (id),
  CONSTRAINT uq_kg_build_jobs_ordinal UNIQUE (ordinal)
);

CREATE TABLE kg_cluster_scratch (
  notebook_id text NOT NULL,
  run_id text NOT NULL,
  object_id text NOT NULL,
  seed text NOT NULL
);

CREATE TABLE kg_conflict_candidates (
  id text NOT NULL,
  notebook_id text NOT NULL,
  kind text NOT NULL,
  left_ref text NOT NULL,
  right_ref text NOT NULL,
  conflict_type text,
  resolution text,
  winner_ref text,
  resolved_payload jsonb,
  confidence double precision,
  rationale text,
  status text NOT NULL DEFAULT 'pending',
  created_at timestamp with time zone NOT NULL,
  updated_at timestamp with time zone NOT NULL,
  CONSTRAINT pk_kg_conflict_candidates PRIMARY KEY (id)
);

CREATE TABLE kg_rebuild_checkpoint (
  notebook_id text NOT NULL,
  input_version text NOT NULL,
  stage text NOT NULL,
  item_key text NOT NULL,
  payload jsonb NOT NULL,
  created_at timestamp with time zone NOT NULL,
  CONSTRAINT pk_kg_rebuild_checkpoint PRIMARY KEY (notebook_id, input_version, stage, item_key)
);

CREATE TABLE knowhow_cell_code (
  id text NOT NULL,
  row_id text NOT NULL,
  column_id text NOT NULL,
  code_text text NOT NULL,
  language text NOT NULL DEFAULT '',
  updated_by text NOT NULL DEFAULT '',
  cell_content_hash text NOT NULL,
  created_at timestamp with time zone NOT NULL,
  updated_at timestamp with time zone NOT NULL,
  CONSTRAINT pk_knowhow_cell_code PRIMARY KEY (id),
  CONSTRAINT uq_knowhow_cell_code_row_id_column_id UNIQUE (row_id, column_id)
);

CREATE TABLE knowhow_cells (
  id text NOT NULL,
  row_id text NOT NULL,
  column_id text NOT NULL,
  content_md text NOT NULL DEFAULT '',
  updated_at timestamp with time zone NOT NULL,
  CONSTRAINT pk_knowhow_cells PRIMARY KEY (id),
  CONSTRAINT uq_knowhow_cells_row_id_column_id UNIQUE (row_id, column_id)
);

CREATE TABLE knowhow_columns (
  id text NOT NULL,
  table_id text NOT NULL,
  name text NOT NULL,
  role text NOT NULL DEFAULT 'plain',
  position bigint NOT NULL,
  CONSTRAINT pk_knowhow_columns PRIMARY KEY (id)
);

CREATE TABLE knowhow_rows (
  id text NOT NULL,
  table_id text NOT NULL,
  position bigint NOT NULL,
  projection_status text NOT NULL DEFAULT 'pending',
  created_at timestamp with time zone NOT NULL,
  updated_at timestamp with time zone NOT NULL,
  CONSTRAINT pk_knowhow_rows PRIMARY KEY (id)
);

CREATE TABLE knowhow_tables (
  id text NOT NULL,
  notebook_id text NOT NULL,
  title text NOT NULL,
  description text NOT NULL DEFAULT '',
  mutation_seq bigint NOT NULL DEFAULT 0,
  hidden_source_id text,
  created_by text NOT NULL DEFAULT '',
  created_at timestamp with time zone NOT NULL,
  updated_at timestamp with time zone NOT NULL,
  CONSTRAINT pk_knowhow_tables PRIMARY KEY (id)
);

CREATE TABLE knowledge_embeddings (
  object_id text NOT NULL,
  notebook_id text NOT NULL,
  vector bytea NOT NULL,
  created_at timestamp with time zone NOT NULL,
  CONSTRAINT pk_knowledge_embeddings PRIMARY KEY (object_id)
);

CREATE TABLE knowledge_object_sources (
  object_id text NOT NULL,
  source_id text NOT NULL,
  notebook_id text NOT NULL
);

CREATE TABLE knowledge_objects (
  id text NOT NULL,
  notebook_id text NOT NULL,
  object_type text NOT NULL,
  status text NOT NULL DEFAULT 'approved',
  owner text NOT NULL DEFAULT '',
  payload jsonb NOT NULL DEFAULT '{}'::jsonb,
  evidence jsonb NOT NULL DEFAULT '[]'::jsonb,
  source_candidate_id text,
  source_id text NOT NULL DEFAULT '',
  created_at timestamp with time zone NOT NULL,
  updated_at timestamp with time zone NOT NULL,
  last_reviewed timestamp with time zone,
  ordinal bigint GENERATED BY DEFAULT AS IDENTITY,
  CONSTRAINT pk_knowledge_objects PRIMARY KEY (id),
  CONSTRAINT uq_knowledge_objects_ordinal UNIQUE (ordinal)
);

CREATE TABLE knowledge_relations (
  id text NOT NULL,
  notebook_id text NOT NULL,
  source_id text,
  source_object_id text NOT NULL,
  target_object_id text NOT NULL,
  edge_type text NOT NULL,
  evidence jsonb NOT NULL DEFAULT '[]'::jsonb,
  created_at timestamp with time zone NOT NULL,
  review_status text NOT NULL DEFAULT 'pending',
  CONSTRAINT pk_knowledge_relations PRIMARY KEY (id)
);

CREATE TABLE memory_embeddings (
  memory_id text NOT NULL,
  model text NOT NULL,
  dimension bigint NOT NULL,
  vector bytea NOT NULL,
  updated_at timestamp with time zone NOT NULL,
  CONSTRAINT pk_memory_embeddings PRIMARY KEY (memory_id),
  CONSTRAINT ck_memory_embeddings_dimension CHECK (dimension > 0)
);

CREATE TABLE memory_items (
  id text NOT NULL,
  notebook_id text NOT NULL,
  created_by text NOT NULL,
  agent_profile_id text,
  source_answer_id text,
  origin text NOT NULL,
  status text NOT NULL,
  promotion_state text NOT NULL DEFAULT 'none',
  title text NOT NULL,
  content_md text NOT NULL,
  tags_json jsonb NOT NULL DEFAULT '[]'::jsonb,
  confirmed_by text,
  confirmed_at timestamp with time zone,
  embedding_status text NOT NULL DEFAULT 'pending',
  embedding_error text NOT NULL DEFAULT '',
  created_at timestamp with time zone NOT NULL,
  updated_at timestamp with time zone NOT NULL,
  CONSTRAINT pk_memory_items PRIMARY KEY (id),
  CONSTRAINT ck_memory_items_origin CHECK (origin IN ('ask_answer', 'external_agent')),
  CONSTRAINT ck_memory_items_status CHECK (status IN ('candidate', 'confirmed', 'rejected', 'deprecated')),
  CONSTRAINT ck_memory_items_promotion_state CHECK (promotion_state IN ('none', 'proposed', 'approved', 'rejected'))
);

CREATE TABLE memory_provenance (
  id text NOT NULL,
  memory_id text NOT NULL,
  origin text NOT NULL,
  payload_json jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamp with time zone NOT NULL,
  CONSTRAINT pk_memory_provenance PRIMARY KEY (id),
  CONSTRAINT uq_memory_provenance_memory_id UNIQUE (memory_id),
  CONSTRAINT ck_memory_provenance_origin CHECK (origin IN ('ask_answer', 'external_agent'))
);

CREATE TABLE memory_revisions (
  id text NOT NULL,
  memory_id text NOT NULL,
  revision bigint NOT NULL,
  title text NOT NULL,
  content_md text NOT NULL,
  tags_json jsonb NOT NULL DEFAULT '[]'::jsonb,
  status text NOT NULL,
  promotion_state text NOT NULL,
  changed_by text NOT NULL,
  change_reason text NOT NULL DEFAULT '',
  created_at timestamp with time zone NOT NULL,
  CONSTRAINT pk_memory_revisions PRIMARY KEY (id),
  CONSTRAINT uq_memory_revisions_memory_id_revision UNIQUE (memory_id, revision),
  CONSTRAINT ck_memory_revisions_revision CHECK (revision > 0),
  CONSTRAINT ck_memory_revisions_status CHECK (status IN ('candidate', 'confirmed', 'rejected', 'deprecated')),
  CONSTRAINT ck_memory_revisions_promotion_state CHECK (promotion_state IN ('none', 'proposed', 'approved', 'rejected'))
);

CREATE TABLE mention_edges (
  notebook_id text NOT NULL,
  claim_object_id text NOT NULL,
  concept_canonical_id text NOT NULL,
  matched_alias text NOT NULL DEFAULT '',
  CONSTRAINT pk_mention_edges PRIMARY KEY (notebook_id, claim_object_id, concept_canonical_id)
);

CREATE TABLE merge_review_jobs (
  notebook_id text NOT NULL,
  status text NOT NULL DEFAULT 'idle',
  total bigint NOT NULL DEFAULT 0,
  done bigint NOT NULL DEFAULT 0,
  started_at timestamp with time zone,
  updated_at timestamp with time zone,
  error text NOT NULL DEFAULT '',
  CONSTRAINT pk_merge_review_jobs PRIMARY KEY (notebook_id)
);

CREATE TABLE model_service_status (
  user_id text NOT NULL,
  service text NOT NULL,
  config_fingerprint text NOT NULL,
  status text NOT NULL,
  latency_ms bigint NOT NULL DEFAULT 0,
  code text NOT NULL DEFAULT '',
  trigger text NOT NULL,
  checked_at timestamp with time zone NOT NULL,
  CONSTRAINT pk_model_service_status PRIMARY KEY (user_id, service),
  CONSTRAINT ck_model_service_status_status CHECK (status IN ('ok', 'error')),
  CONSTRAINT ck_model_service_status_trigger CHECK (trigger IN ('manual_test', 'observed_failure'))
);

CREATE TABLE notebook_assets (
  id text NOT NULL,
  notebook_id text NOT NULL,
  filename text NOT NULL,
  mime text NOT NULL,
  size bigint NOT NULL,
  created_by text NOT NULL DEFAULT '',
  created_at timestamp with time zone NOT NULL,
  source_id text,
  CONSTRAINT pk_notebook_assets PRIMARY KEY (id)
);

CREATE TABLE notebook_bases (
  notebook_id text NOT NULL,
  base_notebook_id text NOT NULL,
  created_at timestamp with time zone NOT NULL,
  created_by text,
  CONSTRAINT pk_notebook_bases PRIMARY KEY (notebook_id, base_notebook_id),
  CONSTRAINT ck_notebook_bases_distinct CHECK (notebook_id <> base_notebook_id)
);

CREATE TABLE notebook_members (
  notebook_id text NOT NULL,
  user_id text NOT NULL,
  role text NOT NULL DEFAULT 'reader',
  added_at timestamp with time zone NOT NULL,
  CONSTRAINT pk_notebook_members PRIMARY KEY (notebook_id, user_id)
);

CREATE TABLE notebooks (
  id text NOT NULL,
  name text NOT NULL,
  purpose text NOT NULL DEFAULT '',
  primary_domain text NOT NULL DEFAULT '',
  status text NOT NULL DEFAULT 'draft',
  created_by text,
  created_at timestamp with time zone NOT NULL,
  updated_at timestamp with time zone NOT NULL,
  target_users text NOT NULL DEFAULT '',
  expected_questions jsonb NOT NULL DEFAULT '[]'::jsonb,
  source_types jsonb NOT NULL DEFAULT '[]'::jsonb,
  taxonomy jsonb NOT NULL DEFAULT '[]'::jsonb,
  access_scope text NOT NULL DEFAULT '',
  template text NOT NULL DEFAULT '',
  purpose_auto bigint NOT NULL DEFAULT 0,
  tier text NOT NULL DEFAULT 'personal',
  is_shared bigint NOT NULL DEFAULT 0,
  share_token text,
  CONSTRAINT pk_notebooks PRIMARY KEY (id)
);

CREATE TABLE object_schemas (
  object_type text NOT NULL,
  plural text NOT NULL DEFAULT '',
  fields jsonb NOT NULL DEFAULT '[]'::jsonb,
  primary_field text NOT NULL DEFAULT '',
  description text NOT NULL DEFAULT '',
  label text NOT NULL DEFAULT '',
  list_fields jsonb NOT NULL DEFAULT '[]'::jsonb,
  source text NOT NULL DEFAULT 'builtin',
  status text NOT NULL DEFAULT 'active',
  rationale text NOT NULL DEFAULT '',
  notebook_id text NOT NULL DEFAULT '',
  created_at timestamp with time zone NOT NULL,
  updated_at timestamp with time zone NOT NULL,
  CONSTRAINT pk_object_schemas PRIMARY KEY (object_type)
);

CREATE TABLE promotion_candidates (
  id text NOT NULL,
  notebook_id text NOT NULL,
  object_id text NOT NULL,
  object_type text NOT NULL,
  status text NOT NULL DEFAULT 'proposed',
  reason text NOT NULL DEFAULT '',
  reviewed_by text NOT NULL DEFAULT '',
  base_match_id text NOT NULL DEFAULT '',
  created_at timestamp with time zone NOT NULL,
  updated_at timestamp with time zone NOT NULL,
  target_base_id text NOT NULL DEFAULT '',
  CONSTRAINT pk_promotion_candidates PRIMARY KEY (id)
);

CREATE TABLE relation_embeddings (
  relation_id text NOT NULL,
  notebook_id text NOT NULL,
  vector bytea NOT NULL,
  created_at timestamp with time zone NOT NULL,
  CONSTRAINT pk_relation_embeddings PRIMARY KEY (relation_id)
);

CREATE TABLE reports (
  id text NOT NULL,
  notebook_id text NOT NULL,
  question text NOT NULL,
  outline_json jsonb NOT NULL DEFAULT '[]'::jsonb,
  sections_json jsonb NOT NULL DEFAULT '[]'::jsonb,
  gaps_json jsonb NOT NULL DEFAULT '[]'::jsonb,
  references_json jsonb NOT NULL DEFAULT '[]'::jsonb,
  depth bigint NOT NULL DEFAULT 2,
  section_status_json jsonb NOT NULL DEFAULT '[]'::jsonb,
  content_md text NOT NULL DEFAULT '',
  status text NOT NULL DEFAULT 'pending',
  progress text NOT NULL DEFAULT '',
  error text NOT NULL DEFAULT '',
  created_by text NOT NULL DEFAULT '',
  created_at timestamp with time zone NOT NULL,
  updated_at timestamp with time zone NOT NULL,
  CONSTRAINT pk_reports PRIMARY KEY (id)
);

CREATE TABLE source_authors (
  id text NOT NULL,
  source_id text NOT NULL,
  notebook_id text NOT NULL,
  position bigint NOT NULL,
  name text NOT NULL,
  affiliation text NOT NULL DEFAULT '',
  created_at timestamp with time zone NOT NULL,
  CONSTRAINT pk_source_authors PRIMARY KEY (id)
);

CREATE TABLE source_elements (
  id text NOT NULL,
  source_id text NOT NULL,
  element_type text NOT NULL,
  location_label text NOT NULL,
  text text NOT NULL,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamp with time zone NOT NULL,
  ordinal bigint GENERATED BY DEFAULT AS IDENTITY,
  CONSTRAINT pk_source_elements PRIMARY KEY (id),
  CONSTRAINT uq_source_elements_ordinal UNIQUE (ordinal)
);

CREATE TABLE source_paper_meta (
  source_id text NOT NULL,
  notebook_id text NOT NULL,
  is_paper bigint NOT NULL DEFAULT 0,
  paper_title text,
  venue text,
  pub_year bigint,
  doi text,
  keywords jsonb NOT NULL DEFAULT '[]'::jsonb,
  raw_json jsonb NOT NULL DEFAULT '{}'::jsonb,
  model text NOT NULL DEFAULT '',
  created_at timestamp with time zone NOT NULL,
  updated_at timestamp with time zone NOT NULL,
  CONSTRAINT pk_source_paper_meta PRIMARY KEY (source_id)
);

CREATE TABLE sources (
  id text NOT NULL,
  notebook_id text NOT NULL,
  title text NOT NULL,
  source_type text NOT NULL,
  status text NOT NULL DEFAULT 'uploaded',
  parse_status text NOT NULL DEFAULT 'uploaded',
  file_name text NOT NULL DEFAULT '',
  file_path text NOT NULL DEFAULT '',
  source_url text NOT NULL DEFAULT '',
  file_size bigint NOT NULL DEFAULT 0,
  file_hash text NOT NULL DEFAULT '',
  summary text NOT NULL DEFAULT '',
  error_message text NOT NULL DEFAULT '',
  created_at timestamp with time zone NOT NULL,
  updated_at timestamp with time zone NOT NULL,
  doc_type text NOT NULL DEFAULT '',
  memory_id text,
  CONSTRAINT pk_sources PRIMARY KEY (id)
);

CREATE TABLE unified_kg_state (
  notebook_id text NOT NULL,
  dirty bigint NOT NULL DEFAULT 0,
  kg_mutation_seq bigint NOT NULL DEFAULT 0,
  cluster_mutation_seq bigint NOT NULL DEFAULT 0,
  cluster_input_version text NOT NULL DEFAULT '',
  last_rebuild_at timestamp with time zone,
  object_count bigint NOT NULL DEFAULT 0,
  relation_count bigint NOT NULL DEFAULT 0,
  cluster_count bigint NOT NULL DEFAULT 0,
  updated_at timestamp with time zone NOT NULL,
  community_seq bigint NOT NULL DEFAULT -1,
  canonical_rel_seq bigint NOT NULL DEFAULT -1,
  mention_seq bigint NOT NULL DEFAULT -1,
  source_index_backfilled bigint NOT NULL DEFAULT 0,
  CONSTRAINT pk_unified_kg_state PRIMARY KEY (notebook_id)
);

CREATE TABLE user_profiles (
  id text NOT NULL,
  user_id text NOT NULL,
  memory_mode text NOT NULL DEFAULT 'manual',
  domain_focus jsonb NOT NULL DEFAULT '[]'::jsonb,
  created_at timestamp with time zone NOT NULL,
  updated_at timestamp with time zone NOT NULL,
  model_settings jsonb NOT NULL DEFAULT '{}'::jsonb,
  CONSTRAINT pk_user_profiles PRIMARY KEY (id)
);

CREATE TABLE users (
  id text NOT NULL,
  email text NOT NULL,
  display_name text NOT NULL,
  role text NOT NULL,
  status text NOT NULL DEFAULT 'active',
  created_at timestamp with time zone NOT NULL,
  updated_at timestamp with time zone NOT NULL,
  username text NOT NULL DEFAULT '',
  password_hash text NOT NULL DEFAULT '',
  password_salt text NOT NULL DEFAULT '',
  password_iterations bigint NOT NULL DEFAULT 0,
  CONSTRAINT pk_users PRIMARY KEY (id),
  CONSTRAINT uq_users_email UNIQUE (email)
);

ALTER TABLE agent_access_tokens
  ADD CONSTRAINT fk_agent_access_tokens_agent_profile_id__agent_profiles
  FOREIGN KEY (agent_profile_id) REFERENCES agent_profiles (id)
  ON UPDATE NO ACTION ON DELETE CASCADE;

ALTER TABLE agent_access_tokens
  ADD CONSTRAINT fk_agent_access_tokens_default_notebook_id__notebooks
  FOREIGN KEY (default_notebook_id) REFERENCES notebooks (id)
  ON UPDATE NO ACTION ON DELETE CASCADE;

ALTER TABLE agent_profiles
  ADD CONSTRAINT fk_agent_profiles_owner_id__users
  FOREIGN KEY (owner_id) REFERENCES users (id)
  ON UPDATE NO ACTION ON DELETE CASCADE;

ALTER TABLE agent_token_notebooks
  ADD CONSTRAINT fk_agent_token_notebooks_notebook_id__notebooks
  FOREIGN KEY (notebook_id) REFERENCES notebooks (id)
  ON UPDATE NO ACTION ON DELETE CASCADE;

ALTER TABLE agent_token_notebooks
  ADD CONSTRAINT fk_agent_token_notebooks_token_id__agent_access_tokens
  FOREIGN KEY (token_id) REFERENCES agent_access_tokens (id)
  ON UPDATE NO ACTION ON DELETE CASCADE;

ALTER TABLE answers
  ADD CONSTRAINT fk_answers_notebook_id__notebooks
  FOREIGN KEY (notebook_id) REFERENCES notebooks (id)
  ON UPDATE NO ACTION ON DELETE CASCADE;

ALTER TABLE ask_jobs
  ADD CONSTRAINT fk_ask_jobs_notebook_id__notebooks
  FOREIGN KEY (notebook_id) REFERENCES notebooks (id)
  ON UPDATE NO ACTION ON DELETE CASCADE;

ALTER TABLE ask_trace_steps
  ADD CONSTRAINT fk_ask_trace_steps_job_id__ask_jobs
  FOREIGN KEY (job_id) REFERENCES ask_jobs (id)
  ON UPDATE NO ACTION ON DELETE CASCADE;

ALTER TABLE auth_sessions
  ADD CONSTRAINT fk_auth_sessions_user_id__users
  FOREIGN KEY (user_id) REFERENCES users (id)
  ON UPDATE NO ACTION ON DELETE CASCADE;

ALTER TABLE canonical_relations
  ADD CONSTRAINT fk_canonical_relations_notebook_id__notebooks
  FOREIGN KEY (notebook_id) REFERENCES notebooks (id)
  ON UPDATE NO ACTION ON DELETE CASCADE;

ALTER TABLE chunk_embeddings
  ADD CONSTRAINT fk_chunk_embeddings_chunk_id__chunks
  FOREIGN KEY (chunk_id) REFERENCES chunks (id)
  ON UPDATE NO ACTION ON DELETE CASCADE;

ALTER TABLE chunks
  ADD CONSTRAINT fk_chunks_notebook_id__notebooks
  FOREIGN KEY (notebook_id) REFERENCES notebooks (id)
  ON UPDATE NO ACTION ON DELETE CASCADE;

ALTER TABLE chunks
  ADD CONSTRAINT fk_chunks_source_id__sources
  FOREIGN KEY (source_id) REFERENCES sources (id)
  ON UPDATE NO ACTION ON DELETE CASCADE;

ALTER TABLE communities
  ADD CONSTRAINT fk_communities_notebook_id__notebooks
  FOREIGN KEY (notebook_id) REFERENCES notebooks (id)
  ON UPDATE NO ACTION ON DELETE CASCADE;

ALTER TABLE concept_clusters
  ADD CONSTRAINT fk_concept_clusters_notebook_id__notebooks
  FOREIGN KEY (notebook_id) REFERENCES notebooks (id)
  ON UPDATE NO ACTION ON DELETE CASCADE;

ALTER TABLE concept_comentions
  ADD CONSTRAINT fk_concept_comentions_notebook_id__notebooks
  FOREIGN KEY (notebook_id) REFERENCES notebooks (id)
  ON UPDATE NO ACTION ON DELETE CASCADE;

ALTER TABLE concept_merge_candidates
  ADD CONSTRAINT fk_concept_merge_candidates_notebook_id__notebooks
  FOREIGN KEY (notebook_id) REFERENCES notebooks (id)
  ON UPDATE NO ACTION ON DELETE CASCADE;

ALTER TABLE element_embeddings
  ADD CONSTRAINT fk_element_embeddings_element_id__source_elements
  FOREIGN KEY (element_id) REFERENCES source_elements (id)
  ON UPDATE NO ACTION ON DELETE CASCADE;

ALTER TABLE extraction_runs
  ADD CONSTRAINT fk_extraction_runs_notebook_id__notebooks
  FOREIGN KEY (notebook_id) REFERENCES notebooks (id)
  ON UPDATE NO ACTION ON DELETE CASCADE;

ALTER TABLE extraction_runs
  ADD CONSTRAINT fk_extraction_runs_source_id__sources
  FOREIGN KEY (source_id) REFERENCES sources (id)
  ON UPDATE NO ACTION ON DELETE CASCADE;

ALTER TABLE feedback
  ADD CONSTRAINT fk_feedback_answer_id__answers
  FOREIGN KEY (answer_id) REFERENCES answers (id)
  ON UPDATE NO ACTION ON DELETE CASCADE;

ALTER TABLE kg_build_jobs
  ADD CONSTRAINT fk_kg_build_jobs_notebook_id__notebooks
  FOREIGN KEY (notebook_id) REFERENCES notebooks (id)
  ON UPDATE NO ACTION ON DELETE CASCADE;

ALTER TABLE kg_conflict_candidates
  ADD CONSTRAINT fk_kg_conflict_candidates_notebook_id__notebooks
  FOREIGN KEY (notebook_id) REFERENCES notebooks (id)
  ON UPDATE NO ACTION ON DELETE CASCADE;

ALTER TABLE kg_rebuild_checkpoint
  ADD CONSTRAINT fk_kg_rebuild_checkpoint_notebook_id__notebooks
  FOREIGN KEY (notebook_id) REFERENCES notebooks (id)
  ON UPDATE NO ACTION ON DELETE CASCADE;

ALTER TABLE knowhow_cell_code
  ADD CONSTRAINT fk_knowhow_cell_code_column_id__knowhow_columns
  FOREIGN KEY (column_id) REFERENCES knowhow_columns (id)
  ON UPDATE NO ACTION ON DELETE CASCADE;

ALTER TABLE knowhow_cell_code
  ADD CONSTRAINT fk_knowhow_cell_code_row_id__knowhow_rows
  FOREIGN KEY (row_id) REFERENCES knowhow_rows (id)
  ON UPDATE NO ACTION ON DELETE CASCADE;

ALTER TABLE knowhow_cells
  ADD CONSTRAINT fk_knowhow_cells_column_id__knowhow_columns
  FOREIGN KEY (column_id) REFERENCES knowhow_columns (id)
  ON UPDATE NO ACTION ON DELETE CASCADE;

ALTER TABLE knowhow_cells
  ADD CONSTRAINT fk_knowhow_cells_row_id__knowhow_rows
  FOREIGN KEY (row_id) REFERENCES knowhow_rows (id)
  ON UPDATE NO ACTION ON DELETE CASCADE;

ALTER TABLE knowhow_columns
  ADD CONSTRAINT fk_knowhow_columns_table_id__knowhow_tables
  FOREIGN KEY (table_id) REFERENCES knowhow_tables (id)
  ON UPDATE NO ACTION ON DELETE CASCADE;

ALTER TABLE knowhow_rows
  ADD CONSTRAINT fk_knowhow_rows_table_id__knowhow_tables
  FOREIGN KEY (table_id) REFERENCES knowhow_tables (id)
  ON UPDATE NO ACTION ON DELETE CASCADE;

ALTER TABLE knowhow_tables
  ADD CONSTRAINT fk_knowhow_tables_notebook_id__notebooks
  FOREIGN KEY (notebook_id) REFERENCES notebooks (id)
  ON UPDATE NO ACTION ON DELETE CASCADE;

ALTER TABLE knowledge_objects
  ADD CONSTRAINT fk_knowledge_objects_notebook_id__notebooks
  FOREIGN KEY (notebook_id) REFERENCES notebooks (id)
  ON UPDATE NO ACTION ON DELETE CASCADE;

ALTER TABLE knowledge_relations
  ADD CONSTRAINT fk_knowledge_relations_notebook_id__notebooks
  FOREIGN KEY (notebook_id) REFERENCES notebooks (id)
  ON UPDATE NO ACTION ON DELETE CASCADE;

ALTER TABLE knowledge_relations
  ADD CONSTRAINT fk_knowledge_relations_source_id__sources
  FOREIGN KEY (source_id) REFERENCES sources (id)
  ON UPDATE NO ACTION ON DELETE CASCADE;

ALTER TABLE memory_embeddings
  ADD CONSTRAINT fk_memory_embeddings_memory_id__memory_items
  FOREIGN KEY (memory_id) REFERENCES memory_items (id)
  ON UPDATE NO ACTION ON DELETE CASCADE;

ALTER TABLE memory_items
  ADD CONSTRAINT fk_memory_items_agent_profile_id__agent_profiles
  FOREIGN KEY (agent_profile_id) REFERENCES agent_profiles (id)
  ON UPDATE NO ACTION ON DELETE SET NULL;

ALTER TABLE memory_items
  ADD CONSTRAINT fk_memory_items_confirmed_by__users
  FOREIGN KEY (confirmed_by) REFERENCES users (id)
  ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE memory_items
  ADD CONSTRAINT fk_memory_items_created_by__users
  FOREIGN KEY (created_by) REFERENCES users (id)
  ON UPDATE NO ACTION ON DELETE CASCADE;

ALTER TABLE memory_items
  ADD CONSTRAINT fk_memory_items_notebook_id__notebooks
  FOREIGN KEY (notebook_id) REFERENCES notebooks (id)
  ON UPDATE NO ACTION ON DELETE CASCADE;

ALTER TABLE memory_provenance
  ADD CONSTRAINT fk_memory_provenance_memory_id__memory_items
  FOREIGN KEY (memory_id) REFERENCES memory_items (id)
  ON UPDATE NO ACTION ON DELETE CASCADE;

ALTER TABLE memory_revisions
  ADD CONSTRAINT fk_memory_revisions_changed_by__users
  FOREIGN KEY (changed_by) REFERENCES users (id)
  ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE memory_revisions
  ADD CONSTRAINT fk_memory_revisions_memory_id__memory_items
  FOREIGN KEY (memory_id) REFERENCES memory_items (id)
  ON UPDATE NO ACTION ON DELETE CASCADE;

ALTER TABLE mention_edges
  ADD CONSTRAINT fk_mention_edges_notebook_id__notebooks
  FOREIGN KEY (notebook_id) REFERENCES notebooks (id)
  ON UPDATE NO ACTION ON DELETE CASCADE;

ALTER TABLE merge_review_jobs
  ADD CONSTRAINT fk_merge_review_jobs_notebook_id__notebooks
  FOREIGN KEY (notebook_id) REFERENCES notebooks (id)
  ON UPDATE NO ACTION ON DELETE CASCADE;

ALTER TABLE model_service_status
  ADD CONSTRAINT fk_model_service_status_user_id__users
  FOREIGN KEY (user_id) REFERENCES users (id)
  ON UPDATE NO ACTION ON DELETE CASCADE;

ALTER TABLE notebook_assets
  ADD CONSTRAINT fk_notebook_assets_notebook_id__notebooks
  FOREIGN KEY (notebook_id) REFERENCES notebooks (id)
  ON UPDATE NO ACTION ON DELETE CASCADE;

ALTER TABLE notebook_bases
  ADD CONSTRAINT fk_notebook_bases_base_notebook_id__notebooks
  FOREIGN KEY (base_notebook_id) REFERENCES notebooks (id)
  ON UPDATE NO ACTION ON DELETE CASCADE;

ALTER TABLE notebook_bases
  ADD CONSTRAINT fk_notebook_bases_created_by__users
  FOREIGN KEY (created_by) REFERENCES users (id)
  ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE notebook_bases
  ADD CONSTRAINT fk_notebook_bases_notebook_id__notebooks
  FOREIGN KEY (notebook_id) REFERENCES notebooks (id)
  ON UPDATE NO ACTION ON DELETE CASCADE;

ALTER TABLE notebook_members
  ADD CONSTRAINT fk_notebook_members_notebook_id__notebooks
  FOREIGN KEY (notebook_id) REFERENCES notebooks (id)
  ON UPDATE NO ACTION ON DELETE CASCADE;

ALTER TABLE notebook_members
  ADD CONSTRAINT fk_notebook_members_user_id__users
  FOREIGN KEY (user_id) REFERENCES users (id)
  ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE notebooks
  ADD CONSTRAINT fk_notebooks_created_by__users
  FOREIGN KEY (created_by) REFERENCES users (id)
  ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE promotion_candidates
  ADD CONSTRAINT fk_promotion_candidates_notebook_id__notebooks
  FOREIGN KEY (notebook_id) REFERENCES notebooks (id)
  ON UPDATE NO ACTION ON DELETE CASCADE;

ALTER TABLE relation_embeddings
  ADD CONSTRAINT fk_relation_embeddings_relation_id__knowledge_relations
  FOREIGN KEY (relation_id) REFERENCES knowledge_relations (id)
  ON UPDATE NO ACTION ON DELETE CASCADE;

ALTER TABLE reports
  ADD CONSTRAINT fk_reports_notebook_id__notebooks
  FOREIGN KEY (notebook_id) REFERENCES notebooks (id)
  ON UPDATE NO ACTION ON DELETE CASCADE;

ALTER TABLE source_authors
  ADD CONSTRAINT fk_source_authors_notebook_id__notebooks
  FOREIGN KEY (notebook_id) REFERENCES notebooks (id)
  ON UPDATE NO ACTION ON DELETE CASCADE;

ALTER TABLE source_authors
  ADD CONSTRAINT fk_source_authors_source_id__sources
  FOREIGN KEY (source_id) REFERENCES sources (id)
  ON UPDATE NO ACTION ON DELETE CASCADE;

ALTER TABLE source_elements
  ADD CONSTRAINT fk_source_elements_source_id__sources
  FOREIGN KEY (source_id) REFERENCES sources (id)
  ON UPDATE NO ACTION ON DELETE CASCADE;

ALTER TABLE source_paper_meta
  ADD CONSTRAINT fk_source_paper_meta_notebook_id__notebooks
  FOREIGN KEY (notebook_id) REFERENCES notebooks (id)
  ON UPDATE NO ACTION ON DELETE CASCADE;

ALTER TABLE source_paper_meta
  ADD CONSTRAINT fk_source_paper_meta_source_id__sources
  FOREIGN KEY (source_id) REFERENCES sources (id)
  ON UPDATE NO ACTION ON DELETE CASCADE;

ALTER TABLE sources
  ADD CONSTRAINT fk_sources_notebook_id__notebooks
  FOREIGN KEY (notebook_id) REFERENCES notebooks (id)
  ON UPDATE NO ACTION ON DELETE CASCADE;

ALTER TABLE unified_kg_state
  ADD CONSTRAINT fk_unified_kg_state_notebook_id__notebooks
  FOREIGN KEY (notebook_id) REFERENCES notebooks (id)
  ON UPDATE NO ACTION ON DELETE CASCADE;

ALTER TABLE user_profiles
  ADD CONSTRAINT fk_user_profiles_user_id__users
  FOREIGN KEY (user_id) REFERENCES users (id)
  ON UPDATE NO ACTION ON DELETE CASCADE;
