-- Core identity, notebook, source, chunk, Ask, report, and job indexes.
CREATE INDEX idx_agent_profiles_owner_status ON agent_profiles(owner_id, status, updated_at DESC);
CREATE INDEX idx_agent_token_notebooks_notebook ON agent_token_notebooks(notebook_id, token_id);
CREATE INDEX idx_agent_tokens_profile ON agent_access_tokens(agent_profile_id, revoked_at, expires_at);
CREATE INDEX idx_answers_conversation ON answers(conversation_id);
CREATE INDEX idx_answers_nb ON answers(notebook_id);
CREATE INDEX idx_ask_jobs_conv ON ask_jobs(conversation_id);
CREATE INDEX idx_ask_jobs_nb_status ON ask_jobs(notebook_id, status);
CREATE INDEX idx_auth_sessions_user ON auth_sessions(user_id);
CREATE INDEX idx_chunks_nb ON chunks(notebook_id);
CREATE INDEX idx_chunks_nb_created ON chunks(notebook_id, created_at);
CREATE INDEX idx_chunks_source ON chunks(source_id);
CREATE INDEX idx_conversations_created_by ON conversations(created_by);
CREATE INDEX idx_element_embeddings_nb ON element_embeddings(notebook_id);
CREATE INDEX idx_element_embeddings_source ON element_embeddings(source_id);
CREATE INDEX idx_extraction_runs_source_created ON extraction_runs(source_id, created_at);
CREATE INDEX idx_feedback_answer ON feedback(answer_id);
CREATE INDEX idx_feedback_nb_rating ON feedback(notebook_id, rating);
CREATE INDEX idx_kg_build_jobs_nb_created ON kg_build_jobs(notebook_id, created_at DESC, id DESC);
CREATE INDEX idx_notebook_assets_nb ON notebook_assets(notebook_id);
CREATE INDEX idx_notebook_assets_source ON notebook_assets(source_id);
CREATE INDEX idx_notebook_bases_base ON notebook_bases(base_notebook_id);
CREATE INDEX idx_notebook_members_user ON notebook_members(user_id);
CREATE INDEX idx_notebooks_created_by ON notebooks(created_by);
CREATE INDEX idx_reports_nb_created ON reports(notebook_id, created_at DESC);
CREATE INDEX idx_source_authors_nb ON source_authors(notebook_id);
CREATE INDEX idx_source_authors_source ON source_authors(source_id);
CREATE INDEX idx_source_elements_source ON source_elements(source_id);
CREATE INDEX idx_source_elements_source_created ON source_elements(source_id, created_at, id);
CREATE INDEX idx_source_paper_meta_nb ON source_paper_meta(notebook_id);
CREATE INDEX idx_sources_nb_parse_status ON sources(notebook_id, parse_status);
CREATE INDEX idx_sources_nb_parse_status_type ON sources(notebook_id, parse_status, source_type);
CREATE INDEX idx_sources_notebook_created ON sources(notebook_id, created_at);
CREATE INDEX idx_sources_notebook_status ON sources(notebook_id, status);
