-- SQLite v84 parity (_migration_84). Source-side change capture for
-- cross-environment notebook sync: the gate, the change log, a row identity
-- for the two synced tables that never had one, and one AFTER-row trigger per
-- synced business table.
--
-- Everything below the "generated" marker is rendered by
-- backend/app/migration/sync/capture.py and pinned byte-for-byte by
-- backend/tests/test_sync_capture.py. Do not hand-edit it: change the
-- generator and re-render, so the SQLite triggers, this file, the snapshot
-- verifier's expectations and the catalog drift guard cannot disagree.
--
-- sync_capture_control is a one-row gate, NOT seeded here on purpose: an
-- absent row reads exactly like a disabled one, so an upgraded deployment
-- captures nothing until an operator enables it. Adapter-internal, like the
-- 0063 control tables (see backend/app/migration/shadow/manifest.py's
-- LOCAL_EPHEMERAL registration): the log describes writes made in THIS
-- environment and must never travel through the shadow-migration copy path,
-- a notebook deep-copy, or a sync package.
CREATE TABLE sync_capture_control (
  singleton bigint NOT NULL,
  enabled boolean NOT NULL DEFAULT false,
  enabled_at timestamp with time zone,
  disabled_at timestamp with time zone,
  CONSTRAINT pk_sync_capture_control PRIMARY KEY (singleton),
  CONSTRAINT ck_sync_capture_control_singleton CHECK (singleton = 1)
);

-- sync_change_log is append-only and holds row IDENTITIES only -- key_json is
-- the changed row's key columns, never its content. parent_key/notebook_id
-- carry the row's notebook attribution as the sync manifest's TableScope
-- defines it (notebook-scoped rows fill notebook_id, parent-scoped rows fill
-- parent_key and leave the notebook to be resolved at export time, global
-- rows fill neither). txid is the writing transaction's id, which the
-- incremental exporter needs to tell an already-committed change from one
-- still in flight at snapshot time; SQLite has no equivalent and leaves it
-- NULL.
CREATE TABLE sync_change_log (
  seq bigint GENERATED BY DEFAULT AS IDENTITY,
  table_name text COLLATE "C" NOT NULL,
  key_json jsonb NOT NULL,
  operation text COLLATE "C" NOT NULL,
  parent_key text COLLATE "C",
  notebook_id text COLLATE "C",
  txid bigint,
  changed_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT pk_sync_change_log PRIMARY KEY (seq)
);

-- The exporter reads the log one table at a time, in seq order, so the
-- (table_name, seq) prefix is the whole access path.
CREATE INDEX idx_sync_change_log_table_seq
    ON sync_change_log (table_name, seq);

-- knowledge_object_sources and community_members are the only two synced
-- tables 0001_initial.sql left without a primary key. Change capture needs a
-- row identity, and so do the exporter's and importer's row matching, so both
-- get one here: duplicates first collapse to the physically first row (these
-- are derived KG membership rows -- a duplicate carries nothing the survivor
-- does not), then the key becomes a real primary key. SQLite cannot add a
-- primary key to an existing table and uses a UNIQUE INDEX with the same
-- columns instead; app/migration/sync/manifest.py registers the key and
-- tests/test_sync_capture.py pins both backends to it.
DELETE FROM knowledge_object_sources a
  USING knowledge_object_sources b
  WHERE a.ctid > b.ctid
    AND a.object_id = b.object_id
    AND a.source_id = b.source_id;
ALTER TABLE knowledge_object_sources
  ADD CONSTRAINT pk_knowledge_object_sources PRIMARY KEY (object_id, source_id);

-- (community_id, canonical_id), not the shadow manifest's three-column
-- replication key: community_id is recast per generation and is unique across
-- the whole database, so it already implies notebook_id/level/generation,
-- while (notebook_id, level, canonical_id) stopped being unique when v71 added
-- generation. This is also the row identity reap_derived_generations_page
-- deletes by.
DELETE FROM community_members a
  USING community_members b
  WHERE a.ctid > b.ctid
    AND a.community_id = b.community_id
    AND a.canonical_id = b.canonical_id;
ALTER TABLE community_members
  ADD CONSTRAINT pk_community_members PRIMARY KEY (community_id, canonical_id);

-- --- generated by backend/app/migration/sync/capture.py ---------------------
CREATE FUNCTION sync_capture_row() RETURNS trigger
LANGUAGE plpgsql AS $sync_capture_row$
DECLARE
  key_columns text[] := string_to_array(TG_ARGV[0], ',');
  scope_kind text := TG_ARGV[1];
  scope_column text := TG_ARGV[2];
  old_row jsonb;
  new_row jsonb;
  old_key jsonb;
  new_key jsonb;
  xact bigint;
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM sync_capture_control WHERE singleton = 1 AND enabled
  ) THEN
    RETURN NULL;
  END IF;
  xact := pg_current_xact_id()::text::bigint;
  IF TG_OP <> 'INSERT' THEN
    old_row := to_jsonb(OLD);
    SELECT jsonb_object_agg(key_column, old_row -> key_column) INTO old_key
      FROM unnest(key_columns) AS key_column;
  END IF;
  IF TG_OP <> 'DELETE' THEN
    new_row := to_jsonb(NEW);
    SELECT jsonb_object_agg(key_column, new_row -> key_column) INTO new_key
      FROM unnest(key_columns) AS key_column;
  END IF;
  IF TG_OP = 'DELETE'
     OR (TG_OP = 'UPDATE' AND old_key IS DISTINCT FROM new_key) THEN
    INSERT INTO sync_change_log (table_name, key_json, operation, parent_key, notebook_id, txid, changed_at)
    VALUES (TG_TABLE_NAME, old_key, 'delete',
            CASE WHEN scope_kind = 'parent' THEN old_row ->> scope_column END,
            CASE WHEN scope_kind = 'notebook' THEN old_row ->> scope_column END,
            xact, now());
  END IF;
  IF TG_OP <> 'DELETE' THEN
    INSERT INTO sync_change_log (table_name, key_json, operation, parent_key, notebook_id, txid, changed_at)
    VALUES (TG_TABLE_NAME, new_key, 'upsert',
            CASE WHEN scope_kind = 'parent' THEN new_row ->> scope_column END,
            CASE WHEN scope_kind = 'notebook' THEN new_row ->> scope_column END,
            xact, now());
    IF TG_TABLE_NAME = 'unified_kg_state' AND (
         (TG_OP = 'INSERT' AND (new_row ->> 'kg_reset_epoch')::bigint > 0)
         OR (TG_OP = 'UPDATE'
             AND (old_row -> 'kg_reset_epoch')
                 IS DISTINCT FROM (new_row -> 'kg_reset_epoch'))
       ) THEN
      INSERT INTO sync_change_log (table_name, key_json, operation, parent_key, notebook_id, txid, changed_at)
      VALUES (TG_TABLE_NAME, new_key, 'kg_epoch',
              CASE WHEN scope_kind = 'parent' THEN new_row ->> scope_column END,
              CASE WHEN scope_kind = 'notebook' THEN new_row ->> scope_column END,
              xact, now());
    END IF;
  END IF;
  RETURN NULL;
END;
$sync_capture_row$;

CREATE TRIGGER sync_capture_community_members AFTER INSERT OR UPDATE OR DELETE ON community_members FOR EACH ROW EXECUTE FUNCTION sync_capture_row('community_id,canonical_id', 'notebook', 'notebook_id');
CREATE TRIGGER sync_capture_knowledge_embeddings AFTER INSERT OR UPDATE OR DELETE ON knowledge_embeddings FOR EACH ROW EXECUTE FUNCTION sync_capture_row('object_id', 'notebook', 'notebook_id');
CREATE TRIGGER sync_capture_knowledge_object_sources AFTER INSERT OR UPDATE OR DELETE ON knowledge_object_sources FOR EACH ROW EXECUTE FUNCTION sync_capture_row('object_id,source_id', 'notebook', 'notebook_id');
CREATE TRIGGER sync_capture_object_schemas AFTER INSERT OR UPDATE OR DELETE ON object_schemas FOR EACH ROW EXECUTE FUNCTION sync_capture_row('object_type', 'global', '');
CREATE TRIGGER sync_capture_notebooks AFTER INSERT OR UPDATE OR DELETE ON notebooks FOR EACH ROW EXECUTE FUNCTION sync_capture_row('id', 'notebook', 'id');
CREATE TRIGGER sync_capture_canonical_relations AFTER INSERT OR UPDATE OR DELETE ON canonical_relations FOR EACH ROW EXECUTE FUNCTION sync_capture_row('notebook_id,canonical_src,edge_type,canonical_tgt', 'notebook', 'notebook_id');
CREATE TRIGGER sync_capture_communities AFTER INSERT OR UPDATE OR DELETE ON communities FOR EACH ROW EXECUTE FUNCTION sync_capture_row('id', 'notebook', 'notebook_id');
CREATE TRIGGER sync_capture_concept_clusters AFTER INSERT OR UPDATE OR DELETE ON concept_clusters FOR EACH ROW EXECUTE FUNCTION sync_capture_row('id', 'notebook', 'notebook_id');
CREATE TRIGGER sync_capture_concept_comentions AFTER INSERT OR UPDATE OR DELETE ON concept_comentions FOR EACH ROW EXECUTE FUNCTION sync_capture_row('notebook_id,canonical_a,canonical_b', 'notebook', 'notebook_id');
CREATE TRIGGER sync_capture_knowhow_tables AFTER INSERT OR UPDATE OR DELETE ON knowhow_tables FOR EACH ROW EXECUTE FUNCTION sync_capture_row('id', 'notebook', 'notebook_id');
CREATE TRIGGER sync_capture_knowhow_changes AFTER INSERT OR UPDATE OR DELETE ON knowhow_changes FOR EACH ROW EXECUTE FUNCTION sync_capture_row('id', 'parent', 'table_id');
CREATE TRIGGER sync_capture_knowhow_columns AFTER INSERT OR UPDATE OR DELETE ON knowhow_columns FOR EACH ROW EXECUTE FUNCTION sync_capture_row('id', 'parent', 'table_id');
CREATE TRIGGER sync_capture_knowhow_milestones AFTER INSERT OR UPDATE OR DELETE ON knowhow_milestones FOR EACH ROW EXECUTE FUNCTION sync_capture_row('id', 'parent', 'table_id');
CREATE TRIGGER sync_capture_knowhow_rows AFTER INSERT OR UPDATE OR DELETE ON knowhow_rows FOR EACH ROW EXECUTE FUNCTION sync_capture_row('id', 'parent', 'table_id');
CREATE TRIGGER sync_capture_knowhow_cell_code AFTER INSERT OR UPDATE OR DELETE ON knowhow_cell_code FOR EACH ROW EXECUTE FUNCTION sync_capture_row('id', 'parent', 'row_id');
CREATE TRIGGER sync_capture_knowhow_cells AFTER INSERT OR UPDATE OR DELETE ON knowhow_cells FOR EACH ROW EXECUTE FUNCTION sync_capture_row('id', 'parent', 'row_id');
CREATE TRIGGER sync_capture_knowledge_objects AFTER INSERT OR UPDATE OR DELETE ON knowledge_objects FOR EACH ROW EXECUTE FUNCTION sync_capture_row('id', 'notebook', 'notebook_id');
CREATE TRIGGER sync_capture_memory_items AFTER INSERT OR UPDATE OR DELETE ON memory_items FOR EACH ROW EXECUTE FUNCTION sync_capture_row('id', 'notebook', 'notebook_id');
CREATE TRIGGER sync_capture_memory_embeddings AFTER INSERT OR UPDATE OR DELETE ON memory_embeddings FOR EACH ROW EXECUTE FUNCTION sync_capture_row('memory_id', 'parent', 'memory_id');
CREATE TRIGGER sync_capture_memory_provenance AFTER INSERT OR UPDATE OR DELETE ON memory_provenance FOR EACH ROW EXECUTE FUNCTION sync_capture_row('id', 'parent', 'memory_id');
CREATE TRIGGER sync_capture_memory_revisions AFTER INSERT OR UPDATE OR DELETE ON memory_revisions FOR EACH ROW EXECUTE FUNCTION sync_capture_row('id', 'parent', 'memory_id');
CREATE TRIGGER sync_capture_mention_edges AFTER INSERT OR UPDATE OR DELETE ON mention_edges FOR EACH ROW EXECUTE FUNCTION sync_capture_row('notebook_id,claim_object_id,concept_canonical_id', 'notebook', 'notebook_id');
CREATE TRIGGER sync_capture_notebook_assets AFTER INSERT OR UPDATE OR DELETE ON notebook_assets FOR EACH ROW EXECUTE FUNCTION sync_capture_row('id', 'notebook', 'notebook_id');
CREATE TRIGGER sync_capture_notebook_bases AFTER INSERT OR UPDATE OR DELETE ON notebook_bases FOR EACH ROW EXECUTE FUNCTION sync_capture_row('notebook_id,base_notebook_id', 'notebook', 'notebook_id');
CREATE TRIGGER sync_capture_notebook_members AFTER INSERT OR UPDATE OR DELETE ON notebook_members FOR EACH ROW EXECUTE FUNCTION sync_capture_row('notebook_id,user_id', 'notebook', 'notebook_id');
CREATE TRIGGER sync_capture_sources AFTER INSERT OR UPDATE OR DELETE ON sources FOR EACH ROW EXECUTE FUNCTION sync_capture_row('id', 'notebook', 'notebook_id');
CREATE TRIGGER sync_capture_chunks AFTER INSERT OR UPDATE OR DELETE ON chunks FOR EACH ROW EXECUTE FUNCTION sync_capture_row('id', 'notebook', 'notebook_id');
CREATE TRIGGER sync_capture_chunk_embeddings AFTER INSERT OR UPDATE OR DELETE ON chunk_embeddings FOR EACH ROW EXECUTE FUNCTION sync_capture_row('chunk_id', 'notebook', 'notebook_id');
CREATE TRIGGER sync_capture_knowledge_relations AFTER INSERT OR UPDATE OR DELETE ON knowledge_relations FOR EACH ROW EXECUTE FUNCTION sync_capture_row('id', 'notebook', 'notebook_id');
CREATE TRIGGER sync_capture_relation_embeddings AFTER INSERT OR UPDATE OR DELETE ON relation_embeddings FOR EACH ROW EXECUTE FUNCTION sync_capture_row('relation_id', 'notebook', 'notebook_id');
CREATE TRIGGER sync_capture_source_authors AFTER INSERT OR UPDATE OR DELETE ON source_authors FOR EACH ROW EXECUTE FUNCTION sync_capture_row('id', 'notebook', 'notebook_id');
CREATE TRIGGER sync_capture_source_elements AFTER INSERT OR UPDATE OR DELETE ON source_elements FOR EACH ROW EXECUTE FUNCTION sync_capture_row('id', 'parent', 'source_id');
CREATE TRIGGER sync_capture_element_embeddings AFTER INSERT OR UPDATE OR DELETE ON element_embeddings FOR EACH ROW EXECUTE FUNCTION sync_capture_row('element_id', 'notebook', 'notebook_id');
CREATE TRIGGER sync_capture_source_paper_meta AFTER INSERT OR UPDATE OR DELETE ON source_paper_meta FOR EACH ROW EXECUTE FUNCTION sync_capture_row('source_id', 'notebook', 'notebook_id');
CREATE TRIGGER sync_capture_unified_kg_state AFTER INSERT OR UPDATE OR DELETE ON unified_kg_state FOR EACH ROW EXECUTE FUNCTION sync_capture_row('notebook_id', 'notebook', 'notebook_id');
CREATE TRIGGER sync_capture_kg_analysis_artifacts AFTER INSERT OR UPDATE OR DELETE ON kg_analysis_artifacts FOR EACH ROW EXECUTE FUNCTION sync_capture_row('notebook_id,kind', 'notebook', 'notebook_id');
CREATE TRIGGER sync_capture_kg_community_edges AFTER INSERT OR UPDATE OR DELETE ON kg_community_edges FOR EACH ROW EXECUTE FUNCTION sync_capture_row('notebook_id,src_community_id,dst_community_id', 'notebook', 'notebook_id');
CREATE TRIGGER sync_capture_kg_source_profiles AFTER INSERT OR UPDATE OR DELETE ON kg_source_profiles FOR EACH ROW EXECUTE FUNCTION sync_capture_row('notebook_id,source_id', 'notebook', 'notebook_id');
CREATE TRIGGER sync_capture_knowledge_source_facts AFTER INSERT OR UPDATE OR DELETE ON knowledge_source_facts FOR EACH ROW EXECUTE FUNCTION sync_capture_row('id', 'notebook', 'notebook_id');
CREATE TRIGGER sync_capture_knowledge_source_fact_elements AFTER INSERT OR UPDATE OR DELETE ON knowledge_source_fact_elements FOR EACH ROW EXECUTE FUNCTION sync_capture_row('fact_id,element_id', 'notebook', 'notebook_id');
CREATE TRIGGER sync_capture_chunk_questions AFTER INSERT OR UPDATE OR DELETE ON chunk_questions FOR EACH ROW EXECUTE FUNCTION sync_capture_row('id', 'notebook', 'notebook_id');
CREATE TRIGGER sync_capture_chunk_elements AFTER INSERT OR UPDATE OR DELETE ON chunk_elements FOR EACH ROW EXECUTE FUNCTION sync_capture_row('notebook_id,element_id,chunk_id', 'notebook', 'notebook_id');
CREATE TRIGGER sync_capture_notebook_object_schemas AFTER INSERT OR UPDATE OR DELETE ON notebook_object_schemas FOR EACH ROW EXECUTE FUNCTION sync_capture_row('notebook_id,object_type', 'notebook', 'notebook_id');
CREATE TRIGGER sync_capture_groups AFTER INSERT OR UPDATE OR DELETE ON groups FOR EACH ROW EXECUTE FUNCTION sync_capture_row('id', 'global', '');
CREATE TRIGGER sync_capture_group_members AFTER INSERT OR UPDATE OR DELETE ON group_members FOR EACH ROW EXECUTE FUNCTION sync_capture_row('group_id,user_id', 'global', '');
CREATE TRIGGER sync_capture_notebook_grants AFTER INSERT OR UPDATE OR DELETE ON notebook_grants FOR EACH ROW EXECUTE FUNCTION sync_capture_row('id', 'notebook', 'notebook_id');
