-- SQLite v84 parity (_migration_84). Source-side change capture for
-- cross-environment notebook sync: the gate, the change log, a row identity
-- for the two synced tables that never had one, and one trigger function plus
-- one AFTER-row trigger per synced business table.
--
-- Everything below the "generated" marker is rendered by
-- backend/app/migration/sync/capture.py and pinned byte-for-byte by
-- backend/tests/test_sync_capture.py. Do not hand-edit it: change the
-- generator and re-render, so the SQLite triggers, this file, the snapshot
-- verifier's expectations and the catalog drift guard cannot disagree.
-- app/migration/shadow/postgres_catalog.py parses the function bodies and
-- trigger statements straight out of THIS file and holds the live catalog to
-- them, so a hand-edit here is not a shortcut -- it is a schema change.
--
-- 46 near-identical functions rather than one generic one: a shared function
-- would have to read an arbitrary key column out of an arbitrary row, and the
-- only way to do that without dynamic SQL is to_jsonb(NEW) -- which
-- serializes the WHOLE row, including chunk_embeddings/knowledge_embeddings
-- bytea vectors and chunks.text, on every captured write. Each function below
-- names its own table's key columns and reads nothing else.
--
-- sync_capture_control is a one-row gate, NOT seeded here on purpose: an
-- absent row reads exactly like a disabled one, so an upgraded deployment
-- captures nothing until an operator enables it. Adapter-internal, like the
-- 0063 control tables (see backend/app/migration/shadow/manifest.py's
-- LOCAL_EPHEMERAL registration): the log describes writes made in THIS
-- environment and must never travel through the shadow-migration copy path,
-- a notebook deep-copy, or a sync package.
CREATE TABLE sync_capture_control (
  singleton bigint NOT NULL,
  enabled boolean NOT NULL DEFAULT false,
  enabled_at timestamp with time zone,
  disabled_at timestamp with time zone,
  CONSTRAINT pk_sync_capture_control PRIMARY KEY (singleton),
  CONSTRAINT ck_sync_capture_control_singleton CHECK (singleton = 1)
);

-- sync_change_log is append-only and holds row IDENTITIES only -- key_json is
-- the changed row's key columns, never its content. parent_key/notebook_id
-- carry the row's notebook attribution as the sync manifest's TableScope
-- defines it (notebook-scoped rows fill notebook_id, parent-scoped rows fill
-- parent_key and leave the notebook to be resolved at export time, global
-- rows fill neither). txid is the writing transaction's id, which the
-- incremental exporter needs to tell an already-committed change from one
-- still in flight at snapshot time; SQLite has no equivalent and leaves it
-- NULL.
CREATE TABLE sync_change_log (
  seq bigint GENERATED BY DEFAULT AS IDENTITY,
  table_name text COLLATE "C" NOT NULL,
  key_json jsonb NOT NULL,
  operation text COLLATE "C" NOT NULL,
  parent_key text COLLATE "C",
  notebook_id text COLLATE "C",
  txid bigint,
  changed_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT pk_sync_change_log PRIMARY KEY (seq)
);

-- The exporter reads the log one table at a time, in seq order, so the
-- (table_name, seq) prefix is the whole access path.
CREATE INDEX idx_sync_change_log_table_seq
    ON sync_change_log (table_name, seq);

-- knowledge_object_sources and community_members are the only two synced
-- tables 0001_initial.sql left without a primary key. Change capture needs a
-- row identity, and so do the exporter's and importer's row matching, so both
-- get one here: duplicates first collapse to the physically first row (these
-- are derived KG membership rows -- a duplicate carries nothing the survivor
-- does not), then the key becomes a real primary key. SQLite cannot add a
-- primary key to an existing table and uses a UNIQUE INDEX with the same
-- columns instead; app/migration/sync/manifest.py registers the key and
-- tests/test_sync_capture.py pins both backends to it.
DELETE FROM knowledge_object_sources a
  USING knowledge_object_sources b
  WHERE a.ctid > b.ctid
    AND a.object_id = b.object_id
    AND a.source_id = b.source_id;
ALTER TABLE knowledge_object_sources
  ADD CONSTRAINT pk_knowledge_object_sources PRIMARY KEY (object_id, source_id);

-- (community_id, canonical_id), not the shadow manifest's three-column
-- replication key: community_id is recast per generation and is unique across
-- the whole database, so it already implies notebook_id/level/generation,
-- while (notebook_id, level, canonical_id) stopped being unique when v71 added
-- generation. This is also the row identity reap_derived_generations_page
-- deletes by.
DELETE FROM community_members a
  USING community_members b
  WHERE a.ctid > b.ctid
    AND a.community_id = b.community_id
    AND a.canonical_id = b.canonical_id;
ALTER TABLE community_members
  ADD CONSTRAINT pk_community_members PRIMARY KEY (community_id, canonical_id);

-- --- generated by backend/app/migration/sync/capture.py ---------------------
CREATE FUNCTION sync_capture_community_members() RETURNS trigger
LANGUAGE plpgsql AS $sync_capture_community_members$
DECLARE
  xact bigint;
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM sync_capture_control WHERE singleton = 1 AND enabled
  ) THEN
    RETURN NULL;
  END IF;
  xact := pg_current_xact_id()::text::bigint;
  IF TG_OP = 'DELETE' THEN
    INSERT INTO sync_change_log (table_name, key_json, operation, parent_key, notebook_id, txid, changed_at)
    VALUES ('community_members', jsonb_build_object('community_id', OLD."community_id", 'canonical_id', OLD."canonical_id"), 'delete',
            NULL, OLD."notebook_id", xact, now());
    RETURN NULL;
  END IF;
  IF TG_OP = 'UPDATE' THEN
    IF OLD."community_id" IS DISTINCT FROM NEW."community_id"
       OR OLD."canonical_id" IS DISTINCT FROM NEW."canonical_id" THEN
      INSERT INTO sync_change_log (table_name, key_json, operation, parent_key, notebook_id, txid, changed_at)
      VALUES ('community_members', jsonb_build_object('community_id', OLD."community_id", 'canonical_id', OLD."canonical_id"), 'delete',
              NULL, OLD."notebook_id", xact, now());
    END IF;
  END IF;
  INSERT INTO sync_change_log (table_name, key_json, operation, parent_key, notebook_id, txid, changed_at)
  VALUES ('community_members', jsonb_build_object('community_id', NEW."community_id", 'canonical_id', NEW."canonical_id"), 'upsert',
          NULL, NEW."notebook_id", xact, now());
  RETURN NULL;
END;
$sync_capture_community_members$;
CREATE TRIGGER sync_capture_community_members AFTER INSERT OR DELETE OR UPDATE ON community_members FOR EACH ROW EXECUTE FUNCTION sync_capture_community_members();

CREATE FUNCTION sync_capture_knowledge_embeddings() RETURNS trigger
LANGUAGE plpgsql AS $sync_capture_knowledge_embeddings$
DECLARE
  xact bigint;
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM sync_capture_control WHERE singleton = 1 AND enabled
  ) THEN
    RETURN NULL;
  END IF;
  xact := pg_current_xact_id()::text::bigint;
  IF TG_OP = 'DELETE' THEN
    INSERT INTO sync_change_log (table_name, key_json, operation, parent_key, notebook_id, txid, changed_at)
    VALUES ('knowledge_embeddings', jsonb_build_object('object_id', OLD."object_id"), 'delete',
            NULL, OLD."notebook_id", xact, now());
    RETURN NULL;
  END IF;
  IF TG_OP = 'UPDATE' THEN
    IF OLD."object_id" IS DISTINCT FROM NEW."object_id" THEN
      INSERT INTO sync_change_log (table_name, key_json, operation, parent_key, notebook_id, txid, changed_at)
      VALUES ('knowledge_embeddings', jsonb_build_object('object_id', OLD."object_id"), 'delete',
              NULL, OLD."notebook_id", xact, now());
    END IF;
  END IF;
  INSERT INTO sync_change_log (table_name, key_json, operation, parent_key, notebook_id, txid, changed_at)
  VALUES ('knowledge_embeddings', jsonb_build_object('object_id', NEW."object_id"), 'upsert',
          NULL, NEW."notebook_id", xact, now());
  RETURN NULL;
END;
$sync_capture_knowledge_embeddings$;
CREATE TRIGGER sync_capture_knowledge_embeddings AFTER INSERT OR DELETE OR UPDATE ON knowledge_embeddings FOR EACH ROW EXECUTE FUNCTION sync_capture_knowledge_embeddings();

CREATE FUNCTION sync_capture_knowledge_object_sources() RETURNS trigger
LANGUAGE plpgsql AS $sync_capture_knowledge_object_sources$
DECLARE
  xact bigint;
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM sync_capture_control WHERE singleton = 1 AND enabled
  ) THEN
    RETURN NULL;
  END IF;
  xact := pg_current_xact_id()::text::bigint;
  IF TG_OP = 'DELETE' THEN
    INSERT INTO sync_change_log (table_name, key_json, operation, parent_key, notebook_id, txid, changed_at)
    VALUES ('knowledge_object_sources', jsonb_build_object('object_id', OLD."object_id", 'source_id', OLD."source_id"), 'delete',
            NULL, OLD."notebook_id", xact, now());
    RETURN NULL;
  END IF;
  IF TG_OP = 'UPDATE' THEN
    IF OLD."object_id" IS DISTINCT FROM NEW."object_id"
       OR OLD."source_id" IS DISTINCT FROM NEW."source_id" THEN
      INSERT INTO sync_change_log (table_name, key_json, operation, parent_key, notebook_id, txid, changed_at)
      VALUES ('knowledge_object_sources', jsonb_build_object('object_id', OLD."object_id", 'source_id', OLD."source_id"), 'delete',
              NULL, OLD."notebook_id", xact, now());
    END IF;
  END IF;
  INSERT INTO sync_change_log (table_name, key_json, operation, parent_key, notebook_id, txid, changed_at)
  VALUES ('knowledge_object_sources', jsonb_build_object('object_id', NEW."object_id", 'source_id', NEW."source_id"), 'upsert',
          NULL, NEW."notebook_id", xact, now());
  RETURN NULL;
END;
$sync_capture_knowledge_object_sources$;
CREATE TRIGGER sync_capture_knowledge_object_sources AFTER INSERT OR DELETE OR UPDATE ON knowledge_object_sources FOR EACH ROW EXECUTE FUNCTION sync_capture_knowledge_object_sources();

CREATE FUNCTION sync_capture_object_schemas() RETURNS trigger
LANGUAGE plpgsql AS $sync_capture_object_schemas$
DECLARE
  xact bigint;
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM sync_capture_control WHERE singleton = 1 AND enabled
  ) THEN
    RETURN NULL;
  END IF;
  xact := pg_current_xact_id()::text::bigint;
  IF TG_OP = 'DELETE' THEN
    INSERT INTO sync_change_log (table_name, key_json, operation, parent_key, notebook_id, txid, changed_at)
    VALUES ('object_schemas', jsonb_build_object('object_type', OLD."object_type"), 'delete',
            NULL, NULL, xact, now());
    RETURN NULL;
  END IF;
  IF TG_OP = 'UPDATE' THEN
    IF OLD."object_type" IS DISTINCT FROM NEW."object_type" THEN
      INSERT INTO sync_change_log (table_name, key_json, operation, parent_key, notebook_id, txid, changed_at)
      VALUES ('object_schemas', jsonb_build_object('object_type', OLD."object_type"), 'delete',
              NULL, NULL, xact, now());
    END IF;
  END IF;
  INSERT INTO sync_change_log (table_name, key_json, operation, parent_key, notebook_id, txid, changed_at)
  VALUES ('object_schemas', jsonb_build_object('object_type', NEW."object_type"), 'upsert',
          NULL, NULL, xact, now());
  RETURN NULL;
END;
$sync_capture_object_schemas$;
CREATE TRIGGER sync_capture_object_schemas AFTER INSERT OR DELETE OR UPDATE ON object_schemas FOR EACH ROW EXECUTE FUNCTION sync_capture_object_schemas();

CREATE FUNCTION sync_capture_notebooks() RETURNS trigger
LANGUAGE plpgsql AS $sync_capture_notebooks$
DECLARE
  xact bigint;
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM sync_capture_control WHERE singleton = 1 AND enabled
  ) THEN
    RETURN NULL;
  END IF;
  xact := pg_current_xact_id()::text::bigint;
  IF TG_OP = 'DELETE' THEN
    INSERT INTO sync_change_log (table_name, key_json, operation, parent_key, notebook_id, txid, changed_at)
    VALUES ('notebooks', jsonb_build_object('id', OLD."id"), 'delete',
            NULL, OLD."id", xact, now());
    RETURN NULL;
  END IF;
  IF TG_OP = 'UPDATE' THEN
    IF OLD."id" IS DISTINCT FROM NEW."id" THEN
      INSERT INTO sync_change_log (table_name, key_json, operation, parent_key, notebook_id, txid, changed_at)
      VALUES ('notebooks', jsonb_build_object('id', OLD."id"), 'delete',
              NULL, OLD."id", xact, now());
    END IF;
  END IF;
  INSERT INTO sync_change_log (table_name, key_json, operation, parent_key, notebook_id, txid, changed_at)
  VALUES ('notebooks', jsonb_build_object('id', NEW."id"), 'upsert',
          NULL, NEW."id", xact, now());
  RETURN NULL;
END;
$sync_capture_notebooks$;
CREATE TRIGGER sync_capture_notebooks AFTER INSERT OR DELETE OR UPDATE ON notebooks FOR EACH ROW EXECUTE FUNCTION sync_capture_notebooks();

CREATE FUNCTION sync_capture_canonical_relations() RETURNS trigger
LANGUAGE plpgsql AS $sync_capture_canonical_relations$
DECLARE
  xact bigint;
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM sync_capture_control WHERE singleton = 1 AND enabled
  ) THEN
    RETURN NULL;
  END IF;
  xact := pg_current_xact_id()::text::bigint;
  IF TG_OP = 'DELETE' THEN
    INSERT INTO sync_change_log (table_name, key_json, operation, parent_key, notebook_id, txid, changed_at)
    VALUES ('canonical_relations', jsonb_build_object('notebook_id', OLD."notebook_id", 'canonical_src', OLD."canonical_src", 'edge_type', OLD."edge_type", 'canonical_tgt', OLD."canonical_tgt"), 'delete',
            NULL, OLD."notebook_id", xact, now());
    RETURN NULL;
  END IF;
  IF TG_OP = 'UPDATE' THEN
    IF OLD."notebook_id" IS DISTINCT FROM NEW."notebook_id"
       OR OLD."canonical_src" IS DISTINCT FROM NEW."canonical_src"
       OR OLD."edge_type" IS DISTINCT FROM NEW."edge_type"
       OR OLD."canonical_tgt" IS DISTINCT FROM NEW."canonical_tgt" THEN
      INSERT INTO sync_change_log (table_name, key_json, operation, parent_key, notebook_id, txid, changed_at)
      VALUES ('canonical_relations', jsonb_build_object('notebook_id', OLD."notebook_id", 'canonical_src', OLD."canonical_src", 'edge_type', OLD."edge_type", 'canonical_tgt', OLD."canonical_tgt"), 'delete',
              NULL, OLD."notebook_id", xact, now());
    END IF;
  END IF;
  INSERT INTO sync_change_log (table_name, key_json, operation, parent_key, notebook_id, txid, changed_at)
  VALUES ('canonical_relations', jsonb_build_object('notebook_id', NEW."notebook_id", 'canonical_src', NEW."canonical_src", 'edge_type', NEW."edge_type", 'canonical_tgt', NEW."canonical_tgt"), 'upsert',
          NULL, NEW."notebook_id", xact, now());
  RETURN NULL;
END;
$sync_capture_canonical_relations$;
CREATE TRIGGER sync_capture_canonical_relations AFTER INSERT OR DELETE OR UPDATE ON canonical_relations FOR EACH ROW EXECUTE FUNCTION sync_capture_canonical_relations();

CREATE FUNCTION sync_capture_communities() RETURNS trigger
LANGUAGE plpgsql AS $sync_capture_communities$
DECLARE
  xact bigint;
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM sync_capture_control WHERE singleton = 1 AND enabled
  ) THEN
    RETURN NULL;
  END IF;
  xact := pg_current_xact_id()::text::bigint;
  IF TG_OP = 'DELETE' THEN
    INSERT INTO sync_change_log (table_name, key_json, operation, parent_key, notebook_id, txid, changed_at)
    VALUES ('communities', jsonb_build_object('id', OLD."id"), 'delete',
            NULL, OLD."notebook_id", xact, now());
    RETURN NULL;
  END IF;
  IF TG_OP = 'UPDATE' THEN
    IF OLD."id" IS DISTINCT FROM NEW."id" THEN
      INSERT INTO sync_change_log (table_name, key_json, operation, parent_key, notebook_id, txid, changed_at)
      VALUES ('communities', jsonb_build_object('id', OLD."id"), 'delete',
              NULL, OLD."notebook_id", xact, now());
    END IF;
  END IF;
  INSERT INTO sync_change_log (table_name, key_json, operation, parent_key, notebook_id, txid, changed_at)
  VALUES ('communities', jsonb_build_object('id', NEW."id"), 'upsert',
          NULL, NEW."notebook_id", xact, now());
  RETURN NULL;
END;
$sync_capture_communities$;
CREATE TRIGGER sync_capture_communities AFTER INSERT OR DELETE OR UPDATE ON communities FOR EACH ROW EXECUTE FUNCTION sync_capture_communities();

CREATE FUNCTION sync_capture_concept_clusters() RETURNS trigger
LANGUAGE plpgsql AS $sync_capture_concept_clusters$
DECLARE
  xact bigint;
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM sync_capture_control WHERE singleton = 1 AND enabled
  ) THEN
    RETURN NULL;
  END IF;
  xact := pg_current_xact_id()::text::bigint;
  IF TG_OP = 'DELETE' THEN
    INSERT INTO sync_change_log (table_name, key_json, operation, parent_key, notebook_id, txid, changed_at)
    VALUES ('concept_clusters', jsonb_build_object('id', OLD."id"), 'delete',
            NULL, OLD."notebook_id", xact, now());
    RETURN NULL;
  END IF;
  IF TG_OP = 'UPDATE' THEN
    IF OLD."id" IS DISTINCT FROM NEW."id" THEN
      INSERT INTO sync_change_log (table_name, key_json, operation, parent_key, notebook_id, txid, changed_at)
      VALUES ('concept_clusters', jsonb_build_object('id', OLD."id"), 'delete',
              NULL, OLD."notebook_id", xact, now());
    END IF;
  END IF;
  INSERT INTO sync_change_log (table_name, key_json, operation, parent_key, notebook_id, txid, changed_at)
  VALUES ('concept_clusters', jsonb_build_object('id', NEW."id"), 'upsert',
          NULL, NEW."notebook_id", xact, now());
  RETURN NULL;
END;
$sync_capture_concept_clusters$;
CREATE TRIGGER sync_capture_concept_clusters AFTER INSERT OR DELETE OR UPDATE ON concept_clusters FOR EACH ROW EXECUTE FUNCTION sync_capture_concept_clusters();

CREATE FUNCTION sync_capture_concept_comentions() RETURNS trigger
LANGUAGE plpgsql AS $sync_capture_concept_comentions$
DECLARE
  xact bigint;
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM sync_capture_control WHERE singleton = 1 AND enabled
  ) THEN
    RETURN NULL;
  END IF;
  xact := pg_current_xact_id()::text::bigint;
  IF TG_OP = 'DELETE' THEN
    INSERT INTO sync_change_log (table_name, key_json, operation, parent_key, notebook_id, txid, changed_at)
    VALUES ('concept_comentions', jsonb_build_object('notebook_id', OLD."notebook_id", 'canonical_a', OLD."canonical_a", 'canonical_b', OLD."canonical_b"), 'delete',
            NULL, OLD."notebook_id", xact, now());
    RETURN NULL;
  END IF;
  IF TG_OP = 'UPDATE' THEN
    IF OLD."notebook_id" IS DISTINCT FROM NEW."notebook_id"
       OR OLD."canonical_a" IS DISTINCT FROM NEW."canonical_a"
       OR OLD."canonical_b" IS DISTINCT FROM NEW."canonical_b" THEN
      INSERT INTO sync_change_log (table_name, key_json, operation, parent_key, notebook_id, txid, changed_at)
      VALUES ('concept_comentions', jsonb_build_object('notebook_id', OLD."notebook_id", 'canonical_a', OLD."canonical_a", 'canonical_b', OLD."canonical_b"), 'delete',
              NULL, OLD."notebook_id", xact, now());
    END IF;
  END IF;
  INSERT INTO sync_change_log (table_name, key_json, operation, parent_key, notebook_id, txid, changed_at)
  VALUES ('concept_comentions', jsonb_build_object('notebook_id', NEW."notebook_id", 'canonical_a', NEW."canonical_a", 'canonical_b', NEW."canonical_b"), 'upsert',
          NULL, NEW."notebook_id", xact, now());
  RETURN NULL;
END;
$sync_capture_concept_comentions$;
CREATE TRIGGER sync_capture_concept_comentions AFTER INSERT OR DELETE OR UPDATE ON concept_comentions FOR EACH ROW EXECUTE FUNCTION sync_capture_concept_comentions();

CREATE FUNCTION sync_capture_knowhow_tables() RETURNS trigger
LANGUAGE plpgsql AS $sync_capture_knowhow_tables$
DECLARE
  xact bigint;
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM sync_capture_control WHERE singleton = 1 AND enabled
  ) THEN
    RETURN NULL;
  END IF;
  xact := pg_current_xact_id()::text::bigint;
  IF TG_OP = 'DELETE' THEN
    INSERT INTO sync_change_log (table_name, key_json, operation, parent_key, notebook_id, txid, changed_at)
    VALUES ('knowhow_tables', jsonb_build_object('id', OLD."id"), 'delete',
            NULL, OLD."notebook_id", xact, now());
    RETURN NULL;
  END IF;
  IF TG_OP = 'UPDATE' THEN
    IF OLD."id" IS DISTINCT FROM NEW."id" THEN
      INSERT INTO sync_change_log (table_name, key_json, operation, parent_key, notebook_id, txid, changed_at)
      VALUES ('knowhow_tables', jsonb_build_object('id', OLD."id"), 'delete',
              NULL, OLD."notebook_id", xact, now());
    END IF;
  END IF;
  INSERT INTO sync_change_log (table_name, key_json, operation, parent_key, notebook_id, txid, changed_at)
  VALUES ('knowhow_tables', jsonb_build_object('id', NEW."id"), 'upsert',
          NULL, NEW."notebook_id", xact, now());
  RETURN NULL;
END;
$sync_capture_knowhow_tables$;
CREATE TRIGGER sync_capture_knowhow_tables AFTER INSERT OR DELETE OR UPDATE ON knowhow_tables FOR EACH ROW EXECUTE FUNCTION sync_capture_knowhow_tables();

CREATE FUNCTION sync_capture_knowhow_changes() RETURNS trigger
LANGUAGE plpgsql AS $sync_capture_knowhow_changes$
DECLARE
  xact bigint;
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM sync_capture_control WHERE singleton = 1 AND enabled
  ) THEN
    RETURN NULL;
  END IF;
  xact := pg_current_xact_id()::text::bigint;
  IF TG_OP = 'DELETE' THEN
    INSERT INTO sync_change_log (table_name, key_json, operation, parent_key, notebook_id, txid, changed_at)
    VALUES ('knowhow_changes', jsonb_build_object('id', OLD."id"), 'delete',
            OLD."table_id", NULL, xact, now());
    RETURN NULL;
  END IF;
  IF TG_OP = 'UPDATE' THEN
    IF OLD."id" IS DISTINCT FROM NEW."id" THEN
      INSERT INTO sync_change_log (table_name, key_json, operation, parent_key, notebook_id, txid, changed_at)
      VALUES ('knowhow_changes', jsonb_build_object('id', OLD."id"), 'delete',
              OLD."table_id", NULL, xact, now());
    END IF;
  END IF;
  INSERT INTO sync_change_log (table_name, key_json, operation, parent_key, notebook_id, txid, changed_at)
  VALUES ('knowhow_changes', jsonb_build_object('id', NEW."id"), 'upsert',
          NEW."table_id", NULL, xact, now());
  RETURN NULL;
END;
$sync_capture_knowhow_changes$;
CREATE TRIGGER sync_capture_knowhow_changes AFTER INSERT OR DELETE OR UPDATE ON knowhow_changes FOR EACH ROW EXECUTE FUNCTION sync_capture_knowhow_changes();

CREATE FUNCTION sync_capture_knowhow_columns() RETURNS trigger
LANGUAGE plpgsql AS $sync_capture_knowhow_columns$
DECLARE
  xact bigint;
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM sync_capture_control WHERE singleton = 1 AND enabled
  ) THEN
    RETURN NULL;
  END IF;
  xact := pg_current_xact_id()::text::bigint;
  IF TG_OP = 'DELETE' THEN
    INSERT INTO sync_change_log (table_name, key_json, operation, parent_key, notebook_id, txid, changed_at)
    VALUES ('knowhow_columns', jsonb_build_object('id', OLD."id"), 'delete',
            OLD."table_id", NULL, xact, now());
    RETURN NULL;
  END IF;
  IF TG_OP = 'UPDATE' THEN
    IF OLD."id" IS DISTINCT FROM NEW."id" THEN
      INSERT INTO sync_change_log (table_name, key_json, operation, parent_key, notebook_id, txid, changed_at)
      VALUES ('knowhow_columns', jsonb_build_object('id', OLD."id"), 'delete',
              OLD."table_id", NULL, xact, now());
    END IF;
  END IF;
  INSERT INTO sync_change_log (table_name, key_json, operation, parent_key, notebook_id, txid, changed_at)
  VALUES ('knowhow_columns', jsonb_build_object('id', NEW."id"), 'upsert',
          NEW."table_id", NULL, xact, now());
  RETURN NULL;
END;
$sync_capture_knowhow_columns$;
CREATE TRIGGER sync_capture_knowhow_columns AFTER INSERT OR DELETE OR UPDATE ON knowhow_columns FOR EACH ROW EXECUTE FUNCTION sync_capture_knowhow_columns();

CREATE FUNCTION sync_capture_knowhow_milestones() RETURNS trigger
LANGUAGE plpgsql AS $sync_capture_knowhow_milestones$
DECLARE
  xact bigint;
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM sync_capture_control WHERE singleton = 1 AND enabled
  ) THEN
    RETURN NULL;
  END IF;
  xact := pg_current_xact_id()::text::bigint;
  IF TG_OP = 'DELETE' THEN
    INSERT INTO sync_change_log (table_name, key_json, operation, parent_key, notebook_id, txid, changed_at)
    VALUES ('knowhow_milestones', jsonb_build_object('id', OLD."id"), 'delete',
            OLD."table_id", NULL, xact, now());
    RETURN NULL;
  END IF;
  IF TG_OP = 'UPDATE' THEN
    IF OLD."id" IS DISTINCT FROM NEW."id" THEN
      INSERT INTO sync_change_log (table_name, key_json, operation, parent_key, notebook_id, txid, changed_at)
      VALUES ('knowhow_milestones', jsonb_build_object('id', OLD."id"), 'delete',
              OLD."table_id", NULL, xact, now());
    END IF;
  END IF;
  INSERT INTO sync_change_log (table_name, key_json, operation, parent_key, notebook_id, txid, changed_at)
  VALUES ('knowhow_milestones', jsonb_build_object('id', NEW."id"), 'upsert',
          NEW."table_id", NULL, xact, now());
  RETURN NULL;
END;
$sync_capture_knowhow_milestones$;
CREATE TRIGGER sync_capture_knowhow_milestones AFTER INSERT OR DELETE OR UPDATE ON knowhow_milestones FOR EACH ROW EXECUTE FUNCTION sync_capture_knowhow_milestones();

CREATE FUNCTION sync_capture_knowhow_rows() RETURNS trigger
LANGUAGE plpgsql AS $sync_capture_knowhow_rows$
DECLARE
  xact bigint;
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM sync_capture_control WHERE singleton = 1 AND enabled
  ) THEN
    RETURN NULL;
  END IF;
  xact := pg_current_xact_id()::text::bigint;
  IF TG_OP = 'DELETE' THEN
    INSERT INTO sync_change_log (table_name, key_json, operation, parent_key, notebook_id, txid, changed_at)
    VALUES ('knowhow_rows', jsonb_build_object('id', OLD."id"), 'delete',
            OLD."table_id", NULL, xact, now());
    RETURN NULL;
  END IF;
  IF TG_OP = 'UPDATE' THEN
    IF OLD."id" IS DISTINCT FROM NEW."id" THEN
      INSERT INTO sync_change_log (table_name, key_json, operation, parent_key, notebook_id, txid, changed_at)
      VALUES ('knowhow_rows', jsonb_build_object('id', OLD."id"), 'delete',
              OLD."table_id", NULL, xact, now());
    END IF;
  END IF;
  INSERT INTO sync_change_log (table_name, key_json, operation, parent_key, notebook_id, txid, changed_at)
  VALUES ('knowhow_rows', jsonb_build_object('id', NEW."id"), 'upsert',
          NEW."table_id", NULL, xact, now());
  RETURN NULL;
END;
$sync_capture_knowhow_rows$;
CREATE TRIGGER sync_capture_knowhow_rows AFTER INSERT OR DELETE OR UPDATE ON knowhow_rows FOR EACH ROW EXECUTE FUNCTION sync_capture_knowhow_rows();

CREATE FUNCTION sync_capture_knowhow_cell_code() RETURNS trigger
LANGUAGE plpgsql AS $sync_capture_knowhow_cell_code$
DECLARE
  xact bigint;
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM sync_capture_control WHERE singleton = 1 AND enabled
  ) THEN
    RETURN NULL;
  END IF;
  xact := pg_current_xact_id()::text::bigint;
  IF TG_OP = 'DELETE' THEN
    INSERT INTO sync_change_log (table_name, key_json, operation, parent_key, notebook_id, txid, changed_at)
    VALUES ('knowhow_cell_code', jsonb_build_object('id', OLD."id"), 'delete',
            OLD."row_id", NULL, xact, now());
    RETURN NULL;
  END IF;
  IF TG_OP = 'UPDATE' THEN
    IF OLD."id" IS DISTINCT FROM NEW."id" THEN
      INSERT INTO sync_change_log (table_name, key_json, operation, parent_key, notebook_id, txid, changed_at)
      VALUES ('knowhow_cell_code', jsonb_build_object('id', OLD."id"), 'delete',
              OLD."row_id", NULL, xact, now());
    END IF;
  END IF;
  INSERT INTO sync_change_log (table_name, key_json, operation, parent_key, notebook_id, txid, changed_at)
  VALUES ('knowhow_cell_code', jsonb_build_object('id', NEW."id"), 'upsert',
          NEW."row_id", NULL, xact, now());
  RETURN NULL;
END;
$sync_capture_knowhow_cell_code$;
CREATE TRIGGER sync_capture_knowhow_cell_code AFTER INSERT OR DELETE OR UPDATE ON knowhow_cell_code FOR EACH ROW EXECUTE FUNCTION sync_capture_knowhow_cell_code();

CREATE FUNCTION sync_capture_knowhow_cells() RETURNS trigger
LANGUAGE plpgsql AS $sync_capture_knowhow_cells$
DECLARE
  xact bigint;
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM sync_capture_control WHERE singleton = 1 AND enabled
  ) THEN
    RETURN NULL;
  END IF;
  xact := pg_current_xact_id()::text::bigint;
  IF TG_OP = 'DELETE' THEN
    INSERT INTO sync_change_log (table_name, key_json, operation, parent_key, notebook_id, txid, changed_at)
    VALUES ('knowhow_cells', jsonb_build_object('id', OLD."id"), 'delete',
            OLD."row_id", NULL, xact, now());
    RETURN NULL;
  END IF;
  IF TG_OP = 'UPDATE' THEN
    IF OLD."id" IS DISTINCT FROM NEW."id" THEN
      INSERT INTO sync_change_log (table_name, key_json, operation, parent_key, notebook_id, txid, changed_at)
      VALUES ('knowhow_cells', jsonb_build_object('id', OLD."id"), 'delete',
              OLD."row_id", NULL, xact, now());
    END IF;
  END IF;
  INSERT INTO sync_change_log (table_name, key_json, operation, parent_key, notebook_id, txid, changed_at)
  VALUES ('knowhow_cells', jsonb_build_object('id', NEW."id"), 'upsert',
          NEW."row_id", NULL, xact, now());
  RETURN NULL;
END;
$sync_capture_knowhow_cells$;
CREATE TRIGGER sync_capture_knowhow_cells AFTER INSERT OR DELETE OR UPDATE ON knowhow_cells FOR EACH ROW EXECUTE FUNCTION sync_capture_knowhow_cells();

CREATE FUNCTION sync_capture_knowledge_objects() RETURNS trigger
LANGUAGE plpgsql AS $sync_capture_knowledge_objects$
DECLARE
  xact bigint;
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM sync_capture_control WHERE singleton = 1 AND enabled
  ) THEN
    RETURN NULL;
  END IF;
  xact := pg_current_xact_id()::text::bigint;
  IF TG_OP = 'DELETE' THEN
    INSERT INTO sync_change_log (table_name, key_json, operation, parent_key, notebook_id, txid, changed_at)
    VALUES ('knowledge_objects', jsonb_build_object('id', OLD."id"), 'delete',
            NULL, OLD."notebook_id", xact, now());
    RETURN NULL;
  END IF;
  IF TG_OP = 'UPDATE' THEN
    IF OLD."id" IS DISTINCT FROM NEW."id" THEN
      INSERT INTO sync_change_log (table_name, key_json, operation, parent_key, notebook_id, txid, changed_at)
      VALUES ('knowledge_objects', jsonb_build_object('id', OLD."id"), 'delete',
              NULL, OLD."notebook_id", xact, now());
    END IF;
  END IF;
  INSERT INTO sync_change_log (table_name, key_json, operation, parent_key, notebook_id, txid, changed_at)
  VALUES ('knowledge_objects', jsonb_build_object('id', NEW."id"), 'upsert',
          NULL, NEW."notebook_id", xact, now());
  RETURN NULL;
END;
$sync_capture_knowledge_objects$;
CREATE TRIGGER sync_capture_knowledge_objects AFTER INSERT OR DELETE OR UPDATE ON knowledge_objects FOR EACH ROW EXECUTE FUNCTION sync_capture_knowledge_objects();

CREATE FUNCTION sync_capture_memory_items() RETURNS trigger
LANGUAGE plpgsql AS $sync_capture_memory_items$
DECLARE
  xact bigint;
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM sync_capture_control WHERE singleton = 1 AND enabled
  ) THEN
    RETURN NULL;
  END IF;
  xact := pg_current_xact_id()::text::bigint;
  IF TG_OP = 'DELETE' THEN
    INSERT INTO sync_change_log (table_name, key_json, operation, parent_key, notebook_id, txid, changed_at)
    VALUES ('memory_items', jsonb_build_object('id', OLD."id"), 'delete',
            NULL, OLD."notebook_id", xact, now());
    RETURN NULL;
  END IF;
  IF TG_OP = 'UPDATE' THEN
    IF OLD."id" IS DISTINCT FROM NEW."id" THEN
      INSERT INTO sync_change_log (table_name, key_json, operation, parent_key, notebook_id, txid, changed_at)
      VALUES ('memory_items', jsonb_build_object('id', OLD."id"), 'delete',
              NULL, OLD."notebook_id", xact, now());
    END IF;
  END IF;
  INSERT INTO sync_change_log (table_name, key_json, operation, parent_key, notebook_id, txid, changed_at)
  VALUES ('memory_items', jsonb_build_object('id', NEW."id"), 'upsert',
          NULL, NEW."notebook_id", xact, now());
  RETURN NULL;
END;
$sync_capture_memory_items$;
CREATE TRIGGER sync_capture_memory_items AFTER INSERT OR DELETE OR UPDATE ON memory_items FOR EACH ROW EXECUTE FUNCTION sync_capture_memory_items();

CREATE FUNCTION sync_capture_memory_embeddings() RETURNS trigger
LANGUAGE plpgsql AS $sync_capture_memory_embeddings$
DECLARE
  xact bigint;
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM sync_capture_control WHERE singleton = 1 AND enabled
  ) THEN
    RETURN NULL;
  END IF;
  xact := pg_current_xact_id()::text::bigint;
  IF TG_OP = 'DELETE' THEN
    INSERT INTO sync_change_log (table_name, key_json, operation, parent_key, notebook_id, txid, changed_at)
    VALUES ('memory_embeddings', jsonb_build_object('memory_id', OLD."memory_id"), 'delete',
            OLD."memory_id", NULL, xact, now());
    RETURN NULL;
  END IF;
  IF TG_OP = 'UPDATE' THEN
    IF OLD."memory_id" IS DISTINCT FROM NEW."memory_id" THEN
      INSERT INTO sync_change_log (table_name, key_json, operation, parent_key, notebook_id, txid, changed_at)
      VALUES ('memory_embeddings', jsonb_build_object('memory_id', OLD."memory_id"), 'delete',
              OLD."memory_id", NULL, xact, now());
    END IF;
  END IF;
  INSERT INTO sync_change_log (table_name, key_json, operation, parent_key, notebook_id, txid, changed_at)
  VALUES ('memory_embeddings', jsonb_build_object('memory_id', NEW."memory_id"), 'upsert',
          NEW."memory_id", NULL, xact, now());
  RETURN NULL;
END;
$sync_capture_memory_embeddings$;
CREATE TRIGGER sync_capture_memory_embeddings AFTER INSERT OR DELETE OR UPDATE ON memory_embeddings FOR EACH ROW EXECUTE FUNCTION sync_capture_memory_embeddings();

CREATE FUNCTION sync_capture_memory_provenance() RETURNS trigger
LANGUAGE plpgsql AS $sync_capture_memory_provenance$
DECLARE
  xact bigint;
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM sync_capture_control WHERE singleton = 1 AND enabled
  ) THEN
    RETURN NULL;
  END IF;
  xact := pg_current_xact_id()::text::bigint;
  IF TG_OP = 'DELETE' THEN
    INSERT INTO sync_change_log (table_name, key_json, operation, parent_key, notebook_id, txid, changed_at)
    VALUES ('memory_provenance', jsonb_build_object('id', OLD."id"), 'delete',
            OLD."memory_id", NULL, xact, now());
    RETURN NULL;
  END IF;
  IF TG_OP = 'UPDATE' THEN
    IF OLD."id" IS DISTINCT FROM NEW."id" THEN
      INSERT INTO sync_change_log (table_name, key_json, operation, parent_key, notebook_id, txid, changed_at)
      VALUES ('memory_provenance', jsonb_build_object('id', OLD."id"), 'delete',
              OLD."memory_id", NULL, xact, now());
    END IF;
  END IF;
  INSERT INTO sync_change_log (table_name, key_json, operation, parent_key, notebook_id, txid, changed_at)
  VALUES ('memory_provenance', jsonb_build_object('id', NEW."id"), 'upsert',
          NEW."memory_id", NULL, xact, now());
  RETURN NULL;
END;
$sync_capture_memory_provenance$;
CREATE TRIGGER sync_capture_memory_provenance AFTER INSERT OR DELETE OR UPDATE ON memory_provenance FOR EACH ROW EXECUTE FUNCTION sync_capture_memory_provenance();

CREATE FUNCTION sync_capture_memory_revisions() RETURNS trigger
LANGUAGE plpgsql AS $sync_capture_memory_revisions$
DECLARE
  xact bigint;
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM sync_capture_control WHERE singleton = 1 AND enabled
  ) THEN
    RETURN NULL;
  END IF;
  xact := pg_current_xact_id()::text::bigint;
  IF TG_OP = 'DELETE' THEN
    INSERT INTO sync_change_log (table_name, key_json, operation, parent_key, notebook_id, txid, changed_at)
    VALUES ('memory_revisions', jsonb_build_object('id', OLD."id"), 'delete',
            OLD."memory_id", NULL, xact, now());
    RETURN NULL;
  END IF;
  IF TG_OP = 'UPDATE' THEN
    IF OLD."id" IS DISTINCT FROM NEW."id" THEN
      INSERT INTO sync_change_log (table_name, key_json, operation, parent_key, notebook_id, txid, changed_at)
      VALUES ('memory_revisions', jsonb_build_object('id', OLD."id"), 'delete',
              OLD."memory_id", NULL, xact, now());
    END IF;
  END IF;
  INSERT INTO sync_change_log (table_name, key_json, operation, parent_key, notebook_id, txid, changed_at)
  VALUES ('memory_revisions', jsonb_build_object('id', NEW."id"), 'upsert',
          NEW."memory_id", NULL, xact, now());
  RETURN NULL;
END;
$sync_capture_memory_revisions$;
CREATE TRIGGER sync_capture_memory_revisions AFTER INSERT OR DELETE OR UPDATE ON memory_revisions FOR EACH ROW EXECUTE FUNCTION sync_capture_memory_revisions();

CREATE FUNCTION sync_capture_mention_edges() RETURNS trigger
LANGUAGE plpgsql AS $sync_capture_mention_edges$
DECLARE
  xact bigint;
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM sync_capture_control WHERE singleton = 1 AND enabled
  ) THEN
    RETURN NULL;
  END IF;
  xact := pg_current_xact_id()::text::bigint;
  IF TG_OP = 'DELETE' THEN
    INSERT INTO sync_change_log (table_name, key_json, operation, parent_key, notebook_id, txid, changed_at)
    VALUES ('mention_edges', jsonb_build_object('notebook_id', OLD."notebook_id", 'claim_object_id', OLD."claim_object_id", 'concept_canonical_id', OLD."concept_canonical_id"), 'delete',
            NULL, OLD."notebook_id", xact, now());
    RETURN NULL;
  END IF;
  IF TG_OP = 'UPDATE' THEN
    IF OLD."notebook_id" IS DISTINCT FROM NEW."notebook_id"
       OR OLD."claim_object_id" IS DISTINCT FROM NEW."claim_object_id"
       OR OLD."concept_canonical_id" IS DISTINCT FROM NEW."concept_canonical_id" THEN
      INSERT INTO sync_change_log (table_name, key_json, operation, parent_key, notebook_id, txid, changed_at)
      VALUES ('mention_edges', jsonb_build_object('notebook_id', OLD."notebook_id", 'claim_object_id', OLD."claim_object_id", 'concept_canonical_id', OLD."concept_canonical_id"), 'delete',
              NULL, OLD."notebook_id", xact, now());
    END IF;
  END IF;
  INSERT INTO sync_change_log (table_name, key_json, operation, parent_key, notebook_id, txid, changed_at)
  VALUES ('mention_edges', jsonb_build_object('notebook_id', NEW."notebook_id", 'claim_object_id', NEW."claim_object_id", 'concept_canonical_id', NEW."concept_canonical_id"), 'upsert',
          NULL, NEW."notebook_id", xact, now());
  RETURN NULL;
END;
$sync_capture_mention_edges$;
CREATE TRIGGER sync_capture_mention_edges AFTER INSERT OR DELETE OR UPDATE ON mention_edges FOR EACH ROW EXECUTE FUNCTION sync_capture_mention_edges();

CREATE FUNCTION sync_capture_notebook_assets() RETURNS trigger
LANGUAGE plpgsql AS $sync_capture_notebook_assets$
DECLARE
  xact bigint;
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM sync_capture_control WHERE singleton = 1 AND enabled
  ) THEN
    RETURN NULL;
  END IF;
  xact := pg_current_xact_id()::text::bigint;
  IF TG_OP = 'DELETE' THEN
    INSERT INTO sync_change_log (table_name, key_json, operation, parent_key, notebook_id, txid, changed_at)
    VALUES ('notebook_assets', jsonb_build_object('id', OLD."id"), 'delete',
            NULL, OLD."notebook_id", xact, now());
    RETURN NULL;
  END IF;
  IF TG_OP = 'UPDATE' THEN
    IF OLD."id" IS DISTINCT FROM NEW."id" THEN
      INSERT INTO sync_change_log (table_name, key_json, operation, parent_key, notebook_id, txid, changed_at)
      VALUES ('notebook_assets', jsonb_build_object('id', OLD."id"), 'delete',
              NULL, OLD."notebook_id", xact, now());
    END IF;
  END IF;
  INSERT INTO sync_change_log (table_name, key_json, operation, parent_key, notebook_id, txid, changed_at)
  VALUES ('notebook_assets', jsonb_build_object('id', NEW."id"), 'upsert',
          NULL, NEW."notebook_id", xact, now());
  RETURN NULL;
END;
$sync_capture_notebook_assets$;
CREATE TRIGGER sync_capture_notebook_assets AFTER INSERT OR DELETE OR UPDATE ON notebook_assets FOR EACH ROW EXECUTE FUNCTION sync_capture_notebook_assets();

CREATE FUNCTION sync_capture_notebook_bases() RETURNS trigger
LANGUAGE plpgsql AS $sync_capture_notebook_bases$
DECLARE
  xact bigint;
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM sync_capture_control WHERE singleton = 1 AND enabled
  ) THEN
    RETURN NULL;
  END IF;
  xact := pg_current_xact_id()::text::bigint;
  IF TG_OP = 'DELETE' THEN
    INSERT INTO sync_change_log (table_name, key_json, operation, parent_key, notebook_id, txid, changed_at)
    VALUES ('notebook_bases', jsonb_build_object('notebook_id', OLD."notebook_id", 'base_notebook_id', OLD."base_notebook_id"), 'delete',
            NULL, OLD."notebook_id", xact, now());
    RETURN NULL;
  END IF;
  IF TG_OP = 'UPDATE' THEN
    IF OLD."notebook_id" IS DISTINCT FROM NEW."notebook_id"
       OR OLD."base_notebook_id" IS DISTINCT FROM NEW."base_notebook_id" THEN
      INSERT INTO sync_change_log (table_name, key_json, operation, parent_key, notebook_id, txid, changed_at)
      VALUES ('notebook_bases', jsonb_build_object('notebook_id', OLD."notebook_id", 'base_notebook_id', OLD."base_notebook_id"), 'delete',
              NULL, OLD."notebook_id", xact, now());
    END IF;
  END IF;
  INSERT INTO sync_change_log (table_name, key_json, operation, parent_key, notebook_id, txid, changed_at)
  VALUES ('notebook_bases', jsonb_build_object('notebook_id', NEW."notebook_id", 'base_notebook_id', NEW."base_notebook_id"), 'upsert',
          NULL, NEW."notebook_id", xact, now());
  RETURN NULL;
END;
$sync_capture_notebook_bases$;
CREATE TRIGGER sync_capture_notebook_bases AFTER INSERT OR DELETE OR UPDATE ON notebook_bases FOR EACH ROW EXECUTE FUNCTION sync_capture_notebook_bases();

CREATE FUNCTION sync_capture_notebook_members() RETURNS trigger
LANGUAGE plpgsql AS $sync_capture_notebook_members$
DECLARE
  xact bigint;
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM sync_capture_control WHERE singleton = 1 AND enabled
  ) THEN
    RETURN NULL;
  END IF;
  xact := pg_current_xact_id()::text::bigint;
  IF TG_OP = 'DELETE' THEN
    INSERT INTO sync_change_log (table_name, key_json, operation, parent_key, notebook_id, txid, changed_at)
    VALUES ('notebook_members', jsonb_build_object('notebook_id', OLD."notebook_id", 'user_id', OLD."user_id"), 'delete',
            NULL, OLD."notebook_id", xact, now());
    RETURN NULL;
  END IF;
  IF TG_OP = 'UPDATE' THEN
    IF OLD."notebook_id" IS DISTINCT FROM NEW."notebook_id"
       OR OLD."user_id" IS DISTINCT FROM NEW."user_id" THEN
      INSERT INTO sync_change_log (table_name, key_json, operation, parent_key, notebook_id, txid, changed_at)
      VALUES ('notebook_members', jsonb_build_object('notebook_id', OLD."notebook_id", 'user_id', OLD."user_id"), 'delete',
              NULL, OLD."notebook_id", xact, now());
    END IF;
  END IF;
  INSERT INTO sync_change_log (table_name, key_json, operation, parent_key, notebook_id, txid, changed_at)
  VALUES ('notebook_members', jsonb_build_object('notebook_id', NEW."notebook_id", 'user_id', NEW."user_id"), 'upsert',
          NULL, NEW."notebook_id", xact, now());
  RETURN NULL;
END;
$sync_capture_notebook_members$;
CREATE TRIGGER sync_capture_notebook_members AFTER INSERT OR DELETE OR UPDATE ON notebook_members FOR EACH ROW EXECUTE FUNCTION sync_capture_notebook_members();

CREATE FUNCTION sync_capture_sources() RETURNS trigger
LANGUAGE plpgsql AS $sync_capture_sources$
DECLARE
  xact bigint;
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM sync_capture_control WHERE singleton = 1 AND enabled
  ) THEN
    RETURN NULL;
  END IF;
  xact := pg_current_xact_id()::text::bigint;
  IF TG_OP = 'DELETE' THEN
    INSERT INTO sync_change_log (table_name, key_json, operation, parent_key, notebook_id, txid, changed_at)
    VALUES ('sources', jsonb_build_object('id', OLD."id"), 'delete',
            NULL, OLD."notebook_id", xact, now());
    RETURN NULL;
  END IF;
  IF TG_OP = 'UPDATE' THEN
    IF OLD."id" IS DISTINCT FROM NEW."id" THEN
      INSERT INTO sync_change_log (table_name, key_json, operation, parent_key, notebook_id, txid, changed_at)
      VALUES ('sources', jsonb_build_object('id', OLD."id"), 'delete',
              NULL, OLD."notebook_id", xact, now());
    END IF;
  END IF;
  INSERT INTO sync_change_log (table_name, key_json, operation, parent_key, notebook_id, txid, changed_at)
  VALUES ('sources', jsonb_build_object('id', NEW."id"), 'upsert',
          NULL, NEW."notebook_id", xact, now());
  RETURN NULL;
END;
$sync_capture_sources$;
CREATE TRIGGER sync_capture_sources AFTER INSERT OR DELETE OR UPDATE ON sources FOR EACH ROW EXECUTE FUNCTION sync_capture_sources();

CREATE FUNCTION sync_capture_chunks() RETURNS trigger
LANGUAGE plpgsql AS $sync_capture_chunks$
DECLARE
  xact bigint;
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM sync_capture_control WHERE singleton = 1 AND enabled
  ) THEN
    RETURN NULL;
  END IF;
  xact := pg_current_xact_id()::text::bigint;
  IF TG_OP = 'DELETE' THEN
    INSERT INTO sync_change_log (table_name, key_json, operation, parent_key, notebook_id, txid, changed_at)
    VALUES ('chunks', jsonb_build_object('id', OLD."id"), 'delete',
            NULL, OLD."notebook_id", xact, now());
    RETURN NULL;
  END IF;
  IF TG_OP = 'UPDATE' THEN
    IF OLD."id" IS DISTINCT FROM NEW."id" THEN
      INSERT INTO sync_change_log (table_name, key_json, operation, parent_key, notebook_id, txid, changed_at)
      VALUES ('chunks', jsonb_build_object('id', OLD."id"), 'delete',
              NULL, OLD."notebook_id", xact, now());
    END IF;
  END IF;
  INSERT INTO sync_change_log (table_name, key_json, operation, parent_key, notebook_id, txid, changed_at)
  VALUES ('chunks', jsonb_build_object('id', NEW."id"), 'upsert',
          NULL, NEW."notebook_id", xact, now());
  RETURN NULL;
END;
$sync_capture_chunks$;
CREATE TRIGGER sync_capture_chunks AFTER INSERT OR DELETE OR UPDATE ON chunks FOR EACH ROW EXECUTE FUNCTION sync_capture_chunks();

CREATE FUNCTION sync_capture_chunk_embeddings() RETURNS trigger
LANGUAGE plpgsql AS $sync_capture_chunk_embeddings$
DECLARE
  xact bigint;
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM sync_capture_control WHERE singleton = 1 AND enabled
  ) THEN
    RETURN NULL;
  END IF;
  xact := pg_current_xact_id()::text::bigint;
  IF TG_OP = 'DELETE' THEN
    INSERT INTO sync_change_log (table_name, key_json, operation, parent_key, notebook_id, txid, changed_at)
    VALUES ('chunk_embeddings', jsonb_build_object('chunk_id', OLD."chunk_id"), 'delete',
            NULL, OLD."notebook_id", xact, now());
    RETURN NULL;
  END IF;
  IF TG_OP = 'UPDATE' THEN
    IF OLD."chunk_id" IS DISTINCT FROM NEW."chunk_id" THEN
      INSERT INTO sync_change_log (table_name, key_json, operation, parent_key, notebook_id, txid, changed_at)
      VALUES ('chunk_embeddings', jsonb_build_object('chunk_id', OLD."chunk_id"), 'delete',
              NULL, OLD."notebook_id", xact, now());
    END IF;
  END IF;
  INSERT INTO sync_change_log (table_name, key_json, operation, parent_key, notebook_id, txid, changed_at)
  VALUES ('chunk_embeddings', jsonb_build_object('chunk_id', NEW."chunk_id"), 'upsert',
          NULL, NEW."notebook_id", xact, now());
  RETURN NULL;
END;
$sync_capture_chunk_embeddings$;
CREATE TRIGGER sync_capture_chunk_embeddings AFTER INSERT OR DELETE OR UPDATE ON chunk_embeddings FOR EACH ROW EXECUTE FUNCTION sync_capture_chunk_embeddings();

CREATE FUNCTION sync_capture_knowledge_relations() RETURNS trigger
LANGUAGE plpgsql AS $sync_capture_knowledge_relations$
DECLARE
  xact bigint;
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM sync_capture_control WHERE singleton = 1 AND enabled
  ) THEN
    RETURN NULL;
  END IF;
  xact := pg_current_xact_id()::text::bigint;
  IF TG_OP = 'DELETE' THEN
    INSERT INTO sync_change_log (table_name, key_json, operation, parent_key, notebook_id, txid, changed_at)
    VALUES ('knowledge_relations', jsonb_build_object('id', OLD."id"), 'delete',
            NULL, OLD."notebook_id", xact, now());
    RETURN NULL;
  END IF;
  IF TG_OP = 'UPDATE' THEN
    IF OLD."id" IS DISTINCT FROM NEW."id" THEN
      INSERT INTO sync_change_log (table_name, key_json, operation, parent_key, notebook_id, txid, changed_at)
      VALUES ('knowledge_relations', jsonb_build_object('id', OLD."id"), 'delete',
              NULL, OLD."notebook_id", xact, now());
    END IF;
  END IF;
  INSERT INTO sync_change_log (table_name, key_json, operation, parent_key, notebook_id, txid, changed_at)
  VALUES ('knowledge_relations', jsonb_build_object('id', NEW."id"), 'upsert',
          NULL, NEW."notebook_id", xact, now());
  RETURN NULL;
END;
$sync_capture_knowledge_relations$;
CREATE TRIGGER sync_capture_knowledge_relations AFTER INSERT OR DELETE OR UPDATE ON knowledge_relations FOR EACH ROW EXECUTE FUNCTION sync_capture_knowledge_relations();

CREATE FUNCTION sync_capture_relation_embeddings() RETURNS trigger
LANGUAGE plpgsql AS $sync_capture_relation_embeddings$
DECLARE
  xact bigint;
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM sync_capture_control WHERE singleton = 1 AND enabled
  ) THEN
    RETURN NULL;
  END IF;
  xact := pg_current_xact_id()::text::bigint;
  IF TG_OP = 'DELETE' THEN
    INSERT INTO sync_change_log (table_name, key_json, operation, parent_key, notebook_id, txid, changed_at)
    VALUES ('relation_embeddings', jsonb_build_object('relation_id', OLD."relation_id"), 'delete',
            NULL, OLD."notebook_id", xact, now());
    RETURN NULL;
  END IF;
  IF TG_OP = 'UPDATE' THEN
    IF OLD."relation_id" IS DISTINCT FROM NEW."relation_id" THEN
      INSERT INTO sync_change_log (table_name, key_json, operation, parent_key, notebook_id, txid, changed_at)
      VALUES ('relation_embeddings', jsonb_build_object('relation_id', OLD."relation_id"), 'delete',
              NULL, OLD."notebook_id", xact, now());
    END IF;
  END IF;
  INSERT INTO sync_change_log (table_name, key_json, operation, parent_key, notebook_id, txid, changed_at)
  VALUES ('relation_embeddings', jsonb_build_object('relation_id', NEW."relation_id"), 'upsert',
          NULL, NEW."notebook_id", xact, now());
  RETURN NULL;
END;
$sync_capture_relation_embeddings$;
CREATE TRIGGER sync_capture_relation_embeddings AFTER INSERT OR DELETE OR UPDATE ON relation_embeddings FOR EACH ROW EXECUTE FUNCTION sync_capture_relation_embeddings();

CREATE FUNCTION sync_capture_source_authors() RETURNS trigger
LANGUAGE plpgsql AS $sync_capture_source_authors$
DECLARE
  xact bigint;
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM sync_capture_control WHERE singleton = 1 AND enabled
  ) THEN
    RETURN NULL;
  END IF;
  xact := pg_current_xact_id()::text::bigint;
  IF TG_OP = 'DELETE' THEN
    INSERT INTO sync_change_log (table_name, key_json, operation, parent_key, notebook_id, txid, changed_at)
    VALUES ('source_authors', jsonb_build_object('id', OLD."id"), 'delete',
            NULL, OLD."notebook_id", xact, now());
    RETURN NULL;
  END IF;
  IF TG_OP = 'UPDATE' THEN
    IF OLD."id" IS DISTINCT FROM NEW."id" THEN
      INSERT INTO sync_change_log (table_name, key_json, operation, parent_key, notebook_id, txid, changed_at)
      VALUES ('source_authors', jsonb_build_object('id', OLD."id"), 'delete',
              NULL, OLD."notebook_id", xact, now());
    END IF;
  END IF;
  INSERT INTO sync_change_log (table_name, key_json, operation, parent_key, notebook_id, txid, changed_at)
  VALUES ('source_authors', jsonb_build_object('id', NEW."id"), 'upsert',
          NULL, NEW."notebook_id", xact, now());
  RETURN NULL;
END;
$sync_capture_source_authors$;
CREATE TRIGGER sync_capture_source_authors AFTER INSERT OR DELETE OR UPDATE ON source_authors FOR EACH ROW EXECUTE FUNCTION sync_capture_source_authors();

CREATE FUNCTION sync_capture_source_elements() RETURNS trigger
LANGUAGE plpgsql AS $sync_capture_source_elements$
DECLARE
  xact bigint;
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM sync_capture_control WHERE singleton = 1 AND enabled
  ) THEN
    RETURN NULL;
  END IF;
  xact := pg_current_xact_id()::text::bigint;
  IF TG_OP = 'DELETE' THEN
    INSERT INTO sync_change_log (table_name, key_json, operation, parent_key, notebook_id, txid, changed_at)
    VALUES ('source_elements', jsonb_build_object('id', OLD."id"), 'delete',
            OLD."source_id", NULL, xact, now());
    RETURN NULL;
  END IF;
  IF TG_OP = 'UPDATE' THEN
    IF OLD."id" IS DISTINCT FROM NEW."id" THEN
      INSERT INTO sync_change_log (table_name, key_json, operation, parent_key, notebook_id, txid, changed_at)
      VALUES ('source_elements', jsonb_build_object('id', OLD."id"), 'delete',
              OLD."source_id", NULL, xact, now());
    END IF;
  END IF;
  INSERT INTO sync_change_log (table_name, key_json, operation, parent_key, notebook_id, txid, changed_at)
  VALUES ('source_elements', jsonb_build_object('id', NEW."id"), 'upsert',
          NEW."source_id", NULL, xact, now());
  RETURN NULL;
END;
$sync_capture_source_elements$;
CREATE TRIGGER sync_capture_source_elements AFTER INSERT OR DELETE OR UPDATE ON source_elements FOR EACH ROW EXECUTE FUNCTION sync_capture_source_elements();

CREATE FUNCTION sync_capture_element_embeddings() RETURNS trigger
LANGUAGE plpgsql AS $sync_capture_element_embeddings$
DECLARE
  xact bigint;
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM sync_capture_control WHERE singleton = 1 AND enabled
  ) THEN
    RETURN NULL;
  END IF;
  xact := pg_current_xact_id()::text::bigint;
  IF TG_OP = 'DELETE' THEN
    INSERT INTO sync_change_log (table_name, key_json, operation, parent_key, notebook_id, txid, changed_at)
    VALUES ('element_embeddings', jsonb_build_object('element_id', OLD."element_id"), 'delete',
            NULL, OLD."notebook_id", xact, now());
    RETURN NULL;
  END IF;
  IF TG_OP = 'UPDATE' THEN
    IF OLD."element_id" IS DISTINCT FROM NEW."element_id" THEN
      INSERT INTO sync_change_log (table_name, key_json, operation, parent_key, notebook_id, txid, changed_at)
      VALUES ('element_embeddings', jsonb_build_object('element_id', OLD."element_id"), 'delete',
              NULL, OLD."notebook_id", xact, now());
    END IF;
  END IF;
  INSERT INTO sync_change_log (table_name, key_json, operation, parent_key, notebook_id, txid, changed_at)
  VALUES ('element_embeddings', jsonb_build_object('element_id', NEW."element_id"), 'upsert',
          NULL, NEW."notebook_id", xact, now());
  RETURN NULL;
END;
$sync_capture_element_embeddings$;
CREATE TRIGGER sync_capture_element_embeddings AFTER INSERT OR DELETE OR UPDATE ON element_embeddings FOR EACH ROW EXECUTE FUNCTION sync_capture_element_embeddings();

CREATE FUNCTION sync_capture_source_paper_meta() RETURNS trigger
LANGUAGE plpgsql AS $sync_capture_source_paper_meta$
DECLARE
  xact bigint;
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM sync_capture_control WHERE singleton = 1 AND enabled
  ) THEN
    RETURN NULL;
  END IF;
  xact := pg_current_xact_id()::text::bigint;
  IF TG_OP = 'DELETE' THEN
    INSERT INTO sync_change_log (table_name, key_json, operation, parent_key, notebook_id, txid, changed_at)
    VALUES ('source_paper_meta', jsonb_build_object('source_id', OLD."source_id"), 'delete',
            NULL, OLD."notebook_id", xact, now());
    RETURN NULL;
  END IF;
  IF TG_OP = 'UPDATE' THEN
    IF OLD."source_id" IS DISTINCT FROM NEW."source_id" THEN
      INSERT INTO sync_change_log (table_name, key_json, operation, parent_key, notebook_id, txid, changed_at)
      VALUES ('source_paper_meta', jsonb_build_object('source_id', OLD."source_id"), 'delete',
              NULL, OLD."notebook_id", xact, now());
    END IF;
  END IF;
  INSERT INTO sync_change_log (table_name, key_json, operation, parent_key, notebook_id, txid, changed_at)
  VALUES ('source_paper_meta', jsonb_build_object('source_id', NEW."source_id"), 'upsert',
          NULL, NEW."notebook_id", xact, now());
  RETURN NULL;
END;
$sync_capture_source_paper_meta$;
CREATE TRIGGER sync_capture_source_paper_meta AFTER INSERT OR DELETE OR UPDATE ON source_paper_meta FOR EACH ROW EXECUTE FUNCTION sync_capture_source_paper_meta();

CREATE FUNCTION sync_capture_unified_kg_state() RETURNS trigger
LANGUAGE plpgsql AS $sync_capture_unified_kg_state$
DECLARE
  xact bigint;
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM sync_capture_control WHERE singleton = 1 AND enabled
  ) THEN
    RETURN NULL;
  END IF;
  xact := pg_current_xact_id()::text::bigint;
  IF TG_OP = 'DELETE' THEN
    INSERT INTO sync_change_log (table_name, key_json, operation, parent_key, notebook_id, txid, changed_at)
    VALUES ('unified_kg_state', jsonb_build_object('notebook_id', OLD."notebook_id"), 'delete',
            NULL, OLD."notebook_id", xact, now());
    RETURN NULL;
  END IF;
  IF TG_OP = 'UPDATE' THEN
    IF OLD."notebook_id" IS DISTINCT FROM NEW."notebook_id" THEN
      INSERT INTO sync_change_log (table_name, key_json, operation, parent_key, notebook_id, txid, changed_at)
      VALUES ('unified_kg_state', jsonb_build_object('notebook_id', OLD."notebook_id"), 'delete',
              NULL, OLD."notebook_id", xact, now());
    END IF;
  END IF;
  INSERT INTO sync_change_log (table_name, key_json, operation, parent_key, notebook_id, txid, changed_at)
  VALUES ('unified_kg_state', jsonb_build_object('notebook_id', NEW."notebook_id"), 'upsert',
          NULL, NEW."notebook_id", xact, now());
  IF TG_OP = 'INSERT' THEN
    IF NEW."kg_reset_epoch" > 0 THEN
      INSERT INTO sync_change_log (table_name, key_json, operation, parent_key, notebook_id, txid, changed_at)
      VALUES ('unified_kg_state', jsonb_build_object('notebook_id', NEW."notebook_id"), 'kg_epoch',
              NULL, NEW."notebook_id", xact, now());
    END IF;
  ELSE
    IF OLD."kg_reset_epoch" IS DISTINCT FROM NEW."kg_reset_epoch" THEN
      INSERT INTO sync_change_log (table_name, key_json, operation, parent_key, notebook_id, txid, changed_at)
      VALUES ('unified_kg_state', jsonb_build_object('notebook_id', NEW."notebook_id"), 'kg_epoch',
              NULL, NEW."notebook_id", xact, now());
    END IF;
  END IF;
  RETURN NULL;
END;
$sync_capture_unified_kg_state$;
CREATE TRIGGER sync_capture_unified_kg_state AFTER INSERT OR DELETE OR UPDATE ON unified_kg_state FOR EACH ROW EXECUTE FUNCTION sync_capture_unified_kg_state();

CREATE FUNCTION sync_capture_kg_analysis_artifacts() RETURNS trigger
LANGUAGE plpgsql AS $sync_capture_kg_analysis_artifacts$
DECLARE
  xact bigint;
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM sync_capture_control WHERE singleton = 1 AND enabled
  ) THEN
    RETURN NULL;
  END IF;
  xact := pg_current_xact_id()::text::bigint;
  IF TG_OP = 'DELETE' THEN
    INSERT INTO sync_change_log (table_name, key_json, operation, parent_key, notebook_id, txid, changed_at)
    VALUES ('kg_analysis_artifacts', jsonb_build_object('notebook_id', OLD."notebook_id", 'kind', OLD."kind"), 'delete',
            NULL, OLD."notebook_id", xact, now());
    RETURN NULL;
  END IF;
  IF TG_OP = 'UPDATE' THEN
    IF OLD."notebook_id" IS DISTINCT FROM NEW."notebook_id"
       OR OLD."kind" IS DISTINCT FROM NEW."kind" THEN
      INSERT INTO sync_change_log (table_name, key_json, operation, parent_key, notebook_id, txid, changed_at)
      VALUES ('kg_analysis_artifacts', jsonb_build_object('notebook_id', OLD."notebook_id", 'kind', OLD."kind"), 'delete',
              NULL, OLD."notebook_id", xact, now());
    END IF;
  END IF;
  INSERT INTO sync_change_log (table_name, key_json, operation, parent_key, notebook_id, txid, changed_at)
  VALUES ('kg_analysis_artifacts', jsonb_build_object('notebook_id', NEW."notebook_id", 'kind', NEW."kind"), 'upsert',
          NULL, NEW."notebook_id", xact, now());
  RETURN NULL;
END;
$sync_capture_kg_analysis_artifacts$;
CREATE TRIGGER sync_capture_kg_analysis_artifacts AFTER INSERT OR DELETE OR UPDATE ON kg_analysis_artifacts FOR EACH ROW EXECUTE FUNCTION sync_capture_kg_analysis_artifacts();

CREATE FUNCTION sync_capture_kg_community_edges() RETURNS trigger
LANGUAGE plpgsql AS $sync_capture_kg_community_edges$
DECLARE
  xact bigint;
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM sync_capture_control WHERE singleton = 1 AND enabled
  ) THEN
    RETURN NULL;
  END IF;
  xact := pg_current_xact_id()::text::bigint;
  IF TG_OP = 'DELETE' THEN
    INSERT INTO sync_change_log (table_name, key_json, operation, parent_key, notebook_id, txid, changed_at)
    VALUES ('kg_community_edges', jsonb_build_object('notebook_id', OLD."notebook_id", 'src_community_id', OLD."src_community_id", 'dst_community_id', OLD."dst_community_id"), 'delete',
            NULL, OLD."notebook_id", xact, now());
    RETURN NULL;
  END IF;
  IF TG_OP = 'UPDATE' THEN
    IF OLD."notebook_id" IS DISTINCT FROM NEW."notebook_id"
       OR OLD."src_community_id" IS DISTINCT FROM NEW."src_community_id"
       OR OLD."dst_community_id" IS DISTINCT FROM NEW."dst_community_id" THEN
      INSERT INTO sync_change_log (table_name, key_json, operation, parent_key, notebook_id, txid, changed_at)
      VALUES ('kg_community_edges', jsonb_build_object('notebook_id', OLD."notebook_id", 'src_community_id', OLD."src_community_id", 'dst_community_id', OLD."dst_community_id"), 'delete',
              NULL, OLD."notebook_id", xact, now());
    END IF;
  END IF;
  INSERT INTO sync_change_log (table_name, key_json, operation, parent_key, notebook_id, txid, changed_at)
  VALUES ('kg_community_edges', jsonb_build_object('notebook_id', NEW."notebook_id", 'src_community_id', NEW."src_community_id", 'dst_community_id', NEW."dst_community_id"), 'upsert',
          NULL, NEW."notebook_id", xact, now());
  RETURN NULL;
END;
$sync_capture_kg_community_edges$;
CREATE TRIGGER sync_capture_kg_community_edges AFTER INSERT OR DELETE OR UPDATE ON kg_community_edges FOR EACH ROW EXECUTE FUNCTION sync_capture_kg_community_edges();

CREATE FUNCTION sync_capture_kg_source_profiles() RETURNS trigger
LANGUAGE plpgsql AS $sync_capture_kg_source_profiles$
DECLARE
  xact bigint;
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM sync_capture_control WHERE singleton = 1 AND enabled
  ) THEN
    RETURN NULL;
  END IF;
  xact := pg_current_xact_id()::text::bigint;
  IF TG_OP = 'DELETE' THEN
    INSERT INTO sync_change_log (table_name, key_json, operation, parent_key, notebook_id, txid, changed_at)
    VALUES ('kg_source_profiles', jsonb_build_object('notebook_id', OLD."notebook_id", 'source_id', OLD."source_id"), 'delete',
            NULL, OLD."notebook_id", xact, now());
    RETURN NULL;
  END IF;
  IF TG_OP = 'UPDATE' THEN
    IF OLD."notebook_id" IS DISTINCT FROM NEW."notebook_id"
       OR OLD."source_id" IS DISTINCT FROM NEW."source_id" THEN
      INSERT INTO sync_change_log (table_name, key_json, operation, parent_key, notebook_id, txid, changed_at)
      VALUES ('kg_source_profiles', jsonb_build_object('notebook_id', OLD."notebook_id", 'source_id', OLD."source_id"), 'delete',
              NULL, OLD."notebook_id", xact, now());
    END IF;
  END IF;
  INSERT INTO sync_change_log (table_name, key_json, operation, parent_key, notebook_id, txid, changed_at)
  VALUES ('kg_source_profiles', jsonb_build_object('notebook_id', NEW."notebook_id", 'source_id', NEW."source_id"), 'upsert',
          NULL, NEW."notebook_id", xact, now());
  RETURN NULL;
END;
$sync_capture_kg_source_profiles$;
CREATE TRIGGER sync_capture_kg_source_profiles AFTER INSERT OR DELETE OR UPDATE ON kg_source_profiles FOR EACH ROW EXECUTE FUNCTION sync_capture_kg_source_profiles();

CREATE FUNCTION sync_capture_knowledge_source_facts() RETURNS trigger
LANGUAGE plpgsql AS $sync_capture_knowledge_source_facts$
DECLARE
  xact bigint;
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM sync_capture_control WHERE singleton = 1 AND enabled
  ) THEN
    RETURN NULL;
  END IF;
  xact := pg_current_xact_id()::text::bigint;
  IF TG_OP = 'DELETE' THEN
    INSERT INTO sync_change_log (table_name, key_json, operation, parent_key, notebook_id, txid, changed_at)
    VALUES ('knowledge_source_facts', jsonb_build_object('id', OLD."id"), 'delete',
            NULL, OLD."notebook_id", xact, now());
    RETURN NULL;
  END IF;
  IF TG_OP = 'UPDATE' THEN
    IF OLD."id" IS DISTINCT FROM NEW."id" THEN
      INSERT INTO sync_change_log (table_name, key_json, operation, parent_key, notebook_id, txid, changed_at)
      VALUES ('knowledge_source_facts', jsonb_build_object('id', OLD."id"), 'delete',
              NULL, OLD."notebook_id", xact, now());
    END IF;
  END IF;
  INSERT INTO sync_change_log (table_name, key_json, operation, parent_key, notebook_id, txid, changed_at)
  VALUES ('knowledge_source_facts', jsonb_build_object('id', NEW."id"), 'upsert',
          NULL, NEW."notebook_id", xact, now());
  RETURN NULL;
END;
$sync_capture_knowledge_source_facts$;
CREATE TRIGGER sync_capture_knowledge_source_facts AFTER INSERT OR DELETE OR UPDATE ON knowledge_source_facts FOR EACH ROW EXECUTE FUNCTION sync_capture_knowledge_source_facts();

CREATE FUNCTION sync_capture_knowledge_source_fact_elements() RETURNS trigger
LANGUAGE plpgsql AS $sync_capture_knowledge_source_fact_elements$
DECLARE
  xact bigint;
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM sync_capture_control WHERE singleton = 1 AND enabled
  ) THEN
    RETURN NULL;
  END IF;
  xact := pg_current_xact_id()::text::bigint;
  IF TG_OP = 'DELETE' THEN
    INSERT INTO sync_change_log (table_name, key_json, operation, parent_key, notebook_id, txid, changed_at)
    VALUES ('knowledge_source_fact_elements', jsonb_build_object('fact_id', OLD."fact_id", 'element_id', OLD."element_id"), 'delete',
            NULL, OLD."notebook_id", xact, now());
    RETURN NULL;
  END IF;
  IF TG_OP = 'UPDATE' THEN
    IF OLD."fact_id" IS DISTINCT FROM NEW."fact_id"
       OR OLD."element_id" IS DISTINCT FROM NEW."element_id" THEN
      INSERT INTO sync_change_log (table_name, key_json, operation, parent_key, notebook_id, txid, changed_at)
      VALUES ('knowledge_source_fact_elements', jsonb_build_object('fact_id', OLD."fact_id", 'element_id', OLD."element_id"), 'delete',
              NULL, OLD."notebook_id", xact, now());
    END IF;
  END IF;
  INSERT INTO sync_change_log (table_name, key_json, operation, parent_key, notebook_id, txid, changed_at)
  VALUES ('knowledge_source_fact_elements', jsonb_build_object('fact_id', NEW."fact_id", 'element_id', NEW."element_id"), 'upsert',
          NULL, NEW."notebook_id", xact, now());
  RETURN NULL;
END;
$sync_capture_knowledge_source_fact_elements$;
CREATE TRIGGER sync_capture_knowledge_source_fact_elements AFTER INSERT OR DELETE OR UPDATE ON knowledge_source_fact_elements FOR EACH ROW EXECUTE FUNCTION sync_capture_knowledge_source_fact_elements();

CREATE FUNCTION sync_capture_chunk_questions() RETURNS trigger
LANGUAGE plpgsql AS $sync_capture_chunk_questions$
DECLARE
  xact bigint;
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM sync_capture_control WHERE singleton = 1 AND enabled
  ) THEN
    RETURN NULL;
  END IF;
  xact := pg_current_xact_id()::text::bigint;
  IF TG_OP = 'DELETE' THEN
    INSERT INTO sync_change_log (table_name, key_json, operation, parent_key, notebook_id, txid, changed_at)
    VALUES ('chunk_questions', jsonb_build_object('id', OLD."id"), 'delete',
            NULL, OLD."notebook_id", xact, now());
    RETURN NULL;
  END IF;
  IF TG_OP = 'UPDATE' THEN
    IF OLD."id" IS DISTINCT FROM NEW."id" THEN
      INSERT INTO sync_change_log (table_name, key_json, operation, parent_key, notebook_id, txid, changed_at)
      VALUES ('chunk_questions', jsonb_build_object('id', OLD."id"), 'delete',
              NULL, OLD."notebook_id", xact, now());
    END IF;
  END IF;
  INSERT INTO sync_change_log (table_name, key_json, operation, parent_key, notebook_id, txid, changed_at)
  VALUES ('chunk_questions', jsonb_build_object('id', NEW."id"), 'upsert',
          NULL, NEW."notebook_id", xact, now());
  RETURN NULL;
END;
$sync_capture_chunk_questions$;
CREATE TRIGGER sync_capture_chunk_questions AFTER INSERT OR DELETE OR UPDATE ON chunk_questions FOR EACH ROW EXECUTE FUNCTION sync_capture_chunk_questions();

CREATE FUNCTION sync_capture_chunk_elements() RETURNS trigger
LANGUAGE plpgsql AS $sync_capture_chunk_elements$
DECLARE
  xact bigint;
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM sync_capture_control WHERE singleton = 1 AND enabled
  ) THEN
    RETURN NULL;
  END IF;
  xact := pg_current_xact_id()::text::bigint;
  IF TG_OP = 'DELETE' THEN
    INSERT INTO sync_change_log (table_name, key_json, operation, parent_key, notebook_id, txid, changed_at)
    VALUES ('chunk_elements', jsonb_build_object('notebook_id', OLD."notebook_id", 'element_id', OLD."element_id", 'chunk_id', OLD."chunk_id"), 'delete',
            NULL, OLD."notebook_id", xact, now());
    RETURN NULL;
  END IF;
  IF TG_OP = 'UPDATE' THEN
    IF OLD."notebook_id" IS DISTINCT FROM NEW."notebook_id"
       OR OLD."element_id" IS DISTINCT FROM NEW."element_id"
       OR OLD."chunk_id" IS DISTINCT FROM NEW."chunk_id" THEN
      INSERT INTO sync_change_log (table_name, key_json, operation, parent_key, notebook_id, txid, changed_at)
      VALUES ('chunk_elements', jsonb_build_object('notebook_id', OLD."notebook_id", 'element_id', OLD."element_id", 'chunk_id', OLD."chunk_id"), 'delete',
              NULL, OLD."notebook_id", xact, now());
    END IF;
  END IF;
  INSERT INTO sync_change_log (table_name, key_json, operation, parent_key, notebook_id, txid, changed_at)
  VALUES ('chunk_elements', jsonb_build_object('notebook_id', NEW."notebook_id", 'element_id', NEW."element_id", 'chunk_id', NEW."chunk_id"), 'upsert',
          NULL, NEW."notebook_id", xact, now());
  RETURN NULL;
END;
$sync_capture_chunk_elements$;
CREATE TRIGGER sync_capture_chunk_elements AFTER INSERT OR DELETE OR UPDATE ON chunk_elements FOR EACH ROW EXECUTE FUNCTION sync_capture_chunk_elements();

CREATE FUNCTION sync_capture_notebook_object_schemas() RETURNS trigger
LANGUAGE plpgsql AS $sync_capture_notebook_object_schemas$
DECLARE
  xact bigint;
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM sync_capture_control WHERE singleton = 1 AND enabled
  ) THEN
    RETURN NULL;
  END IF;
  xact := pg_current_xact_id()::text::bigint;
  IF TG_OP = 'DELETE' THEN
    INSERT INTO sync_change_log (table_name, key_json, operation, parent_key, notebook_id, txid, changed_at)
    VALUES ('notebook_object_schemas', jsonb_build_object('notebook_id', OLD."notebook_id", 'object_type', OLD."object_type"), 'delete',
            NULL, OLD."notebook_id", xact, now());
    RETURN NULL;
  END IF;
  IF TG_OP = 'UPDATE' THEN
    IF OLD."notebook_id" IS DISTINCT FROM NEW."notebook_id"
       OR OLD."object_type" IS DISTINCT FROM NEW."object_type" THEN
      INSERT INTO sync_change_log (table_name, key_json, operation, parent_key, notebook_id, txid, changed_at)
      VALUES ('notebook_object_schemas', jsonb_build_object('notebook_id', OLD."notebook_id", 'object_type', OLD."object_type"), 'delete',
              NULL, OLD."notebook_id", xact, now());
    END IF;
  END IF;
  INSERT INTO sync_change_log (table_name, key_json, operation, parent_key, notebook_id, txid, changed_at)
  VALUES ('notebook_object_schemas', jsonb_build_object('notebook_id', NEW."notebook_id", 'object_type', NEW."object_type"), 'upsert',
          NULL, NEW."notebook_id", xact, now());
  RETURN NULL;
END;
$sync_capture_notebook_object_schemas$;
CREATE TRIGGER sync_capture_notebook_object_schemas AFTER INSERT OR DELETE OR UPDATE ON notebook_object_schemas FOR EACH ROW EXECUTE FUNCTION sync_capture_notebook_object_schemas();

CREATE FUNCTION sync_capture_groups() RETURNS trigger
LANGUAGE plpgsql AS $sync_capture_groups$
DECLARE
  xact bigint;
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM sync_capture_control WHERE singleton = 1 AND enabled
  ) THEN
    RETURN NULL;
  END IF;
  xact := pg_current_xact_id()::text::bigint;
  IF TG_OP = 'DELETE' THEN
    INSERT INTO sync_change_log (table_name, key_json, operation, parent_key, notebook_id, txid, changed_at)
    VALUES ('groups', jsonb_build_object('id', OLD."id"), 'delete',
            NULL, NULL, xact, now());
    RETURN NULL;
  END IF;
  IF TG_OP = 'UPDATE' THEN
    IF OLD."id" IS DISTINCT FROM NEW."id" THEN
      INSERT INTO sync_change_log (table_name, key_json, operation, parent_key, notebook_id, txid, changed_at)
      VALUES ('groups', jsonb_build_object('id', OLD."id"), 'delete',
              NULL, NULL, xact, now());
    END IF;
  END IF;
  INSERT INTO sync_change_log (table_name, key_json, operation, parent_key, notebook_id, txid, changed_at)
  VALUES ('groups', jsonb_build_object('id', NEW."id"), 'upsert',
          NULL, NULL, xact, now());
  RETURN NULL;
END;
$sync_capture_groups$;
CREATE TRIGGER sync_capture_groups AFTER INSERT OR DELETE OR UPDATE ON groups FOR EACH ROW EXECUTE FUNCTION sync_capture_groups();

CREATE FUNCTION sync_capture_group_members() RETURNS trigger
LANGUAGE plpgsql AS $sync_capture_group_members$
DECLARE
  xact bigint;
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM sync_capture_control WHERE singleton = 1 AND enabled
  ) THEN
    RETURN NULL;
  END IF;
  xact := pg_current_xact_id()::text::bigint;
  IF TG_OP = 'DELETE' THEN
    INSERT INTO sync_change_log (table_name, key_json, operation, parent_key, notebook_id, txid, changed_at)
    VALUES ('group_members', jsonb_build_object('group_id', OLD."group_id", 'user_id', OLD."user_id"), 'delete',
            NULL, NULL, xact, now());
    RETURN NULL;
  END IF;
  IF TG_OP = 'UPDATE' THEN
    IF OLD."group_id" IS DISTINCT FROM NEW."group_id"
       OR OLD."user_id" IS DISTINCT FROM NEW."user_id" THEN
      INSERT INTO sync_change_log (table_name, key_json, operation, parent_key, notebook_id, txid, changed_at)
      VALUES ('group_members', jsonb_build_object('group_id', OLD."group_id", 'user_id', OLD."user_id"), 'delete',
              NULL, NULL, xact, now());
    END IF;
  END IF;
  INSERT INTO sync_change_log (table_name, key_json, operation, parent_key, notebook_id, txid, changed_at)
  VALUES ('group_members', jsonb_build_object('group_id', NEW."group_id", 'user_id', NEW."user_id"), 'upsert',
          NULL, NULL, xact, now());
  RETURN NULL;
END;
$sync_capture_group_members$;
CREATE TRIGGER sync_capture_group_members AFTER INSERT OR DELETE OR UPDATE ON group_members FOR EACH ROW EXECUTE FUNCTION sync_capture_group_members();

CREATE FUNCTION sync_capture_notebook_grants() RETURNS trigger
LANGUAGE plpgsql AS $sync_capture_notebook_grants$
DECLARE
  xact bigint;
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM sync_capture_control WHERE singleton = 1 AND enabled
  ) THEN
    RETURN NULL;
  END IF;
  xact := pg_current_xact_id()::text::bigint;
  IF TG_OP = 'DELETE' THEN
    INSERT INTO sync_change_log (table_name, key_json, operation, parent_key, notebook_id, txid, changed_at)
    VALUES ('notebook_grants', jsonb_build_object('id', OLD."id"), 'delete',
            NULL, OLD."notebook_id", xact, now());
    RETURN NULL;
  END IF;
  IF TG_OP = 'UPDATE' THEN
    IF OLD."id" IS DISTINCT FROM NEW."id" THEN
      INSERT INTO sync_change_log (table_name, key_json, operation, parent_key, notebook_id, txid, changed_at)
      VALUES ('notebook_grants', jsonb_build_object('id', OLD."id"), 'delete',
              NULL, OLD."notebook_id", xact, now());
    END IF;
  END IF;
  INSERT INTO sync_change_log (table_name, key_json, operation, parent_key, notebook_id, txid, changed_at)
  VALUES ('notebook_grants', jsonb_build_object('id', NEW."id"), 'upsert',
          NULL, NEW."notebook_id", xact, now());
  RETURN NULL;
END;
$sync_capture_notebook_grants$;
CREATE TRIGGER sync_capture_notebook_grants AFTER INSERT OR DELETE OR UPDATE ON notebook_grants FOR EACH ROW EXECUTE FUNCTION sync_capture_notebook_grants();
