import test from "node:test";
import assert from "node:assert/strict";
import { existsSync } from "node:fs";
import { mkdir, mkdtemp, readdir, readFile, rm, symlink, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import path from "node:path";
import { fileURLToPath } from "node:url";

import {
  inspectPackage,
  mergeContractRows,
  parsePluginRoots,
  renderLocalRegistry,
  syncUiPlugins,
  validateManifest,
} from "../../scripts/sync-ui-plugins.mjs";


const REPO_DIR = path.resolve(
  path.dirname(fileURLToPath(import.meta.url)),
  "../../..",
);
const BUILTIN_ROW = Object.freeze({
  plugin_id: "builtin.demo_panel",
  version: "1.0.0",
  contribution_id: "builtin.demo_panel.workspace_panel",
  slot: "workspace.side_panel",
  capability: "ui.demo_panel.available",
});
const EMPTY_REGISTRY = [
  "// GENERATED by frontend/scripts/sync-ui-plugins.mjs — do not edit, do not commit.",
  "// source: SILICON_NOTEBOOK_UI_PLUGINS=<unset>",
  "import type { WorkspaceUiContribution } from \"./contracts.ts\";",
  "",
  "export const LOCAL_WORKSPACE_UI_CONTRIBUTIONS: readonly WorkspaceUiContribution[] = [];",
  "",
].join("\n");


async function makeWorkspace(t) {
  const root = await mkdtemp(path.join(tmpdir(), "sync-ui-plugins-"));
  t.after(() => rm(root, { recursive: true, force: true }));
  const frontendDir = path.join(root, "frontend");
  await mkdir(path.join(frontendDir, "features", "extension-sdk"), { recursive: true });
  await mkdir(path.join(root, "backend", "tests", "fixtures"), { recursive: true });
  await writeFile(
    path.join(root, "backend", "tests", "fixtures", "ui_extension_contract.json"),
    `${JSON.stringify({ api_version: "1", contributions: [BUILTIN_ROW] }, null, 2)}\n`,
    "utf8",
  );
  return { root, frontendDir };
}


function manifestFor(pluginId, overrides = {}) {
  return {
    api_version: "1",
    contributions: [{
      id: `${pluginId}.search.workspace_panel`,
      plugin_id: pluginId,
      version: "1.0.0",
      capability: `ui.${pluginId}.search`,
      slot: "workspace.side_panel",
      permission: "notebook:write",
      mode: "all",
      component: "SearchEntry",
      ...overrides,
    }],
  };
}


async function writePackage(root, name, options = {}) {
  const {
    manifest = manifestFor(name),
    entry = "workspace-plugin.tsx",
    extras = {},
    directories = [],
  } = options;
  const directory = path.join(root, "packages", name);
  await mkdir(directory, { recursive: true });
  await writeFile(
    path.join(directory, "ui-plugin.json"),
    `${JSON.stringify(manifest, null, 2)}\n`,
    "utf8",
  );
  await writeFile(
    path.join(directory, entry),
    "export const SearchEntry = () => null;\n",
    "utf8",
  );
  for (const [name_, body] of Object.entries(extras)) {
    await writeFile(path.join(directory, name_), body, "utf8");
  }
  for (const child of directories) {
    await mkdir(path.join(directory, child), { recursive: true });
  }
  return directory;
}


function registryPath(frontendDir) {
  return path.join(frontendDir, "features", "extension-sdk", "registry.local.ts");
}


function contractPath(frontendDir) {
  return path.join(frontendDir, ".local", "ui-extension-contract.json");
}


test("plugin roots are colon separated, trimmed, and resolved against the caller's directory", () => {
  assert.deepEqual(parsePluginRoots("", "/work"), []);
  assert.deepEqual(parsePluginRoots(undefined, "/work"), []);
  assert.deepEqual(parsePluginRoots("::", "/work"), []);
  assert.deepEqual(
    parsePluginRoots("/srv/plugins/one: ./two :", "/work"),
    ["/srv/plugins/one", "/work/two"],
  );
});


test("a deployment with no plugins still gets the empty stub and the built-in-only contract", async (t) => {
  const { frontendDir } = await makeWorkspace(t);

  const result = await syncUiPlugins({ frontendDir, roots: [] });

  assert.deepEqual(result.packages, []);
  assert.deepEqual(result.rows, [BUILTIN_ROW]);
  assert.equal(await readFile(registryPath(frontendDir), "utf8"), EMPTY_REGISTRY);
  assert.deepEqual(
    JSON.parse(await readFile(contractPath(frontendDir), "utf8")),
    { api_version: "1", contributions: [BUILTIN_ROW] },
  );
});


test("the copied package carries only TypeScript, the manifest, and the origin marker", async (t) => {
  const { root, frontendDir } = await makeWorkspace(t);
  const directory = await writePackage(root, "ieee-xplore", {
    manifest: manifestFor("ieee-xplore", { component: "IeeeSearchEntry" }),
    extras: { "ieee-model.ts": "export const KIND = \"paper\";\n" },
  });

  const result = await syncUiPlugins({ frontendDir, roots: [directory] });

  assert.deepEqual(result.packages.map((row) => row.name), ["ieee-xplore"]);
  const copied = await readdir(path.join(frontendDir, "features", "ext-ieee-xplore"));
  assert.deepEqual(copied.sort(), [
    ".ui-plugin-origin",
    "ieee-model.ts",
    "ui-plugin.json",
    "workspace-plugin.tsx",
  ]);
  const expectedRows = mergeContractRows([BUILTIN_ROW], [{
    plugin_id: "ieee-xplore",
    version: "1.0.0",
    contribution_id: "ieee-xplore.search.workspace_panel",
    slot: "workspace.side_panel",
    capability: "ui.ieee-xplore.search",
  }]);
  assert.deepEqual(result.rows, expectedRows);
  // 返回值不是产物：部署期对账读的是磁盘上那份文件，所以插件行必须在**文件里**
  // 被见证。只断言 `result.rows` 时，把写入换成 `renderContract(builtinRows, [])`
  // 全套用例照样绿。
  assert.deepEqual(
    JSON.parse(await readFile(contractPath(frontendDir), "utf8")),
    { api_version: "1", contributions: expectedRows },
  );
});


test("a package with a subdirectory, a package.json, or a stylesheet aborts the whole sync", async (t) => {
  const { root, frontendDir } = await makeWorkspace(t);
  const nested = await writePackage(root, "with-modules", { directories: ["node_modules"] });
  const dependent = await writePackage(root, "with-manifest", {
    extras: { "package.json": "{}\n" },
  });
  const styled = await writePackage(root, "with-styles", {
    extras: { "styles.css": ".x { color: red; }\n" },
  });

  await assert.rejects(
    syncUiPlugins({ frontendDir, roots: [nested] }),
    /subdirectory "node_modules" is not allowed/,
  );
  await assert.rejects(
    syncUiPlugins({ frontendDir, roots: [dependent] }),
    /"package\.json" is not an allowed package file/,
  );
  await assert.rejects(
    syncUiPlugins({ frontendDir, roots: [styled] }),
    /"styles\.css" is not an allowed package file/,
  );
  // 校验在动文件树之前跑完，所以一次被拒的同步不留任何产物。`assert.rejects` 对
  // 一个已存在但内容意外的文件同样会通过（读成功就不 reject）——要断言的是「不存在」。
  assert.equal(existsSync(registryPath(frontendDir)), false);
});


test("a package directory named like a generated copy, or claimed twice, is refused", async (t) => {
  const { root, frontendDir } = await makeWorkspace(t);
  const reserved = await writePackage(root, "ext-shadow");
  await assert.rejects(
    inspectPackage(reserved),
    /package directory name is invalid/,
  );

  const first = await writePackage(path.join(root, "left"), "ieee-xplore");
  const second = await writePackage(path.join(root, "right"), "ieee-xplore");
  await assert.rejects(
    syncUiPlugins({ frontendDir, roots: [first, second] }),
    /package name is not unique/,
  );
});


test("manifest fields are checked against the same rules the built-in registry enforces", () => {
  for (const [overrides, pattern] of [
    [{ slot: "side_panel" }, /"slot"/],
    [{ plugin_id: "Ieee" }, /"plugin_id"/],
    [{ mode: "expert" }, /"mode"/],
    [{ permission: "notebook:everything" }, /"permission"/],
    [{ capability: "UI.Search" }, /"capability"/],
    [{ component: "searchEntry" }, /"component"/],
    [{ version: "" }, /"version"/],
  ]) {
    assert.throws(
      () => validateManifest(manifestFor("ieee", overrides), "ieee"),
      pattern,
    );
  }

  const withoutComponent = manifestFor("ieee");
  delete withoutComponent.contributions[0].component;
  assert.throws(() => validateManifest(withoutComponent, "ieee"), /"component"/);

  assert.throws(
    () => validateManifest({ api_version: "2", contributions: [] }, "ieee"),
    /"api_version"/,
  );
  assert.throws(
    () => validateManifest({ api_version: "1", contributions: [] }, "ieee"),
    /"contributions"/,
  );
  assert.deepEqual(validateManifest(manifestFor("ieee"), "ieee"), [{
    plugin_id: "ieee",
    version: "1.0.0",
    contribution_id: "ieee.search.workspace_panel",
    slot: "workspace.side_panel",
    capability: "ui.ieee.search",
  }]);
});


test("the generated registry pairs one import with each entry in a deterministic order", async (t) => {
  const { root, frontendDir } = await makeWorkspace(t);
  const alpha = await writePackage(root, "alpha", {
    manifest: manifestFor("alpha", { component: "AlphaEntry" }),
  });
  const beta = await writePackage(root, "beta", {
    manifest: manifestFor("beta", { component: "BetaEntry" }),
    entry: "workspace-plugin.ts",
  });

  // 刻意按逆字典序传入：产物必须只由包名决定，不由环境变量的书写顺序决定。
  await syncUiPlugins({ frontendDir, roots: [beta, alpha] });

  assert.equal(await readFile(registryPath(frontendDir), "utf8"), [
    "// GENERATED by frontend/scripts/sync-ui-plugins.mjs — do not edit, do not commit.",
    "// source: SILICON_NOTEBOOK_UI_PLUGINS=<2 package(s): alpha, beta>",
    "import type { WorkspaceUiContribution } from \"./contracts.ts\";",
    "import { AlphaEntry as ext_alpha__AlphaEntry } from \"../ext-alpha/workspace-plugin.tsx\";",
    "import { BetaEntry as ext_beta__BetaEntry } from \"../ext-beta/workspace-plugin.ts\";",
    "",
    "export const LOCAL_WORKSPACE_UI_CONTRIBUTIONS: readonly WorkspaceUiContribution[] = [",
    "  {",
    "    id: \"alpha.search.workspace_panel\",",
    "    pluginId: \"alpha\",",
    "    pluginVersion: \"1.0.0\",",
    "    capability: \"ui.alpha.search\",",
    "    slot: \"workspace.side_panel\",",
    "    permission: \"notebook:write\",",
    "    mode: \"all\",",
    "    Component: ext_alpha__AlphaEntry,",
    "  },",
    "  {",
    "    id: \"beta.search.workspace_panel\",",
    "    pluginId: \"beta\",",
    "    pluginVersion: \"1.0.0\",",
    "    capability: \"ui.beta.search\",",
    "    slot: \"workspace.side_panel\",",
    "    permission: \"notebook:write\",",
    "    mode: \"all\",",
    "    Component: ext_beta__BetaEntry,",
    "  },",
    "];",
    "",
  ].join("\n"));
  assert.equal(renderLocalRegistry([]), EMPTY_REGISTRY);
});


test("a second sync is idempotent, and dropping the variable removes the stale copies", async (t) => {
  const { root, frontendDir } = await makeWorkspace(t);
  const alpha = await writePackage(root, "alpha", {
    manifest: manifestFor("alpha", { component: "AlphaEntry" }),
  });

  await syncUiPlugins({ frontendDir, roots: [alpha] });
  const firstRegistry = await readFile(registryPath(frontendDir), "utf8");
  const firstListing = (await readdir(path.join(frontendDir, "features", "ext-alpha"))).sort();

  await syncUiPlugins({ frontendDir, roots: [alpha] });
  assert.equal(await readFile(registryPath(frontendDir), "utf8"), firstRegistry);
  assert.deepEqual(
    (await readdir(path.join(frontendDir, "features", "ext-alpha"))).sort(),
    firstListing,
  );

  await syncUiPlugins({ frontendDir, roots: [] });
  assert.deepEqual(
    (await readdir(path.join(frontendDir, "features"))).sort(),
    ["extension-sdk"],
  );
  assert.equal(await readFile(registryPath(frontendDir), "utf8"), EMPTY_REGISTRY);
});


test("a hand-written features/ext-* directory without the marker is refused, not deleted", async (t) => {
  const { root, frontendDir } = await makeWorkspace(t);
  const alpha = await writePackage(root, "alpha", {
    manifest: manifestFor("alpha", { component: "AlphaEntry" }),
  });
  await syncUiPlugins({ frontendDir, roots: [alpha] });
  const registryBefore = await readFile(registryPath(frontendDir), "utf8");

  // `ext-zzz-…` 排在 `ext-alpha` 之后：勘察若与删除交错，抛错时 alpha 已经没了，
  // 而 registry.local.ts 还指着它——之后每次 build 都红且不自愈。
  const handWritten = path.join(frontendDir, "features", "ext-zzz-handwritten");
  await mkdir(handWritten, { recursive: true });
  await writeFile(
    path.join(handWritten, "workspace-plugin.ts"),
    "export const Entry = () => null;\n",
    "utf8",
  );

  await assert.rejects(
    syncUiPlugins({ frontendDir, roots: [alpha] }),
    /carries no \.ui-plugin-origin marker/,
  );
  assert.deepEqual(await readdir(handWritten), ["workspace-plugin.ts"]);
  assert.equal(existsSync(path.join(frontendDir, "features", "ext-alpha")), true);
  assert.equal(await readFile(registryPath(frontendDir), "utf8"), registryBefore);
});


test("a features/ext-* symlink is refused instead of being written through", async (t) => {
  const { root, frontendDir } = await makeWorkspace(t);
  const sdkDir = path.join(frontendDir, "features", "extension-sdk");
  const victim = path.join(sdkDir, "contracts.ts");
  const original = "export type WorkspaceUiContribution = never;\n";
  await writeFile(victim, original, "utf8");
  // 包里带一个与 SDK 同名的文件：`ext-alpha` 是软链时，跳过删除再 mkdir+copyFile
  // 会顺着它把受版本控制的 SDK 源码整个覆盖掉。
  const alpha = await writePackage(root, "alpha", {
    manifest: manifestFor("alpha", { component: "AlphaEntry" }),
    extras: { "contracts.ts": "export const HIJACKED = true;\n" },
  });
  await symlink(sdkDir, path.join(frontendDir, "features", "ext-alpha"), "dir");

  await assert.rejects(
    syncUiPlugins({ frontendDir, roots: [alpha] }),
    /is not a real directory/,
  );
  assert.equal(await readFile(victim, "utf8"), original);
  assert.equal(existsSync(path.join(sdkDir, "ui-plugin.json")), false);
  assert.equal(existsSync(path.join(sdkDir, ".ui-plugin-origin")), false);
  assert.equal(existsSync(registryPath(frontendDir)), false);
});


test("a rejected sync leaves the previous copies, registry and contract byte-for-byte intact", async (t) => {
  const { root, frontendDir } = await makeWorkspace(t);
  const alpha = await writePackage(root, "alpha", {
    manifest: manifestFor("alpha", { component: "AlphaEntry" }),
  });
  const copiedEntry = path.join(frontendDir, "features", "ext-alpha", "workspace-plugin.tsx");

  await syncUiPlugins({ frontendDir, roots: [alpha] });
  const registryBefore = await readFile(registryPath(frontendDir), "utf8");
  const contractBefore = await readFile(contractPath(frontendDir), "utf8");
  const copyBefore = await readFile(copiedEntry, "utf8");

  // ① 一个不合法的输入包：全部校验都在删除之前跑完，A 的副本一个字节都不能变。
  const broken = await writePackage(root, "broken", { extras: { "styles.css": ".x {}\n" } });
  await assert.rejects(
    syncUiPlugins({ frontendDir, roots: [alpha, broken] }),
    /"styles\.css" is not an allowed package file/,
  );
  assert.equal(await readFile(registryPath(frontendDir), "utf8"), registryBefore);
  assert.equal(await readFile(copiedEntry, "utf8"), copyBefore);

  // ② 内建契约 fixture 读不到也必须在勘察阶段就发现：把它留到最后一步会先删掉旧
  //    副本、写完空 registry，再抛错，留下一棵和契约文件互相矛盾的树。
  await rm(path.join(root, "backend", "tests", "fixtures", "ui_extension_contract.json"));
  await assert.rejects(
    syncUiPlugins({ frontendDir, roots: [] }),
    /built-in UI extension contract fixture is missing/,
  );
  assert.equal(await readFile(registryPath(frontendDir), "utf8"), registryBefore);
  assert.equal(await readFile(contractPath(frontendDir), "utf8"), contractBefore);
  assert.equal(await readFile(copiedEntry, "utf8"), copyBefore);
});


test("two packages exporting the same component name get distinct import bindings", async (t) => {
  const { root, frontendDir } = await makeWorkspace(t);
  // 两个包的 manifest 都指名 `SearchEntry`：裸名字会让生成文件出现两条同名 import，
  // `tsc` 报重复标识符、整个前端构建挂在一份「do not edit」的文件上。
  const alpha = await writePackage(root, "alpha");
  const beta = await writePackage(root, "beta");

  await syncUiPlugins({ frontendDir, roots: [alpha, beta] });

  const rendered = await readFile(registryPath(frontendDir), "utf8");
  const imported = [...rendered.matchAll(/^import \{ (.+) \} from "\.\.\/ext-/gm)]
    .map((hit) => hit[1]);
  assert.deepEqual(imported, [
    "SearchEntry as ext_alpha__SearchEntry",
    "SearchEntry as ext_beta__SearchEntry",
  ]);
  assert.ok(rendered.includes("    Component: ext_alpha__SearchEntry,"));
  assert.ok(rendered.includes("    Component: ext_beta__SearchEntry,"));
  const bound = imported.map((clause) => clause.split(" as ").at(-1));
  assert.equal(new Set(bound).size, bound.length, "every binding must be declared once");
});


test("dotfiles in the package root are skipped, while subdirectories stay refused", async (t) => {
  const { root, frontendDir } = await makeWorkspace(t);
  const directory = await writePackage(root, "alpha", {
    manifest: manifestFor("alpha", { component: "AlphaEntry" }),
    extras: { ".DS_Store": "junk\n", ".gitignore": "node_modules\n" },
  });

  const inspected = await inspectPackage(directory);
  assert.deepEqual(inspected.skipped, [".DS_Store", ".gitignore"]);
  assert.deepEqual(inspected.files, ["ui-plugin.json", "workspace-plugin.tsx"]);

  await syncUiPlugins({ frontendDir, roots: [directory] });
  assert.deepEqual(
    (await readdir(path.join(frontendDir, "features", "ext-alpha"))).sort(),
    [".ui-plugin-origin", "ui-plugin.json", "workspace-plugin.tsx"],
  );

  // 子目录仍一律拒绝，`.git` 也不例外——它会被 next build 的类型检查连同 worktree
  // 里的一切一起吞进去，和 `node_modules/` 同类。
  const dotted = await writePackage(root, "dotted", { directories: [".git"] });
  await assert.rejects(
    syncUiPlugins({ frontendDir, roots: [dotted] }),
    /subdirectory "\.git" is not allowed/,
  );
});


test("the contract sort key is the one the backend generator uses", async () => {
  const generatorModule = await readFile(
    path.join(REPO_DIR, "scripts", "generate_ui_extension_contract.py"),
    "utf8",
  );
  const declared = generatorModule.match(/_CONTRIBUTION_SORT_FIELDS = \(([^)]*)\)/);
  assert.ok(declared, "backend generator must declare _CONTRIBUTION_SORT_FIELDS");
  const backendFields = [...declared[1].matchAll(/"([a-z_]+)"/g)].map((hit) => hit[1]);
  assert.deepEqual(
    backendFields,
    ["plugin_id", "version", "contribution_id", "slot", "capability"],
  );

  // 每个字段单独造一次并列，证明比较确实按声明顺序逐级下推。
  function rowWith(overrides) {
    return {
      plugin_id: "m",
      version: "m",
      contribution_id: "m",
      slot: "m",
      capability: "m",
      ...overrides,
    };
  }
  for (const field of backendFields) {
    const low = rowWith({ [field]: "a" });
    const high = rowWith({ [field]: "z" });
    assert.deepEqual(mergeContractRows([high], [low]), [low, high], field);
  }
  const earlier = rowWith({ plugin_id: "a", capability: "z" });
  const later = rowWith({ plugin_id: "z", capability: "a" });
  assert.deepEqual(mergeContractRows([later], [earlier]), [earlier, later]);
});
