"""Narrow authentication persistence surface, separate from the legacy facade."""
from __future__ import annotations

from typing import Literal, Protocol, TypedDict

from app.domain.auth_provider import ExternalIdentity
from app.models.identity import UserProfile


class AuthGrantPreview(TypedDict):
    status: Literal["confirmation_required"]
    pending_id: str
    purpose: Literal["enroll", "recover", "replace"]
    external_username: str
    display_name: str
    previous_external_username: str | None
    target_user_id: str | None
    target_username: str | None


class AuthStorePort(Protocol):
    def get_policy(self) -> dict: ...
    def resolve_session(self, token: str, *, migration_only: bool = False) -> UserProfile | None: ...
    def owner_eligible(self, user_id: str) -> bool: ...
    def identities(self, user_id: str) -> dict: ...
    def begin(
        self, purpose: str, browser_proof: str, *, ttl_seconds: int,
        session_token: str = "", password: str = "", pkce_verifier: str = "",
        grant_token: str = "",
    ) -> str: ...
    def claim(self, state: str, browser_proof: str) -> dict: ...
    def stage_identity(
        self, transaction: dict, identity: ExternalIdentity, browser_proof: str,
        *, ttl_seconds: int,
    ) -> str: ...
    def inspect_completion(
        self, token: str, browser_proof: str, *, session_seconds: int,
    ) -> dict: ...
    def confirm(
        self, token: str, browser_proof: str, *, session_token: str = "",
        session_seconds: int,
    ) -> tuple[UserProfile, str]: ...
    def cancel(self, pending_id: str, browser_proof: str, *, session_token: str) -> None: ...
    def cancel_for_session(self, session_token: str) -> None: ...
    def cancel_for_browser(self, browser_proof: str) -> None: ...
    def preflight(self) -> dict: ...
    def inventory_page(self, *, offset: int, limit: int) -> dict: ...
    def audit_page(self, *, offset: int, limit: int) -> dict: ...
    def set_policy(
        self, mode: str, *, actor_id: str, expected_revision: int,
        provider_id: str = "", provider_namespace: str = "",
        config_generation: str = "", plugin_id: str = "",
        allow_rollback: bool = False,
    ) -> dict: ...
    def prepare_provider_configuration(
        self, *, expected_revision: int, actor_id: str, plugin_id: str,
        provider_id: str, provider_namespace: str, config_generation: str,
    ) -> dict: ...
    def issue_grant(
        self, purpose: str, subject: str, *, actor_id: str, ttl_seconds: int,
        target_user_id: str = "",
    ) -> str: ...
    def set_account_status(self, user_id: str, status: str, *, actor_id: str) -> None: ...
    def retirement_cleanup(self) -> None: ...
