"""Narrow authentication persistence surface, separate from the legacy facade."""
from __future__ import annotations

from typing import Protocol

from app.domain.auth_provider import AuthProviderHostPort, ExternalIdentity
from app.models.identity import UserProfile


class AuthStorePort(Protocol):
    def use_provider(self, host: AuthProviderHostPort) -> None: ...
    def sso_namespace(self) -> str: ...
    def resolve_session(self, token: str) -> UserProfile | None: ...
    def owner_eligible(self, user_id: str) -> bool: ...
    def begin(self, browser_proof: str, *, ttl_seconds: int, pkce_verifier: str = "") -> str: ...
    def claim(self, state: str, browser_proof: str) -> dict: ...
    def stage_identity(
        self, transaction: dict, identity: ExternalIdentity, browser_proof: str,
        *, ttl_seconds: int,
    ) -> str: ...
    def complete(self, code: str, browser_proof: str, *, session_seconds: int) -> dict: ...
    def link(
        self, pending_id: str, browser_proof: str, login_name: str, password: str,
        *, session_seconds: int,
    ) -> tuple[UserProfile, str]: ...
    def create(
        self, pending_id: str, browser_proof: str, *, session_seconds: int,
    ) -> tuple[UserProfile, str]: ...
    def cancel(self, pending_id: str, browser_proof: str) -> None: ...
    def cancel_for_browser(self, browser_proof: str) -> None: ...
    def set_account_status(self, user_id: str, status: str, *, actor_id: str) -> dict: ...
    def set_username(self, user_id: str, username: str, *, actor_id: str) -> dict: ...
