"""Persistence contract for independent global question-answer sessions."""
from typing import Protocol

from app.models.global_ask import GlobalAskJob, GlobalConversationSummary


class GlobalAskStorePort(Protocol):
    def conversation(self, conversation_id: str, user_id: str) -> GlobalConversationSummary | None: ...
    def list_conversations(self, user_id: str, limit: int, offset: int) -> list[GlobalConversationSummary]: ...
    def job(self, job_id: str, user_id: str) -> GlobalAskJob | None: ...
    def request_job(self, user_id: str, request_id: str | None) -> tuple[GlobalAskJob, str] | None: ...
    def create(self, job: GlobalAskJob, user_id: str, request_id: str | None, request_json: str, submitted_via: str, *, new_conversation: bool) -> None: ...
    def save(self, job: GlobalAskJob, user_id: str) -> bool: ...
    def jobs(self, conversation_id: str, user_id: str, limit: int, offset: int) -> list[GlobalAskJob]: ...
    def rename(self, conversation_id: str, user_id: str, title: str) -> bool: ...
    def delete(self, conversation_id: str, user_id: str) -> bool: ...
    def recover(self) -> None: ...
