"""Persistence contract for independent global question-answer sessions."""
from typing import Protocol, Sequence

from app.models.global_ask import GlobalAskJob, GlobalConversationSummary


class GlobalAskAuthorityStorePort(Protocol):
    """Batch read authority used only by global orchestration."""
    def readable_notebook_names(self, user_id: str) -> dict[str, str]: ...
    def readable_notebook_ids(self, notebook_ids: Sequence[str], user_id: str) -> set[str]: ...


class GlobalAskSourceStorePort(Protocol):
    """Narrow source snapshots for global execution and evidence validation."""
    def visible_source_ids_by_notebook(self, notebook_ids: Sequence[str]) -> dict[str, list[str]]: ...
    def evidence_fingerprints(self, element_ids: Sequence[str]) -> dict[str, tuple[str, str]]: ...


class GlobalAskStorePort(Protocol):
    def conversation(self, conversation_id: str, user_id: str) -> GlobalConversationSummary | None: ...
    def list_conversations(self, user_id: str, limit: int, offset: int) -> list[GlobalConversationSummary]: ...
    def job(self, job_id: str, user_id: str) -> GlobalAskJob | None: ...
    def request_job(self, user_id: str, request_id: str | None) -> tuple[GlobalAskJob, str] | None: ...
    def create(self, job: GlobalAskJob, user_id: str, request_id: str | None, request_json: str, submitted_via: str, *, new_conversation: bool) -> None: ...
    def save(self, job: GlobalAskJob, user_id: str) -> bool: ...
    def save_progress(self, job: GlobalAskJob, user_id: str) -> bool: ...
    def jobs(self, conversation_id: str, user_id: str, limit: int, offset: int) -> list[GlobalAskJob]: ...
    def completed_history(self, conversation_id: str, user_id: str, limit: int) -> list[dict]: ...
    def running_job_ids(self, conversation_id: str, user_id: str) -> list[str]: ...
    def rename(self, conversation_id: str, user_id: str, title: str) -> bool: ...
    def delete(self, conversation_id: str, user_id: str) -> bool: ...
    def recover(self) -> None: ...
