"""Consumer-owned repository contracts.

The concrete SQLite facade remains the compatibility implementation.  These
protocols intentionally contain no business logic and are structural seams for
the later store/service extraction.
"""
from __future__ import annotations
import sqlite3
import threading

from dataclasses import dataclass
from pathlib import Path
from typing import Any, Callable, Iterable, Mapping, Protocol, Sequence, runtime_checkable

from app.core.config import Settings
from app.models.schemas import (
    AddUrlSourcesResult, AnswerAnchor, AskRequest, AskResponse, Citation, ConversationDetail,
    ConversationSummary, DuplicateGroup, FeedbackRequest, FeedbackResponse,
    KnowledgeGraph, KnowledgeTypeCount, KnowledgeUpdate, MergeRequest,
    NotebookAnalytics, NotebookCreate, NotebookSearchResponse, NotebookSummary,
    NotebookTemplate, NotebookUpdate, ObjectSchemaCreate, ObjectSchemaModel,
    ObjectSchemaUpdate, PaginatedKnowledge, PaginatedSources, RuleCard,
    SourceDetail, SourceElement, SourceImportRequest, SourceSummary, UserProfile,
)
from app.services.cancellation import CancelEvent
from app.services.model_config import ResolvedModelConfig
from app.services.notebook_scale import NotebookScaleFacts
from app.services.retrieval import (
    RetrievedChunk, RetrievedElement, RetrievedKnowledge, RetrievedRelation,
    W_KEYWORD, W_SEMANTIC,
)
from app.services.kg.follow_chain import FollowChainResult


@dataclass
class UploadedSourceFile:
    file_name: str
    content_type: str
    content: bytes
    doc_type: str = ""


SourceScheduler = Callable[[str], None]


class IdentityRepository(Protocol):
    def current_user(self) -> UserProfile: ...
    def get_user_model_settings(self, user_id: str) -> dict: ...
    def set_user_model_settings(self, user_id: str, settings: dict) -> None: ...
    def resolve_model_config(self, user: UserProfile, role: str) -> ResolvedModelConfig: ...
    def create_user(self, username: str, password: str) -> UserProfile: ...
    def authenticate_user(self, username: str, password: str) -> UserProfile | None: ...
    def create_session(self, user_id: str) -> str: ...
    def resolve_session(self, token: str) -> UserProfile | None: ...
    def delete_session(self, token: str) -> None: ...


class NotebookAccessRepository(Protocol):
    def user_can_access_notebook(self, notebook_id: str, user_id: str) -> bool: ...
    def is_member(self, notebook_id: str, user_id: str) -> bool: ...
    def user_can_read_notebook(self, notebook_id: str, user_id: str) -> bool: ...
    def user_can_read_source(self, source_id: str, user_id: str) -> bool: ...
    def source_owner(self, source_id: str) -> str | None: ...
    def conversation_owner(self, conversation_id: str) -> str | None: ...
    def answer_owner(self, answer_id: str) -> str | None: ...
    def user_can_read_answer(self, answer_id: str, user_id: str) -> bool: ...


class NotebookCatalogRepository(Protocol):
    def list_notebook_templates(self) -> list[NotebookTemplate]: ...
    def list_notebooks(self) -> list[NotebookSummary]: ...
    def create_notebook(self, payload: NotebookCreate) -> NotebookSummary: ...
    def get_notebook(self, notebook_id: str) -> NotebookSummary: ...
    def update_notebook(self, notebook_id: str, payload: NotebookUpdate) -> NotebookSummary: ...
    def delete_notebook(self, notebook_id: str) -> None: ...
    def mark_notebook_base(self, notebook_id: str) -> None: ...
    def set_notebook_personal(self, notebook_id: str) -> None: ...
    def notebook_analytics(self, notebook_id: str) -> NotebookAnalytics: ...
    def search_notebook(self, notebook_id: str, query: str) -> NotebookSearchResponse: ...


class NotebookSharingRepository(Protocol):
    def share_notebook(self, notebook_id: str) -> dict: ...
    def unshare_notebook(self, notebook_id: str) -> None: ...
    def find_notebook_by_share_token(self, token: str) -> str | None: ...
    def notebook_copy_stats(self, notebook_id: str) -> dict: ...
    def shared_preview(self, notebook_id: str) -> dict: ...
    def shared_by_me(self, user_id: str) -> list: ...
    def copy_notebook(self, source_notebook_id: str, *, new_owner_id: str, new_name: str | None = None) -> NotebookSummary: ...
    def add_member(self, notebook_id: str, user_id: str) -> None: ...
    def remove_member(self, notebook_id: str, user_id: str) -> None: ...
    def kick_all_members(self, notebook_id: str) -> None: ...
    def list_members(self, notebook_id: str) -> list: ...
    def join_shared(self, notebook_id: str, user_id: str) -> NotebookSummary: ...
    def leave_notebook(self, notebook_id: str, user_id: str) -> None: ...


class SourceRepository(Protocol):
    def list_sources(self, notebook_id: str) -> list[SourceSummary]: ...
    def list_sources_page(self, notebook_id: str, offset: int = 0, limit: int = 50, q: str = "") -> PaginatedSources: ...
    def import_sources(self, notebook_id: str, payload: SourceImportRequest) -> list[SourceSummary]: ...
    def add_url_sources(self, notebook_id: str, urls: Iterable[str], scheduler: SourceScheduler | None = None) -> AddUrlSourcesResult: ...
    def upload_sources(self, notebook_id: str, files: Iterable[UploadedSourceFile], scheduler: SourceScheduler | None = None) -> list[SourceSummary]: ...
    def get_source(self, source_id: str) -> SourceDetail: ...
    def process_source(self, source_id: str) -> SourceSummary: ...
    def parse_source(self, source_id: str) -> SourceSummary: ...
    def source_elements(self, source_id: str) -> list[SourceElement]: ...
    def delete_source(self, source_id: str) -> None: ...
    def extract_source(self, source_id: str) -> None: ...


class KnowledgeReadRepository(Protocol):
    def knowledge_types(self, notebook_id: str) -> list[KnowledgeTypeCount]: ...
    def list_knowledge(self, notebook_id: str, object_type: str, status: str | None = None, offset: int = 0, limit: int = 50) -> PaginatedKnowledge: ...
    def knowledge_graph(self, notebook_id: str) -> KnowledgeGraph: ...
    def kg_search(self, notebook_id: str, q: str, k: int = 30) -> list: ...
    def unified_graph(self, notebook_id: str, level: str = "concept", limit: int | None = None) -> dict: ...
    def concept_detail(self, notebook_id: str, canonical_id: str) -> dict: ...
    def node_context(self, notebook_id: str, object_id: str) -> dict: ...
    def kg_neighbors(self, notebook_id: str, object_id: str, cap: int = 50) -> dict: ...


class SchemaRegistryRepository(Protocol):
    def list_object_schemas(self) -> list[ObjectSchemaModel]: ...
    def create_object_schema(self, payload: ObjectSchemaCreate) -> ObjectSchemaModel: ...
    def update_object_schema(self, object_type: str, payload: ObjectSchemaUpdate) -> ObjectSchemaModel: ...
    def delete_object_schema(self, object_type: str) -> None: ...
    def propose_schemas(self, notebook_id: str) -> list[ObjectSchemaModel]: ...


class KnowledgeGovernanceRepository(Protocol):
    def update_knowledge(self, notebook_id: str, knowledge_id: str, payload: KnowledgeUpdate) -> RuleCard: ...
    def find_duplicates(self, notebook_id: str, object_type: str) -> list[DuplicateGroup]: ...
    def merge_knowledge(self, notebook_id: str, source_id: str, payload: MergeRequest) -> RuleCard: ...
    def review_queue(self, notebook_id: str, limit: int = 200) -> list[dict]: ...
    def set_edge_review(self, notebook_id: str, rel_id: str, status: str) -> None: ...
    def pending_merges(self, notebook_id: str) -> list[dict]: ...
    def confirm_merge(self, notebook_id: str, candidate_id: str) -> None: ...
    def reject_merge(self, notebook_id: str, candidate_id: str) -> None: ...
    def pending_conflicts(self, notebook_id: str) -> list[dict]: ...
    def resolve_notebook_conflicts(self, notebook_id: str) -> dict: ...
    def confirm_conflict(self, notebook_id: str, candidate_id: str) -> dict: ...
    def reject_conflict(self, notebook_id: str, candidate_id: str) -> None: ...
    def concept_whitelist_list(self) -> list[dict]: ...
    def concept_whitelist_add(self, term: str, note: str = "") -> dict: ...
    def concept_whitelist_remove(self, term: str) -> None: ...
    def review_pending_merges(self, notebook_id: str, limit: int = 50, confirm_threshold: float | None = None, separate_threshold: float | None = None) -> dict: ...
    def merge_review_job_status(self, notebook_id: str) -> dict: ...
    def run_merge_review_job(self, notebook_id: str, *, batch: int = 100) -> dict: ...
    def propose_promotion(self, notebook_id: str, object_id: str) -> dict: ...
    def list_promotion_queue(self, status_filter: str | None = None) -> list[dict]: ...
    def approve_promotion(self, candidate_id: str) -> dict: ...
    def reject_promotion(self, candidate_id: str, reason: str = "") -> dict: ...


class KgMutationPort(Protocol):
    """The KG mutation side-effect coordinator's contract (Task 14).

    Every online KG write funnels its post-commit side effects through this
    port in the frozen per-operation order (mutation_phases.json); deep-copy,
    migration/recovery/seed and streaming-ask writes are exempt and never call
    it. ``mark_unified_kg_dirty`` is the ONLY entry that advances
    kg_mutation_seq; ``bump_cluster_mutation_seq`` runs inside the caller's
    open write transaction (cluster write + bump commit atomically) and never
    touches kg_mutation_seq (rebuild keeps it stable for idempotency).
    """

    def invalidate_unified_cache(self, notebook_id: str) -> None: ...
    def mark_unified_kg_dirty(self, notebook_id: str) -> None: ...
    def bump_cluster_mutation_seq(self, connection: sqlite3.Connection, notebook_id: str) -> None: ...


class KnowledgeLifecycleRepository(Protocol):
    def build_notebook_kg(self, notebook_id: str, *, progress: Callable | None = None) -> dict: ...
    def rebuild_notebook_kg(self, notebook_id: str) -> dict: ...
    def relink_notebook_kg(self, notebook_id: str) -> dict: ...
    def rebuild_unified_kg(self, notebook_id: str, progress: Callable[[str, int, int], None] | None = None, force: bool = False) -> int: ...
    def unified_kg_status(self, notebook_id: str) -> dict: ...


class IndexLifecycleRepository(Protocol):
    def trigger_scale_index_rebuild(self, notebook_id: str, when: str = "now", mode: str = "auto") -> dict: ...
    def cancel_scale_index(self, notebook_id: str) -> dict: ...
    def scale_index_status(self, notebook_id: str) -> dict: ...
    def index_status(self, notebook_id: str) -> dict: ...


class AskStateRepository(Protocol):
    def begin_ask_job(self, notebook_id: str, payload: AskRequest, mode: str, cancel_event: threading.Event) -> tuple[str, str]: ...
    def finish_ask_job(self, job_id: str, status: str, *, answer_id: str = "", error: str = "") -> None: ...
    def cancel_ask_job(self, job_id: str, user_id: str) -> dict: ...
    def ask_job_status(self, job_id: str) -> dict: ...
    def append_ask_trace(self, job_id: str, step: dict) -> None: ...
    def ask_job_detail(self, job_id: str) -> dict: ...
    def list_conversations(self, notebook_id: str) -> list[ConversationSummary]: ...
    def get_conversation(self, conversation_id: str) -> ConversationDetail: ...
    def rename_conversation(self, conversation_id: str, title: str) -> None: ...
    def delete_conversation(self, conversation_id: str) -> None: ...
    def bulk_delete_conversations(self, notebook_id: str, older_than_days: int) -> int: ...
    def submit_feedback(self, answer_id: str, payload: FeedbackRequest) -> FeedbackResponse: ...


class ReportRepository(Protocol):
    def create_report(self, notebook_id: str, question: str, depth: int = 2) -> str: ...
    def update_report(self, notebook_id: str, report_id: str, *, status=None, progress=None, error=None, outline=None, sections=None, gaps=None, references=None, content_md=None, section_status=None) -> None: ...
    def get_report(self, notebook_id: str, report_id: str) -> dict: ...
    def list_reports(self, notebook_id: str) -> list: ...
    def delete_report(self, notebook_id: str, report_id: str) -> None: ...
    def export_reports(self, notebook_id: str, report_ids: list) -> list: ...


class AdminQueryRepository(Protocol):
    def list_user_usage(self) -> list[dict[str, Any]]: ...
    def list_user_notebooks(self, user_id: str) -> list[dict[str, Any]]: ...
    def notebook_analytics(self, notebook_id: str) -> NotebookAnalytics: ...
    def pending_actions_projection_rows(self, user_id: str) -> dict: ...
    def search_notebook(self, notebook_id: str, query: str) -> NotebookSearchResponse: ...
    def load_notebook_scale_facts(self, notebook_id: str) -> NotebookScaleFacts: ...


class AskExecutionPort(Protocol):
    def ask(self, notebook_id: str, payload: AskRequest) -> AskResponse: ...
    def ask_chunk(self, notebook_id: str, payload: AskRequest, cancel_event: CancelEvent = None) -> AskResponse: ...
    def ask_reasoning(self, notebook_id: str, payload: AskRequest, on_trace: Callable[[Any], None] | None = None, cancel_event: CancelEvent = None) -> AskResponse: ...
    def ask_graph(self, notebook_id: str, payload: AskRequest, seed_ids: list[str] | None = None, cancel_event: CancelEvent = None) -> AskResponse: ...


class NotebookStorePort(Protocol):
    def tier_map(self, notebook_ids: Sequence[str]) -> dict[str, str]: ...
    def participant_notebook_ids(self, active_notebook_id: str) -> list[str]: ...
    def participant_ids(self, db: sqlite3.Connection, active_notebook_id: str) -> list[str]: ...
    def participant_rows(self, db: sqlite3.Connection, active_notebook_id: str) -> tuple[Any, list[Any]]: ...
    def participant_tiers(self, db: sqlite3.Connection, active_notebook_id: str) -> tuple[list[str], dict[str, str]]: ...


class SourceStorePort(Protocol):
    def evidence_elements(
        self, element_ids: Sequence[str]
    ) -> dict[str, dict[str, Any]]: ...
    def source_metadata(
        self, source_ids: Sequence[str]
    ) -> dict[str, dict[str, Any]]: ...
    def retrieval_element_rows(self, db: sqlite3.Connection, notebook_id: str) -> list[Any]: ...


class ChunkStorePort(Protocol):
    def language_probe_rows(self, db: sqlite3.Connection, notebook_id: str) -> list[Any]: ...
    def retrieval_rows(self, db: sqlite3.Connection, notebook_id: str) -> list[Any]: ...
    def count_row(self, db: sqlite3.Connection, notebook_id: str) -> Any: ...
    def hydrate_rows(self, db: sqlite3.Connection, chunk_ids: Sequence[str]) -> list[Any]: ...
    def graph_hydrate_rows(self, db: sqlite3.Connection, chunk_ids: Sequence[str]) -> list[Any]: ...
    def id_element_rows(self, db: sqlite3.Connection, notebook_id: str) -> list[Any]: ...
    def rows_by_ids(self, db: sqlite3.Connection, chunk_ids: Sequence[str]) -> list[Any]: ...
    def id_rows(self, db: sqlite3.Connection, notebook_id: str) -> list[Any]: ...


class EmbeddingStorePort(Protocol):
    def version_row(self, db: sqlite3.Connection, notebook_id: str, table: str) -> Any: ...
    def vector_rows(self, db: sqlite3.Connection, notebook_id: str, table: str, id_col: str) -> list[Any]: ...
    def vector_rows_for_ids(self, db: sqlite3.Connection, notebook_id: str, table: str, id_col: str, ids: Sequence[str]) -> list[Any]: ...
    def relation_delta_rows(self, db: sqlite3.Connection, notebook_id: str, source_ids: Sequence[str]) -> list[Any]: ...
    def knowledge_delta_rows(self, db: sqlite3.Connection, notebook_id: str, source_ids: Sequence[str]) -> list[Any]: ...
    def element_delta_rows(self, db: sqlite3.Connection, notebook_id: str, source_ids: Sequence[str]) -> list[Any]: ...
    def chunk_delta_rows(self, db: sqlite3.Connection, notebook_id: str, source_ids: Sequence[str]) -> list[Any]: ...
    def rows_by_ids(self, db: sqlite3.Connection, table: str, id_col: str, ids: Sequence[str]) -> list[Any]: ...


class KnowledgeStorePort(Protocol):
    def usable_object_rows(
        self,
        notebook_id: str,
        object_ids: Sequence[str],
    ) -> list[dict[str, Any]]: ...


@runtime_checkable
class EvidenceKnowledgeContextPort(Protocol):
    def cluster_map(self, notebook_id: str) -> dict[str, str]: ...
    def node_context(self, notebook_id: str, object_id: str) -> dict[str, Any]: ...
    def in_network_relations(
        self, participant_ids: Sequence[str], object_ids: Sequence[str]
    ) -> list[dict[str, Any]]: ...
    def relation_support_count(
        self, notebook_id: str, source_id: str, edge_type: str, target_id: str
    ) -> int: ...


class RetrievalKnowledgeStorePort(KnowledgeStorePort, Protocol):
    def retrieval_objects(self, db: sqlite3.Connection, notebook_id: str,
                          object_type: str, statuses: Iterable[str] | None,
                          id_filter: Iterable[str] | None, *,
                          batch_size: int = 900) -> list[dict[str, Any]]: ...
    def any_base_has_kg_on(self, db: sqlite3.Connection) -> bool: ...
    def object_version_row(self, db: sqlite3.Connection, notebook_id: str) -> Any: ...
    def relation_context_rows(self, db: sqlite3.Connection, notebook_id: str, relation_ids: Sequence[str] | None = None, *, batch_size: int = 900) -> list[Any]: ...
    def relation_exists(self, db: sqlite3.Connection, notebook_id: str) -> bool: ...
    def relation_endpoint_rows(self, db: sqlite3.Connection, notebook_id: str, source_ids: Sequence[str] | None = None) -> list[Any]: ...
    def relation_connected_rows(self, db: sqlite3.Connection, notebook_id: str, object_ids: Sequence[str]) -> list[Any]: ...
    def neighbor_ids(self, db: sqlite3.Connection, notebook_id: str, object_id: str, *, endpoint: str, edge_type: str | None = None) -> list[Any]: ...
    def usable_object_rows_on(self, db: sqlite3.Connection, object_ids: Sequence[str], statuses: Sequence[str]) -> list[Any]: ...
    def graph_version_rows(self, db: sqlite3.Connection, notebook_id: str) -> tuple[Any, Any]: ...
    def graph_object_rows(self, db: sqlite3.Connection, notebook_id: str, statuses: Sequence[str]) -> list[Any]: ...
    def graph_relation_rows(self, db: sqlite3.Connection, notebook_id: str, *, include_id_evidence: bool = True) -> list[Any]: ...
    def object_evidence_rows(self, db: sqlite3.Connection, object_ids: Sequence[str]) -> list[Any]: ...
    def notebook_object_evidence_rows(self, db: sqlite3.Connection, notebook_id: str) -> list[Any]: ...
    def follow_start_row(self, db: sqlite3.Connection, object_id: str, active_notebook_id: str, statuses: Sequence[str]) -> Any: ...
    def follow_endpoint_rows(self, db: sqlite3.Connection, notebook_id: str, object_id: str, endpoint: str, limit: int) -> list[Any]: ...
    def follow_relation_evidence_rows(self, db: sqlite3.Connection, relation_ids: Sequence[str]) -> list[Any]: ...
    def follow_object_rows(self, db: sqlite3.Connection, notebook_id: str, object_ids: Sequence[str], statuses: Sequence[str]) -> list[Any]: ...
    def in_network_relation_rows(self, db: sqlite3.Connection, notebook_id: str, object_ids: Sequence[str]) -> list[Any]: ...


class UnifiedKgStorePort(Protocol):
    def cluster_version_row(self, db: sqlite3.Connection, notebook_id: str) -> Any: ...
    def cluster_member_rows(self, db: sqlite3.Connection, notebook_id: str) -> list[Any]: ...
    def ppr_version_rows(self, db: sqlite3.Connection, notebook_id: str) -> tuple[Any, Any, Any, Any, Any]: ...
    def mention_rows(self, db: sqlite3.Connection, notebook_id: str) -> list[Any]: ...


class CommunityQueryPort(Protocol):
    def first_base_notebook_id(
        self, active_notebook_id: str
    ) -> str | None: ...
    def resolve_comparison_peers(
        self,
        base_notebook_id: str,
        focal_name: str,
        question: str,
        *,
        top_k: int,
        candidates: int,
    ) -> tuple[list[str], str]: ...


class EvidenceContextPort(Protocol):
    def chunk_context(
        self,
        chunks: Sequence[RetrievedChunk],
        *,
        notebook_id: str,
        budget_chars: int | None = None,
    ) -> tuple[str, dict[str, dict[str, Any]]]: ...
    def knowledge_context(
        self,
        notebook_id: str,
        hits: Sequence[RetrievedKnowledge],
        *,
        id_offset: int = 0,
    ) -> tuple[str, dict[str, dict[str, Any]]]: ...
    def parse_anchors(
        self,
        answer: str,
        evidence_by_id: Mapping[str, Mapping[str, Any]],
    ) -> list[AnswerAnchor]: ...
    def citations_from(
        self,
        hits: Sequence[RetrievedKnowledge],
        valid_element_ids: set[str],
        label: str,
    ) -> list[Citation]: ...
    def tier_map(self, notebook_ids: Sequence[str]) -> dict[str, str]: ...


class RetrievalPort(Protocol):
    def retrieve_scored(self, notebook_id: str, query: str, types: Iterable[str] | None = None, w_keyword: float = W_KEYWORD, w_semantic: float = W_SEMANTIC) -> list[RetrievedKnowledge]: ...
    def federated_retrieve(self, active_notebook_id: str, query: str, types: Iterable[str] | None = None, w_keyword: float = W_KEYWORD, w_semantic: float = W_SEMANTIC) -> list[RetrievedKnowledge]: ...
    def federated_retrieve_relations(self, active_notebook_id: str, query: str) -> list[RetrievedRelation]: ...
    def retrieve_neighbors(self, notebook_id: str, object_id: str, edge_type: str | None = None, direction: str = "both") -> list[RetrievedKnowledge]: ...
    def retrieve_elements(self, notebook_id: str, query: str, limit: int = 8) -> list[RetrievedElement]: ...
    def ppr_retrieve(self, notebook_id: str, question: str) -> list[RetrievedChunk]: ...
    def follow_chain(self, active_notebook_id: str, start_object_id: str, edge_type: str | None = None, target_object_id: str = "", direction: str = "out", max_fan_out: int = 8, max_results: int = 4) -> FollowChainResult: ...
    def node_context(self, notebook_id: str, object_id: str) -> dict[str, Any]: ...


class ModelClientProvider(Protocol):
    @property
    def llm_client(self) -> Any: ...
    @llm_client.setter
    def llm_client(self, value: Any) -> None: ...
    @property
    def reasoning_llm_client(self) -> Any: ...
    @property
    def rewrite_llm_client(self) -> Any: ...
    @property
    def kg_llm_client(self) -> Any: ...
    @property
    def rerank_client(self) -> Any: ...
    @rerank_client.setter
    def rerank_client(self, value: Any) -> None: ...


class ModelErrorSink(Protocol):
    def note_model_error(self, stage: str, model: str, error: Exception) -> None: ...


class FacadePropertyContract(ModelClientProvider, Protocol):
    settings: Settings
    storage_dir: Path
    embedder: Any
    retrieval: RetrievalPort


class AskStreamPort(AskExecutionPort, AskStateRepository, IdentityRepository, Protocol):
    pass


class NotebookRepository(IdentityRepository, NotebookAccessRepository, NotebookCatalogRepository, NotebookSharingRepository, SourceRepository, KnowledgeReadRepository, SchemaRegistryRepository, KnowledgeGovernanceRepository, KnowledgeLifecycleRepository, IndexLifecycleRepository, AskStateRepository, ReportRepository, AdminQueryRepository, AskExecutionPort, FacadePropertyContract, Protocol):
    pass


class SQLiteMaintenancePort(Protocol):
    def delete_notebook_kg(self, notebook_id: str) -> dict: ...
    def backfill_kg_fts(self, notebook_id: str) -> int: ...
    def backfill_chunk_fts(self, notebook_id: str) -> int: ...
    def build_scale_index(self, notebook_id: str, on_stage: Callable[[str, int], None] | None = None) -> dict: ...
    def fold_scale_index_delta(self, notebook_id: str, _assume_locked: bool = False) -> dict: ...
