"""Legacy Pydantic-model import facade; import domain modules in new code."""

from app.models.admin import (
    AdminUserNotebook,
    AdminUserUsage,
    PromoteRequest,
    PromotionApproveResult,
    PromotionCandidate,
    PromotionRejectRequest,
)
from app.models.ask import (
    ActiveAskJob,
    AnswerAnchor,
    AskRequest,
    AskResponse,
    Citation,
    CitationKnowhowRef,
    ConversationDetail,
    ConversationRenameRequest,
    ConversationSummary,
    ConversationTurn,
    FeedbackRequest,
    FeedbackResponse,
    KgSearchHit,
    KgSearchResponse,
    ModelError,
    NotebookSearchResponse,
    RuleCard,
    SearchHit,
    TraceStep,
)
from app.models.common import Evidence
from app.models.content_overview import (
    KnowhowOverviewSummary,
    KnowhowOverviewTable,
    MemoryOverviewItem,
    MemoryOverviewSummary,
    NotebookContentOverview,
)
from app.models.identity import (
    AgentPrincipal,
    AgentProfile,
    AgentProfileCreate,
    AgentProfileUpdate,
    AgentTokenCreate,
    AgentTokenIssued,
    AgentTokenSummary,
    AuthRequest,
    AuthResult,
    UserProfile,
)
from app.models.kg import (
    ConceptWhitelistAdd,
    ConceptWhitelistEntry,
    KgBuildJobStatus,
    MergeReviewJob,
    MergeReviewRequest,
    MergeReviewSummary,
    RebuildScaleIndexRequest,
    ScaleIndexStatus,
    UnifiedKgStatus,
)
from app.models.knowhow import (
    KnowhowAgentColumn,
    KnowhowAgentTable,
    KnowhowAppendDuplicateTitle,
    KnowhowAppendPreview,
    KnowhowAppendResult,
    KnowhowCellCodePut,
    KnowhowCellCodeResult,
    KnowhowCellOptimizeResult,
    KnowhowCellPatch,
    KnowhowCellPatchResult,
    KnowhowCellReformatResult,
    KnowhowCellsBatchPatch,
    KnowhowColumn,
    KnowhowColumnCreate,
    KnowhowColumnPatch,
    KnowhowDiscriminationMethod,
    KnowhowDiscriminationRow,
    KnowhowDiscriminationSet,
    KnowhowImportPreview,
    KnowhowNewColumnInput,
    KnowhowPreviewColumn,
    KnowhowRow,
    KnowhowRowCell,
    KnowhowRowCode,
    KnowhowRowCreate,
    KnowhowRowDetail,
    KnowhowTableCreate,
    KnowhowTableDetail,
    KnowhowTablePatch,
    KnowhowTableSummary,
    KnowhowTransferRequest,
)
from app.models.knowledge import (
    DuplicateGroup,
    EdgeReviewItem,
    EdgeReviewRequest,
    KnowledgeEdge,
    KnowledgeFieldValue,
    KnowledgeGraph,
    KnowledgeNode,
    KnowledgeRecord,
    KnowledgeRef,
    KnowledgeTypeCount,
    KnowledgeUpdate,
    MergeRequest,
    ObjectSchemaCreate,
    ObjectSchemaModel,
    ObjectSchemaUpdate,
    PaginatedKnowledge,
)
from app.models.memory import (
    AnswerMemoryLinksRequest,
    AnswerMemoryLinksResponse,
    MemoryBulkDeleteRequest,
    MemoryCreateFromAnswer,
    MemoryHit,
    MemoryNotebookOption,
    MemoryOrigin,
    MemoryPreview,
    MemoryPromotionState,
    MemoryRecord,
    MemoryReviewRequest,
    MemoryStatus,
    MemoryTransferRequest,
    MemoryUpdate,
    PaginatedMemories,
)
from app.models.model_services import (
    ModelServiceStatusItem,
    ModelServicesStatus,
    ModelWorkloadView,
)
from app.models.notebooks import (
    MountedBase,
    MountedByCount,
    NotebookAnalytics,
    NotebookCreate,
    NotebookRef,
    NotebookSummary,
    NotebookUpdate,
    SetBasesRequest,
    SetTierRequest,
    ShareResponse,
    SharedByMeItem,
    SharedPreview,
)
from app.models.reports import (
    ReportCreate,
    ReportDetail,
    ReportExportRequest,
    ReportGenerateRequest,
    ReportOutlineUpdate,
    ReportSummary,
)
from app.models.sources import (
    AddUrlSourcesRequest,
    AddUrlSourcesResult,
    DetectDocTypeItem,
    DetectDocTypesRequest,
    DetectedDocType,
    PaginatedSources,
    PaperAuthor,
    PaperMeta,
    RejectedUrl,
    SourceDetail,
    SourceElement,
    SourceImportFile,
    SourceImportRequest,
    SourceSummary,
)

__all__ = [
    "ActiveAskJob", "AddUrlSourcesRequest", "AddUrlSourcesResult", "AdminUserNotebook",
    "AdminUserUsage", "AgentPrincipal", "AgentProfile", "AgentProfileCreate",
    "AgentProfileUpdate", "AgentTokenCreate", "AgentTokenIssued", "AgentTokenSummary",
    "AnswerAnchor", "AnswerMemoryLinksRequest", "AnswerMemoryLinksResponse", "AskRequest",
    "AskResponse", "AuthRequest", "AuthResult", "Citation", "CitationKnowhowRef",
    "ConceptWhitelistAdd", "ConceptWhitelistEntry", "ConversationDetail",
    "ConversationRenameRequest", "ConversationSummary", "ConversationTurn", "DetectDocTypeItem",
    "DetectDocTypesRequest", "DetectedDocType", "DuplicateGroup", "EdgeReviewItem",
    "EdgeReviewRequest", "Evidence", "FeedbackRequest", "FeedbackResponse", "KgBuildJobStatus",
    "KgSearchHit", "KgSearchResponse", "KnowhowAgentColumn", "KnowhowAgentTable",
    "KnowhowAppendDuplicateTitle", "KnowhowAppendPreview", "KnowhowAppendResult",
    "KnowhowCellCodePut", "KnowhowCellCodeResult", "KnowhowCellOptimizeResult",
    "KnowhowCellPatch", "KnowhowCellPatchResult", "KnowhowCellReformatResult",
    "KnowhowCellsBatchPatch", "KnowhowColumn", "KnowhowColumnCreate", "KnowhowColumnPatch",
    "KnowhowDiscriminationMethod", "KnowhowDiscriminationRow", "KnowhowDiscriminationSet",
    "KnowhowImportPreview", "KnowhowNewColumnInput", "KnowhowOverviewSummary",
    "KnowhowOverviewTable", "KnowhowPreviewColumn", "KnowhowRow", "KnowhowRowCell",
    "KnowhowRowCode", "KnowhowRowCreate", "KnowhowRowDetail", "KnowhowTableCreate",
    "KnowhowTableDetail", "KnowhowTablePatch", "KnowhowTableSummary", "KnowhowTransferRequest",
    "KnowledgeEdge", "KnowledgeFieldValue", "KnowledgeGraph", "KnowledgeNode", "KnowledgeRecord",
    "KnowledgeRef", "KnowledgeTypeCount", "KnowledgeUpdate", "MemoryBulkDeleteRequest",
    "MemoryCreateFromAnswer", "MemoryHit", "MemoryNotebookOption", "MemoryOrigin",
    "MemoryOverviewItem", "MemoryOverviewSummary", "MemoryPreview", "MemoryPromotionState",
    "MemoryRecord", "MemoryReviewRequest", "MemoryStatus", "MemoryTransferRequest", "MemoryUpdate",
    "MergeRequest", "MergeReviewJob", "MergeReviewRequest", "MergeReviewSummary", "ModelError",
    "ModelServiceStatusItem", "ModelServicesStatus", "ModelWorkloadView", "MountedBase", "MountedByCount", "NotebookAnalytics",
    "NotebookContentOverview", "NotebookCreate", "NotebookRef", "NotebookSearchResponse",
    "NotebookSummary", "NotebookUpdate", "ObjectSchemaCreate",
    "ObjectSchemaModel", "ObjectSchemaUpdate", "PaginatedKnowledge", "PaginatedMemories",
    "PaginatedSources", "PaperAuthor", "PaperMeta", "PromoteRequest", "PromotionApproveResult",
    "PromotionCandidate", "PromotionRejectRequest", "RebuildScaleIndexRequest", "RejectedUrl",
    "ReportCreate", "ReportDetail", "ReportExportRequest", "ReportGenerateRequest",
    "ReportOutlineUpdate", "ReportSummary", "RuleCard", "ScaleIndexStatus", "SearchHit",
    "SetBasesRequest", "SetTierRequest", "ShareResponse", "SharedByMeItem", "SharedPreview",
    "SourceDetail", "SourceElement", "SourceImportFile", "SourceImportRequest", "SourceSummary",
    "TraceStep", "UnifiedKgStatus", "UserProfile",
]
