"""Trusted built-in extension bundles registered by the composition root."""

from app.extensions.builtin.generated_question import (
    GENERATED_QUESTION_BUNDLE,
    GENERATED_QUESTION_CONTRIBUTION_ID,
)

from app.extensions.builtin.selected_source_graph import (
    SELECTED_SOURCE_GRAPH_BUNDLE,
    SELECTED_SOURCE_GRAPH_CONTRIBUTION_ID,
)
from app.extensions.builtin.parser import (
    PARSER_BUILTIN_BUNDLE,
    PARSER_BUILTIN_CONTRIBUTION_ID,
    PARSER_CLOUD_BUNDLE,
    PARSER_CLOUD_CONTRIBUTION_ID,
    PARSER_SELF_HOSTED_BUNDLE,
    PARSER_SELF_HOSTED_CONTRIBUTION_ID,
)
from app.extensions.builtin.ask_completion import (
    AGENT_PROFILE_WORKSPACE_UI_CAPABILITY,
    AGENT_PROFILE_WORKSPACE_UI_CONTRIBUTION_ID,
    ASK_AGENT_PROFILE_COMPLETED_BUNDLE,
    ASK_AGENT_PROFILE_COMPLETED_CONTRIBUTION_ID,
    ASK_RETRIEVAL_EXPERIENCE_COMPLETED_BUNDLE,
    ASK_RETRIEVAL_EXPERIENCE_COMPLETED_CONTRIBUTION_ID,
    ASK_SEARCH_PROFILE_COMPLETED_BUNDLE,
    ASK_SEARCH_PROFILE_COMPLETED_CONTRIBUTION_ID,
)
from app.extensions.builtin.report_completion import (
    REPORT_AGENT_PROFILE_COMPLETED_BUNDLE,
    REPORT_AGENT_PROFILE_COMPLETED_CONTRIBUTION_ID,
)
from app.extensions.builtin.report_export import (
    REPORT_MARKDOWN_EXPORTER_BUNDLE,
    REPORT_MARKDOWN_EXPORTER_CONTRIBUTION_ID,
    REPORT_MARKDOWN_EXPORTER_PLUGIN_ID,
)

__all__ = [
    "AGENT_PROFILE_WORKSPACE_UI_CAPABILITY",
    "AGENT_PROFILE_WORKSPACE_UI_CONTRIBUTION_ID",
    "GENERATED_QUESTION_BUNDLE",
    "GENERATED_QUESTION_CONTRIBUTION_ID",
    "PARSER_BUILTIN_BUNDLE",
    "PARSER_BUILTIN_CONTRIBUTION_ID",
    "PARSER_CLOUD_BUNDLE",
    "PARSER_CLOUD_CONTRIBUTION_ID",
    "PARSER_SELF_HOSTED_BUNDLE",
    "PARSER_SELF_HOSTED_CONTRIBUTION_ID",
    "SELECTED_SOURCE_GRAPH_BUNDLE",
    "SELECTED_SOURCE_GRAPH_CONTRIBUTION_ID",
    "ASK_AGENT_PROFILE_COMPLETED_BUNDLE",
    "ASK_AGENT_PROFILE_COMPLETED_CONTRIBUTION_ID",
    "ASK_RETRIEVAL_EXPERIENCE_COMPLETED_BUNDLE",
    "ASK_RETRIEVAL_EXPERIENCE_COMPLETED_CONTRIBUTION_ID",
    "ASK_SEARCH_PROFILE_COMPLETED_BUNDLE",
    "ASK_SEARCH_PROFILE_COMPLETED_CONTRIBUTION_ID",
    "REPORT_AGENT_PROFILE_COMPLETED_BUNDLE",
    "REPORT_AGENT_PROFILE_COMPLETED_CONTRIBUTION_ID",
    "REPORT_MARKDOWN_EXPORTER_BUNDLE",
    "REPORT_MARKDOWN_EXPORTER_CONTRIBUTION_ID",
    "REPORT_MARKDOWN_EXPORTER_PLUGIN_ID",
]
