"""Bounded prose windows and content-only visibility, with no I/O or judging."""

from __future__ import annotations

import hashlib
import re
from typing import Callable, Collection, Mapping, Sequence


_MATH = re.compile(r"\$\$.*?\$\$|(?<!\\)\$(?:\\.|[^$])*?(?<!\\)\$|\\\(.*?\\\)|\\\[.*?\\\]", re.DOTALL)
_SENTENCE_END = re.compile(r"[。！？](?:[”’])?|[.!?](?:[\"'])?(?=\s|$)")


def select_prose_excerpt(
    body: str, terms: Sequence[str], limit: int,
    *, select_window: Callable[[str, Sequence[str], int], tuple[str, bool]],
) -> tuple[str, bool]:
    """Keep a short paragraph whole; tighten a longer lexical window safely.

    Sentence and math boundaries only shorten the existing bounded selection.
    An overlong sentence may still use a word window, explicitly marked partial;
    a formula straddling its edge is omitted rather than presented as complete.
    """
    if len(body) <= limit:
        return body, False
    selected, _ = select_window(body, terms, limit - len("……"))
    core = selected.strip("…")
    start = body.find(core)
    if start < 0 or not core:
        return selected, True
    end = start + len(core)
    math_spans = [(match.start(), match.end()) for match in _MATH.finditer(body)]
    boundaries = [0, *(
        match.end() for match in _SENTENCE_END.finditer(body)
        if not any(left <= match.start() < right for left, right in math_spans)
    ), len(body)]
    inner = [point for point in boundaries if start <= point <= end]
    # Whole sentences are preferred only when they retain a query anchor.
    if len(inner) >= 2:
        sentence = body[inner[0]:inner[-1]].strip()
        if sentence and (not terms or any(t.casefold() in sentence.casefold() for t in terms)):
            start, end = inner[0], inner[-1]
    for left, right in math_spans:
        if left < start < right:
            start = right
        if left < end < right:
            end = left
    if start >= end:
        return "（公式超出详情窗口，未展开）", True
    # Avoid making a clipped Latin identifier look like another whole word.
    while start < end and start > 0 and body[start - 1].isascii() and body[start - 1].isalnum() and body[start].isascii() and body[start].isalnum():
        start += 1
    while end > start and end < len(body) and body[end - 1].isascii() and body[end - 1].isalnum() and body[end].isascii() and body[end].isalnum():
        end -= 1
    excerpt = body[start:end].strip()
    return ("…" if start else "") + excerpt + ("…" if end < len(body) else ""), True


def visible_excerpt_contents(material: str) -> set[tuple[str, str]]:
    """Read only excerpts in final rendered K/D, ignoring card metadata.

    The renderer collapses source-controlled newlines before assembling cards;
    table continuation lines are generated by the server. Block headings and
    observation rows cannot acquire a card identity here.
    """
    contents: set[tuple[str, str]] = set()
    key = ""
    excerpt: list[str] = []

    def flush() -> None:
        if key and excerpt:
            body = " ".join(" ".join(excerpt).removesuffix("”").split())
            if body:
                contents.add((key, body))

    for line in [*material.splitlines(), ""]:
        if line.startswith("- ["):
            flush()
            fields = line.split(" | ")
            key = fields[1][4:] if len(fields) > 1 and fields[1].startswith("key=") else ""
            excerpt = []
        elif key and line.startswith("  “"):
            excerpt = [line[3:]]
        elif excerpt and line.startswith("  ") and not line.startswith("  适用条件:"):
            excerpt.append(line[2:])
        else:
            flush()
            key, excerpt = "", []
    return contents


def visible_excerpt_identities(material: str) -> set[tuple[str, str]]:
    return {(key, hashlib.sha256(body.encode("utf-8", errors="surrogatepass")).hexdigest())
            for key, body in visible_excerpt_contents(material)}


def excerpt_already_visible(candidate: str, material: str) -> bool:
    """A shorter view of an already readable paragraph adds no source content."""
    proposed = visible_excerpt_contents(candidate)
    existing = visible_excerpt_contents(material)
    return bool(proposed) and all(
        any(key == old_key and body.strip("…") in old_body.strip("…")
            for old_key, old_body in existing)
        for key, body in proposed)


_VISIBLE_PROGRESS_TEXT = (
        "【可见证据变化】本轮首次展示的摘录视图：{added}；当前可见视图：{current}。"
        "此数按实际展示的 key 与摘录内容去重，候选池新增数不代表新增可读依据；"
        "恢复同一摘录或更换查询不计新增。先用已展示的机制句判断能否回答；"
        "如仍缺依据，只针对明确缺失的内容检索。零新增不等于问题已解决。"
)


def render_visible_progress(seen: set[tuple[str, str]], material: str) -> str:
    current = visible_excerpt_identities(material)
    added = len(current - seen)
    seen.update(current)
    return _VISIBLE_PROGRESS_TEXT.format(added=added, current=len(current))


def render_prose_progress(
    seen: set[tuple[str, str]], detail_seen: set[tuple[str, str]], material: str,
    detail_cards: Mapping[str, str] | None, source_keys: Collection[str],
    history_left: int,
) -> str:
    """Track final excerpts even when the optional feedback cannot be emitted.

    Candidate selection or version allocation is not visibility. Only a detail
    body surviving final K/D admission can activate this note, and its key must
    still be authorized by the current source pool. The note uses unused history
    space; it never asks a caller to compact or replace previously sent history.
    """
    current = visible_excerpt_identities(material)
    added = len(current - seen)
    seen.update(current)
    if detail_cards is None:
        return ""
    proposed = visible_excerpt_identities("\n".join(detail_cards.values()))
    detail_seen.update(current & proposed)
    if not any(key in source_keys for key, _ in current & detail_seen):
        return ""
    note = _VISIBLE_PROGRESS_TEXT.format(added=added, current=len(current))
    return note if len(note) + len("\n\n") <= history_left else ""
