"""knowhow 单表整表指纹：跨 store 共享的唯一定义点。

原属 KnowhowTransferStore（为 move_table 的并发编辑守卫而写）。版本管理
（docs/superpowers/specs/2026-07-22-knowhow-table-version-control-design.md）
把它同时用作**回退重放正确性的判据**，两个 store 都要用，故抽到这里，
KnowhowTransferStore 保留同对象别名不破坏既有引用。

⚠️ 改动 FINGERPRINT_SQL 前必读：它现在有两个身份。
  1. move_table 的"源表在复制后被改过吗"探针（原有）。
  2. knowhow_changes 每条流水记录的 fingerprint，回退前后各校验一次（新增）。
身份 2 依赖两个性质，动 SQL 时必须保住：
  · 覆盖范围 == 版本管理的"全盖"范围（表元/列/行/格子/代码附件）；
  · **不含 updated_at 时间戳** —— 回退会写新的时间戳，若指纹覆盖它，
    回退后的后置校验将永远失败，整个回退功能不成立。
"""
from __future__ import annotations

import hashlib
import sqlite3


#: Shared by ``table_fingerprint`` (own ``connect()``) and
#: ``delete_table_if_unchanged`` (caller-supplied connection inside its
#: own ``write()``) so the two never drift apart — see both methods'
#: docstrings for why they must run the byte-identical query.
#:
#: PR review round 5 P1-1 (ROOT FIX — see ``table_fingerprint``'s
#: docstring for the full history/rationale): rather than a growing list
#: of individually-enumerated signals (``mutation_seq``, then four
#: counts, then a cell_code content signal — rounds 2/3), this is now a
#: structurally-complete projection of every field ``snapshot_table``/
#: ``insert_transfer`` actually copy as business data: knowhow_tables.
#: {title,description} (scalar — one row), then one canonically-ordered
#: ``group_concat`` per child table covering EVERY column that table
#: reproduces: knowhow_columns.{id,name,role,position}, knowhow_rows.
#: {id,position}, knowhow_cells.{row_id,column_id,content_md},
#: knowhow_cell_code.{row_id,column_id,code_text,language,
#: cell_content_hash,updated_by}. Deliberately excluded: mutation_seq/
#: created_at/updated_at/hidden_source_id/created_by on knowhow_tables
#: (rewritten or dropped by ``_remap`` — never "the copied content", see
#: transfer.py) and the surrogate ``id`` columns on knowhow_cells/
#: knowhow_cell_code (their real identity is the (row_id, column_id)
#: pair the UNIQUE constraint already keys on; the id is regenerated by
#: ``_remap`` on every copy regardless of content).
#:
#: PR review round 7 P2-B: ``updated_by`` on ``knowhow_cell_code`` was
#: missing from the list above despite ``_remap`` copying it unchanged
#: (``code = dict(code)`` — only id/row_id/column_id get overwritten).
#: An agent rewriting an attachment with IDENTICAL code/language/
#: content-hash but a DIFFERENT ``updated_by`` left every other cell_
#: code field unchanged, so the fingerprint was blind to it — a
#: concurrent rewrite of exactly that shape would sail past ``move_
#: table``'s recheck and the target would keep the OLDER attribution
#: forever. This is the same "structurally complete, not enumerated"
#: mandate the rest of this comment already states — ``updated_by`` is
#: just the one field the original round-5 pass missed.
#:
#: Each per-row tuple is joined with ``char(31)`` (ASCII unit
#: separator) and rows within a group with ``char(30)`` (ASCII record
#: separator) — control characters chosen (not e.g. ``:``/``|``, round
#: 3's choice) specifically because real column names/cell content are
#: free text that could plausibly contain punctuation but essentially
#: never contains non-printable separator characters designed for
#: exactly this purpose. Ordering is by each group's own natural stable
#: key (``id`` for columns/rows — unique, immutable once assigned; the
#: UNIQUE(row_id, column_id) pair for cells/cell_code) via a subquery's
#: ``ORDER BY`` — same idiom round 3 already established (and round 3's
#: own test_fingerprint_stable_when_nothing_changes already proves it
#: reproducible across calls) rather than the newer, version-sensitive
#: ``group_concat(x ORDER BY y)`` syntax. Ordering by ``id`` (a key that
#: never changes value under any of these edits) rather than a
#: mutable field like ``position`` is what makes a pure VALUE swap
#: between two rows (e.g. two columns trading positions) show up as a
#: hash change: the tuple at a given id's slot in the sequence differs,
#: even though the multiset of column ids present is unchanged.
FINGERPRINT_SQL = (
    "SELECT t.title AS title, t.description AS description, "
    "(SELECT group_concat(sig, char(30)) FROM ("
    "  SELECT id || char(31) || name || char(31) || role || char(31) || position AS sig"
    "  FROM knowhow_columns WHERE table_id = t.id ORDER BY id"
    ")) AS columns_signal, "
    "(SELECT group_concat(sig, char(30)) FROM ("
    "  SELECT id || char(31) || position AS sig"
    "  FROM knowhow_rows WHERE table_id = t.id ORDER BY id"
    ")) AS rows_signal, "
    "(SELECT group_concat(sig, char(30)) FROM ("
    "  SELECT c.row_id || char(31) || c.column_id || char(31) || c.content_md AS sig"
    "  FROM knowhow_cells c JOIN knowhow_rows r ON r.id = c.row_id"
    "  WHERE r.table_id = t.id ORDER BY c.row_id, c.column_id"
    ")) AS cells_signal, "
    "(SELECT group_concat(sig, char(30)) FROM ("
    "  SELECT cc.row_id || char(31) || cc.column_id || char(31) || cc.code_text"
    "    || char(31) || cc.language || char(31) || cc.cell_content_hash"
    "    || char(31) || cc.updated_by AS sig"
    "  FROM knowhow_cell_code cc JOIN knowhow_rows r ON r.id = cc.row_id"
    "  WHERE r.table_id = t.id ORDER BY cc.row_id, cc.column_id"
    ")) AS cell_code_signal "
    "FROM knowhow_tables t WHERE t.id = ?"
)

#: ASCII group separator, joining the five top-level signals (table
#: meta / columns / rows / cells / cell_code) before hashing — one more
#: level up from the ``char(30)``/``char(31)`` levels inside
#: ``_FINGERPRINT_SQL`` itself (the standard US < RS < GS ASCII
#: separator hierarchy, used here exactly as designed).
GROUP_SEP = "\x1d"


def fingerprint_on(db: sqlite3.Connection, table_id: str) -> "str | None":
    """在调用方给定的连接上算一次整表指纹；表不存在返回 None。"""
    row = db.execute(FINGERPRINT_SQL, (table_id,)).fetchone()
    if row is None:
        return None
    parts = [
        row["title"],
        row["description"],
        row["columns_signal"] or "",
        row["rows_signal"] or "",
        row["cells_signal"] or "",
        row["cell_code_signal"] or "",
    ]
    canonical = GROUP_SEP.join(parts)
    return hashlib.sha256(canonical.encode("utf-8")).hexdigest()
