#!/usr/bin/env python3
"""Check a committed frontend UI extension contract against *this deployment's*
live plugin topology.

`backend/tests/fixtures/ui_extension_contract.json` (regenerated by
`scripts/generate_ui_extension_contract.py`) only ever reflects the builtin
topology plus whatever the checked-out source tree ships — it is generated
with `EXTENSIONS_CONFIG` cleared (see `scripts/check.sh`) so CI never sees a
site's deployment plugins. An operator who has configured `EXTENSIONS_CONFIG`
for a real deployment has no way to ask "does the frontend I built still
match the plugins that will actually load here" — that is the question this
script answers, run *after* the site's own `EXTENSIONS_CONFIG` is in the
environment, against a frontend contract JSON of the same shape (produced the
same way the committed fixture is: by pointing a build at
`GET /system/extensions` or by exporting `WORKSPACE_UI_CONTRIBUTIONS`,
whichever the deployment's frontend build already keeps around).

Usage:
    EXTENSIONS_CONFIG=/etc/silicon/extensions.toml PYTHONPATH=<repo>/backend \\
      python3 scripts/check_deployment_extension_parity.py \\
      --frontend-contract <path-to-contract.json>

The `--frontend-contract` file must have the shape
`{"api_version": "1", "contributions": [{"plugin_id", "version",
"contribution_id", "slot", "capability"}, ...]}` — the exact shape
`scripts/generate_ui_extension_contract.py` writes.

This script is read-only end to end: it never writes a file, never
constructs a `Repository` (it only touches `default_extension_runtime()`,
which is discovery + registry composition, not persistence), and never makes
a network call. It shares its comparator with `generate_ui_extension_contract.py`
via the public `contract_rows_match` / `contract_diff` functions — there is
exactly one implementation of "do two fixture dicts describe the same
contribution set", reused rather than re-spelled here.

Exit codes:
    0  parity — the live deployment topology matches the frontend contract.
    1  drift — the sets differ; a per-row diff (five wire fields only) is
       printed to stderr.
    2  usage/environment error — missing/unreadable `--frontend-contract`,
       malformed JSON, an `api_version` other than `"1"`, or this
       deployment's own plugin discovery/registry composition failed. On a
       discovery failure only the offending plugin id and its stable reason
       code are printed (never a settings value, module path, or exception
       text — the same sanitization `ExtensionDiscoveryError` already
       enforces at startup); on a registry composition failure the message is
       the registry's own text, which is structurally limited to ids and
       hard-coded phrases and never touches a settings value.

`check_contracts.sh` deliberately does *not* run this script — CI has no
`EXTENSIONS_CONFIG` deployment to check against; it is an operator tool run
against a real site's environment.
"""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "backend"))
sys.path.insert(0, str(Path(__file__).resolve().parent))

from app.extensions import (  # noqa: E402
    ExtensionDiscoveryError,
    ExtensionRegistryError,
    default_extension_runtime,
)
from app.extensions.ui_projection import ui_contribution_contract  # noqa: E402

from generate_ui_extension_contract import (  # noqa: E402
    API_VERSION,
    contract_diff,
    contract_rows_match,
)


def _parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--frontend-contract",
        required=True,
        type=Path,
        metavar="PATH",
        help=(
            "path to a frontend UI extension contract JSON "
            '({"api_version": "1", "contributions": [...]}) to check against '
            "this process's live EXTENSIONS_CONFIG topology"
        ),
    )
    return parser


def main(argv: list[str] | None = None) -> int:
    args = _parser().parse_args(argv)
    contract_path: Path = args.frontend_contract

    if not contract_path.exists():
        print(f"frontend contract not found: {contract_path}", file=sys.stderr)
        return 2

    try:
        raw = contract_path.read_text(encoding="utf-8")
    except OSError as exc:
        print(f"frontend contract unreadable: {contract_path}: {exc}", file=sys.stderr)
        return 2

    try:
        committed = json.loads(raw)
    except json.JSONDecodeError as exc:
        print(
            f"frontend contract is not valid JSON: {contract_path}\n  parse error: {exc}",
            file=sys.stderr,
        )
        return 2

    committed_version = committed.get("api_version") if isinstance(committed, dict) else None
    if committed_version != API_VERSION:
        print(
            f"frontend contract api_version must be {API_VERSION!r}, got {committed_version!r}",
            file=sys.stderr,
        )
        return 2

    try:
        registry = default_extension_runtime().registry
    except ExtensionDiscoveryError as exc:
        # Mirrors the sanitization `default_extension_runtime()` itself applies
        # at startup (backend/app/extensions/bootstrap.py): plugin id + stable
        # reason code only, never a settings value, module path, file path, or
        # upstream exception text.
        print(
            f"deployment extension discovery failed: plugin={exc.plugin_id!r} reason={exc.reason}",
            file=sys.stderr,
        )
        return 2
    except ExtensionRegistryError as exc:
        # ExtensionRegistryError carries no structured plugin_id/reason (unlike
        # ExtensionDiscoveryError above) — its message text is itself already
        # limited to manifest/contribution ids and hard-coded phrases (see
        # every `raise ExtensionRegistryError(...)` call site in
        # backend/app/extensions/registry.py), so it is safe to print verbatim.
        print(f"deployment extension registry rejected the topology: {exc}", file=sys.stderr)
        return 2

    live = {
        "api_version": API_VERSION,
        "contributions": ui_contribution_contract(registry),
    }

    if contract_rows_match(committed, live):
        print(
            "deployment UI extension contract OK "
            f"({len(live['contributions'])} contributions)"
        )
        return 0

    print(
        "deployment UI extension contract DRIFT — this deployment's live plugin "
        f"topology no longer matches {contract_path}.",
        file=sys.stderr,
    )
    for line in contract_diff(committed, live):
        print(f"  {line}", file=sys.stderr)
    return 1


if __name__ == "__main__":
    raise SystemExit(main())
