#!/usr/bin/env python3
"""Regenerate (or, with --check, verify) the generated half of
`backend/app/repositories/postgres/migrations/0064_sync_change_capture.sql`
from `app.migration.sync.capture`.

That migration carries one plpgsql trigger function and one row trigger per
synced business table (46 of each). They are not hand-written: the same
generator renders the SQLite triggers `_migration_84` installs, the
expectations `scripts/verify_repository_snapshot.py` holds a migrated database
to, and this file. `app.migration.shadow.postgres_catalog` then parses the
function bodies and trigger statements straight back out of this file and
holds the live PostgreSQL catalog to them, so an edit here is a schema change,
not a comment fix.

Only the text BELOW the generated marker is rendered. Everything above it --
the header, the two control tables, the de-duplication and the two composite
primary keys -- is hand-written and this script preserves it byte for byte, so
re-rendering after a manifest change never silently rewrites the hand-written
half.

Usage:
    python3 scripts/generate_sync_capture_migration.py          # rewrite the file
    python3 scripts/generate_sync_capture_migration.py --check  # verify only, no write

--check exits non-zero and names the first differing line when the committed
migration is stale (e.g. a table was added to the sync manifest but the
migration was not re-rendered). It is wired into scripts/check_contracts.sh,
the same way `generate_ui_extension_contract.py --check` is, so a stale
migration fails the contracts lane rather than waiting for the backend lane's
`backend/tests/test_sync_capture.py`.

Re-rendering an ALREADY APPLIED migration is not a normal operation: a
deployed database has the old text's checksum in `silicon_schema_migrations`
and would refuse to start (see `PostgresMigrator._validate_ledger`). This
script exists for the window in which 0064 is still unreleased, and for
reviewers who want to prove the committed text is what the generator produces.
"""
from __future__ import annotations

import argparse
import difflib
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "backend"))

from app.migration.sync.capture import (  # noqa: E402
    postgres_function_sql,
    postgres_trigger_sql,
)


MIGRATION_PATH = (
    ROOT
    / "backend"
    / "app"
    / "repositories"
    / "postgres"
    / "migrations"
    / "0064_sync_change_capture.sql"
)
# The hand-written half ends here; this exact line must appear once.
GENERATED_MARKER = (
    "-- --- generated by backend/app/migration/sync/capture.py "
    "---------------------\n"
)


def render_generated_half() -> str:
    """Every function immediately followed by its own trigger, in the sync
    manifest's copy order, blank-line separated."""
    triggers = postgres_trigger_sql()
    blocks: list[str] = []
    for _name, (table, function_sql) in postgres_function_sql().items():
        trigger_sql = triggers[f"sync_capture_{table}"][1]
        blocks.append(f"{function_sql};\n{trigger_sql};\n")
    return "\n".join(blocks)


def render_migration(committed: str) -> str:
    """The full file: the committed hand-written prefix plus a fresh
    generated half."""
    parts = committed.split(GENERATED_MARKER)
    if len(parts) != 2:
        raise SystemExit(
            f"{MIGRATION_PATH}: expected exactly one generated marker, "
            f"found {len(parts) - 1}"
        )
    return parts[0] + GENERATED_MARKER + render_generated_half()


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="verify the committed migration matches the generator; do not write",
    )
    arguments = parser.parse_args()

    committed = MIGRATION_PATH.read_text(encoding="utf-8")
    rendered = render_migration(committed)
    if committed == rendered:
        if not arguments.check:
            print(f"sync capture migration: unchanged ({MIGRATION_PATH.name})")
        return 0
    if arguments.check:
        diff = list(
            difflib.unified_diff(
                committed.splitlines(keepends=True),
                rendered.splitlines(keepends=True),
                fromfile="committed",
                tofile="generated",
                n=1,
            )
        )
        sys.stderr.write(
            f"{MIGRATION_PATH.name} is stale; re-run "
            "`python3 scripts/generate_sync_capture_migration.py`\n"
        )
        sys.stderr.writelines(diff[:40])
        return 1
    MIGRATION_PATH.write_text(rendered, encoding="utf-8")
    print(f"sync capture migration: rewritten ({MIGRATION_PATH.name})")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
